// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cypherpanel/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentStatus is the agent's self-reported liveness, carried on heartbeats.
// It is distinct from the resource/server status vocabulary in ui-principles
// §5 — the control plane derives `running`/`unknown` from heartbeat recency,
// never trusting the agent to assert its own reachability.
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_READY       AgentStatus = 1
	AgentStatus_AGENT_STATUS_DEGRADED    AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_READY",
		2: "AGENT_STATUS_DEGRADED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_READY":       1,
		"AGENT_STATUS_DEGRADED":    2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cypherpanel_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_cypherpanel_agent_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_cypherpanel_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single-use join token issued by the control plane operator.
	JoinToken string `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	// PEM-encoded PKCS#10 certificate signing request. The agent holds the
	// corresponding private key; it never leaves the agent host.
	CsrPem []byte `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Agent build version, for the fleet-version visibility ADR-010 will need.
	AgentVersion string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Reported hostname, advisory only (used for display; identity is the cert).
	Hostname      string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_cypherpanel_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable server identifier the agent uses in its subjects (state.*.<id>).
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// PEM-encoded client certificate signed by the control-plane CA.
	CertificatePem []byte `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	// PEM-encoded CA certificate the agent pins to verify the control plane.
	CaPem []byte `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// URL the agent dials for the NATS data-plane connection (mTLS).
	NatsUrl       string `protobuf:"bytes,4,opt,name=nats_url,json=natsUrl,proto3" json:"nats_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_cypherpanel_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *EnrollResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *EnrollResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollResponse) GetNatsUrl() string {
	if x != nil {
		return x.NatsUrl
	}
	return ""
}

// RenewRequest asks the plane to re-sign this agent's identity.
type RenewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server id the caller believes it is. It is NOT what authorizes the
	// call — the verified client certificate's CommonName is — but the plane
	// refuses a request whose claim disagrees with the peer identity, so an
	// agent can never renew (or accidentally overwrite) another server's
	// certificate, and a mismatch is a loud failure instead of a silent
	// re-issue under the wrong name.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// PEM-encoded PKCS#10 certificate signing request for the agent's new key
	// pair. As with Enroll, the plane signs the key and dictates the subject.
	CsrPem []byte `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Agent build version, recorded the same way Enroll records it so fleet
	// version visibility survives re-enrollment-free lifetimes (ADR-010).
	AgentVersion  string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_cypherpanel_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RenewRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RenewRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *RenewRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// RenewResponse carries the re-signed identity. The server id, the NATS URL
// and the CA are unchanged by a renewal — only the certificate is new — so the
// agent rewrites its certificate and nothing else.
type RenewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded client certificate signed by the control-plane CA, with the
	// same CommonName the caller already had.
	CertificatePem []byte `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	// PEM-encoded CA certificate, echoed so an agent that renews across a CA
	// rotation is not left pinning material the plane no longer uses.
	CaPem []byte `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// Expiry of the new certificate. The agent derives its next renewal from the
	// certificate itself; this field is for logging and for an agent that wants
	// to check the plane agreed with its own parse.
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_cypherpanel_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RenewResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *RenewResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *RenewResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

// Heartbeat is published by the agent to the NATS subject
// `state.heartbeat.<server_id>` (ADR-003, subject family state.*).
//
// It is transient coordination traffic: Postgres remains the single state of
// record (ENGINEERING rule 15). The plane updates a server's observed status
// and last-seen time from these; absence of heartbeats is what drives the
// `unknown` status, never a stale cached value (ui-principles §10).
type Heartbeat struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ServerId     string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	EmittedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	AgentVersion string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Active orchestrator driver on this agent (e.g. "docker"). Phase 1 agents
	// report their configured driver without yet reconciling workloads.
	Driver string      `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	Status AgentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=cypherpanel.agent.v1.AgentStatus" json:"status,omitempty"`
	// Role the agent runs with: "all" (default), "builder", or "worker"
	// (builder-role-and-relay.md §1). Routing input only — relay operations are
	// authorized per-deployment, never from this claim.
	Role          string `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cypherpanel_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_cypherpanel_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Heartbeat) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *Heartbeat) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Heartbeat) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Heartbeat) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *Heartbeat) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_cypherpanel_agent_v1_agent_proto protoreflect.FileDescriptor

const file_cypherpanel_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	" cypherpanel/agent/v1/agent.proto\x12\x14cypherpanel.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\rEnrollRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\x88\x01\n" +
	"\x0eEnrollResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\fR\x0ecertificatePem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\fR\x05caPem\x12\x19\n" +
	"\bnats_url\x18\x04 \x01(\tR\anatsUrl\"i\n" +
	"\fRenewRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\"\x88\x01\n" +
	"\rRenewResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\fR\x05caPem\x127\n" +
	"\tnot_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"\xef\x01\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x129\n" +
	"\n" +
	"emitted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.cypherpanel.agent.v1.AgentStatusR\x06status\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role*^\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AGENT_STATUS_READY\x10\x01\x12\x19\n" +
	"\x15AGENT_STATUS_DEGRADED\x10\x022\xba\x01\n" +
	"\x11EnrollmentService\x12S\n" +
	"\x06Enroll\x12#.cypherpanel.agent.v1.EnrollRequest\x1a$.cypherpanel.agent.v1.EnrollResponse\x12P\n" +
	"\x05Renew\x12\".cypherpanel.agent.v1.RenewRequest\x1a#.cypherpanel.agent.v1.RenewResponseBKZIgithub.com/MaramHarsha/cypherpanel/pkg/proto/cypherpanel/agent/v1;agentv1b\x06proto3"

var (
	file_cypherpanel_agent_v1_agent_proto_rawDescOnce sync.Once
	file_cypherpanel_agent_v1_agent_proto_rawDescData []byte
)

func file_cypherpanel_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_cypherpanel_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_cypherpanel_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cypherpanel_agent_v1_agent_proto_rawDesc), len(file_cypherpanel_agent_v1_agent_proto_rawDesc)))
	})
	return file_cypherpanel_agent_v1_agent_proto_rawDescData
}

var file_cypherpanel_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cypherpanel_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cypherpanel_agent_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),              // 0: cypherpanel.agent.v1.AgentStatus
	(*EnrollRequest)(nil),         // 1: cypherpanel.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 2: cypherpanel.agent.v1.EnrollResponse
	(*RenewRequest)(nil),          // 3: cypherpanel.agent.v1.RenewRequest
	(*RenewResponse)(nil),         // 4: cypherpanel.agent.v1.RenewResponse
	(*Heartbeat)(nil),             // 5: cypherpanel.agent.v1.Heartbeat
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_cypherpanel_agent_v1_agent_proto_depIdxs = []int32{
	6, // 0: cypherpanel.agent.v1.RenewResponse.not_after:type_name -> google.protobuf.Timestamp
	6, // 1: cypherpanel.agent.v1.Heartbeat.emitted_at:type_name -> google.protobuf.Timestamp
	0, // 2: cypherpanel.agent.v1.Heartbeat.status:type_name -> cypherpanel.agent.v1.AgentStatus
	1, // 3: cypherpanel.agent.v1.EnrollmentService.Enroll:input_type -> cypherpanel.agent.v1.EnrollRequest
	3, // 4: cypherpanel.agent.v1.EnrollmentService.Renew:input_type -> cypherpanel.agent.v1.RenewRequest
	2, // 5: cypherpanel.agent.v1.EnrollmentService.Enroll:output_type -> cypherpanel.agent.v1.EnrollResponse
	4, // 6: cypherpanel.agent.v1.EnrollmentService.Renew:output_type -> cypherpanel.agent.v1.RenewResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cypherpanel_agent_v1_agent_proto_init() }
func file_cypherpanel_agent_v1_agent_proto_init() {
	if File_cypherpanel_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cypherpanel_agent_v1_agent_proto_rawDesc), len(file_cypherpanel_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cypherpanel_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_cypherpanel_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_cypherpanel_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_cypherpanel_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_cypherpanel_agent_v1_agent_proto = out.File
	file_cypherpanel_agent_v1_agent_proto_goTypes = nil
	file_cypherpanel_agent_v1_agent_proto_depIdxs = nil
}
