// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessRequest = `-- name: CreateAccessRequest :one

INSERT INTO access_requests (id, team_id, user_id, requested_role, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, team_id, user_id, requested_role, message, state, decided_by, decided_by_label, decision_reason, decided_at, created_at
`

type CreateAccessRequestParams struct {
	ID            string
	TeamID        string
	UserID        string
	RequestedRole string
	Message       string
}

// Access requests (invitations-and-access-requests.md §2, §5): a member asking
// a team's owners for a higher rank. No secret, no bearer token — the row IS
// the ask, and the two decision verbs are the only mutations.
func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, createAccessRequest,
		arg.ID,
		arg.TeamID,
		arg.UserID,
		arg.RequestedRole,
		arg.Message,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RequestedRole,
		&i.Message,
		&i.State,
		&i.DecidedBy,
		&i.DecidedByLabel,
		&i.DecisionReason,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const decideAccessRequest = `-- name: DecideAccessRequest :one
UPDATE access_requests
SET state = $1, decided_by = $2, decided_by_label = $3,
    decision_reason = $4, decided_at = now()
WHERE id = $5 AND state = 'pending'
RETURNING id, team_id, user_id, requested_role, message, state, decided_by, decided_by_label, decision_reason, decided_at, created_at
`

type DecideAccessRequestParams struct {
	State          string
	DecidedBy      pgtype.Text
	DecidedByLabel string
	DecisionReason string
	ID             string
}

// DecideAccessRequest is the single decision statement for both verbs: no row
// back means it was already decided, which is the only race-free way to keep
// "one decision per request" true when two owners click at once.
func (q *Queries) DecideAccessRequest(ctx context.Context, arg DecideAccessRequestParams) (AccessRequest, error) {
	row := q.db.QueryRow(ctx, decideAccessRequest,
		arg.State,
		arg.DecidedBy,
		arg.DecidedByLabel,
		arg.DecisionReason,
		arg.ID,
	)
	var i AccessRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RequestedRole,
		&i.Message,
		&i.State,
		&i.DecidedBy,
		&i.DecidedByLabel,
		&i.DecisionReason,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessRequest = `-- name: GetAccessRequest :one
SELECT r.id, r.team_id, r.user_id, r.requested_role, r.message, r.state, r.decided_by, r.decided_by_label, r.decision_reason, r.decided_at, r.created_at, u.email AS user_email, COALESCE(m.role, '') AS current_role
FROM access_requests r
JOIN users u ON u.id = r.user_id
LEFT JOIN team_members m ON m.team_id = r.team_id AND m.user_id = r.user_id
WHERE r.id = $1
`

type GetAccessRequestRow struct {
	ID             string
	TeamID         string
	UserID         string
	RequestedRole  string
	Message        string
	State          string
	DecidedBy      pgtype.Text
	DecidedByLabel string
	DecisionReason string
	DecidedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UserEmail      string
	CurrentRole    string
}

// GetAccessRequest also carries the requester's address and their CURRENT role
// in the team, both derived at read time: the owner's card says
// "member → admin" without a second call, and it says it about the membership
// as it stands now rather than as it stood when the ask was made.
func (q *Queries) GetAccessRequest(ctx context.Context, id string) (GetAccessRequestRow, error) {
	row := q.db.QueryRow(ctx, getAccessRequest, id)
	var i GetAccessRequestRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.RequestedRole,
		&i.Message,
		&i.State,
		&i.DecidedBy,
		&i.DecidedByLabel,
		&i.DecisionReason,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UserEmail,
		&i.CurrentRole,
	)
	return i, err
}

const listAccessRequests = `-- name: ListAccessRequests :many
SELECT r.id, r.team_id, r.user_id, r.requested_role, r.message, r.state, r.decided_by, r.decided_by_label, r.decision_reason, r.decided_at, r.created_at, u.email AS user_email, COALESCE(m.role, '') AS current_role
FROM access_requests r
JOIN users u ON u.id = r.user_id
LEFT JOIN team_members m ON m.team_id = r.team_id AND m.user_id = r.user_id
WHERE r.team_id = $1
  AND ($2::boolean OR r.state = 'pending')
ORDER BY r.created_at DESC
`

type ListAccessRequestsParams struct {
	TeamID         string
	IncludeDecided bool
}

type ListAccessRequestsRow struct {
	ID             string
	TeamID         string
	UserID         string
	RequestedRole  string
	Message        string
	State          string
	DecidedBy      pgtype.Text
	DecidedByLabel string
	DecisionReason string
	DecidedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UserEmail      string
	CurrentRole    string
}

func (q *Queries) ListAccessRequests(ctx context.Context, arg ListAccessRequestsParams) ([]ListAccessRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAccessRequests, arg.TeamID, arg.IncludeDecided)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessRequestsRow{}
	for rows.Next() {
		var i ListAccessRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.RequestedRole,
			&i.Message,
			&i.State,
			&i.DecidedBy,
			&i.DecidedByLabel,
			&i.DecisionReason,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UserEmail,
			&i.CurrentRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamOwnerEmails = `-- name: ListTeamOwnerEmails :many
SELECT u.email
FROM team_members m
JOIN users u ON u.id = m.user_id
WHERE m.team_id = $1 AND m.role = 'owner'
ORDER BY u.email
`

// ListTeamOwnerEmails is who a pending request is mailed to (§6). It is the
// membership join, not a role column on users: a panel owner's implicit
// team-owner rank is an authorization escape hatch, never an opinion about
// whose mailbox should receive a team's business — the same reasoning
// ListInboxRecipients states.
func (q *Queries) ListTeamOwnerEmails(ctx context.Context, teamID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTeamOwnerEmails, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
