// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_env_vars.sql

package db

import (
	"context"
)

const deleteEnvVar = `-- name: DeleteEnvVar :exec
DELETE FROM app_env_vars WHERE application_id = $1 AND key = $2
`

type DeleteEnvVarParams struct {
	ApplicationID string
	Key           string
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteEnvVar, arg.ApplicationID, arg.Key)
	return err
}

const listEnvVarKeys = `-- name: ListEnvVarKeys :many
SELECT key, shared_refs FROM app_env_vars WHERE application_id = $1 ORDER BY key
`

type ListEnvVarKeysRow struct {
	Key        string
	SharedRefs []string
}

// Keys and their shared-variable references, never the sealed value. This
// exists so core/export's Store interface can be structurally incapable of
// returning a ciphertext (project-export.md §4): ListEnvVars returns
// value_ct/value_nonce, and an exporter that could call it would be one
// serialization mistake away from a download containing every secret.
func (q *Queries) ListEnvVarKeys(ctx context.Context, applicationID string) ([]ListEnvVarKeysRow, error) {
	rows, err := q.db.Query(ctx, listEnvVarKeys, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvVarKeysRow{}
	for rows.Next() {
		var i ListEnvVarKeysRow
		if err := rows.Scan(&i.Key, &i.SharedRefs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVars = `-- name: ListEnvVars :many
SELECT application_id, key, value_ct, value_nonce, shared_refs FROM app_env_vars WHERE application_id = $1 ORDER BY key
`

func (q *Queries) ListEnvVars(ctx context.Context, applicationID string) ([]AppEnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVars, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppEnvVar{}
	for rows.Next() {
		var i AppEnvVar
		if err := rows.Scan(
			&i.ApplicationID,
			&i.Key,
			&i.ValueCt,
			&i.ValueNonce,
			&i.SharedRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :exec
INSERT INTO app_env_vars (application_id, key, value_ct, value_nonce, shared_refs)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (application_id, key)
DO UPDATE SET value_ct = EXCLUDED.value_ct,
              value_nonce = EXCLUDED.value_nonce,
              shared_refs = EXCLUDED.shared_refs
`

type UpsertEnvVarParams struct {
	ApplicationID string
	Key           string
	ValueCt       []byte
	ValueNonce    []byte
	SharedRefs    []string
}

func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) error {
	_, err := q.db.Exec(ctx, upsertEnvVar,
		arg.ApplicationID,
		arg.Key,
		arg.ValueCt,
		arg.ValueNonce,
		arg.SharedRefs,
	)
	return err
}
