// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    id, environment_id, name,
    source_kind, source_repo, source_branch, source_deploy_key_id,
    build_kind, build_dockerfile_path, build_context,
    runtime_server_id, runtime_port, runtime_replicas,
    route_domain, route_https, route_path_prefix,
    health_path, health_interval_seconds, health_timeout_seconds, health_retries,
    webhook_id, webhook_secret_ct, webhook_secret_nonce
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19, $20,
    $21, $22, $23
)
RETURNING id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at
`

type CreateApplicationParams struct {
	ID                    string
	EnvironmentID         string
	Name                  string
	SourceKind            string
	SourceRepo            string
	SourceBranch          string
	SourceDeployKeyID     pgtype.Text
	BuildKind             string
	BuildDockerfilePath   string
	BuildContext          string
	RuntimeServerID       string
	RuntimePort           int32
	RuntimeReplicas       int32
	RouteDomain           string
	RouteHttps            bool
	RoutePathPrefix       string
	HealthPath            string
	HealthIntervalSeconds int32
	HealthTimeoutSeconds  int32
	HealthRetries         int32
	WebhookID             string
	WebhookSecretCt       []byte
	WebhookSecretNonce    []byte
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.SourceKind,
		arg.SourceRepo,
		arg.SourceBranch,
		arg.SourceDeployKeyID,
		arg.BuildKind,
		arg.BuildDockerfilePath,
		arg.BuildContext,
		arg.RuntimeServerID,
		arg.RuntimePort,
		arg.RuntimeReplicas,
		arg.RouteDomain,
		arg.RouteHttps,
		arg.RoutePathPrefix,
		arg.HealthPath,
		arg.HealthIntervalSeconds,
		arg.HealthTimeoutSeconds,
		arg.HealthRetries,
		arg.WebhookID,
		arg.WebhookSecretCt,
		arg.WebhookSecretNonce,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByWebhookID = `-- name: GetApplicationByWebhookID :one
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at FROM applications WHERE webhook_id = $1
`

func (q *Queries) GetApplicationByWebhookID(ctx context.Context, webhookID string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByWebhookID, webhookID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsByEnvironment = `-- name: ListApplicationsByEnvironment :many
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at FROM applications WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByEnvironment(ctx context.Context, environmentID string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.SourceKind,
			&i.SourceRepo,
			&i.SourceBranch,
			&i.SourceDeployKeyID,
			&i.BuildKind,
			&i.BuildDockerfilePath,
			&i.BuildContext,
			&i.RuntimeServerID,
			&i.RuntimePort,
			&i.RuntimeReplicas,
			&i.RouteDomain,
			&i.RouteHttps,
			&i.RoutePathPrefix,
			&i.HealthPath,
			&i.HealthIntervalSeconds,
			&i.HealthTimeoutSeconds,
			&i.HealthRetries,
			&i.WebhookID,
			&i.WebhookSecretCt,
			&i.WebhookSecretNonce,
			&i.DesiredRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByServer = `-- name: ListApplicationsByServer :many
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at FROM applications WHERE runtime_server_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByServer(ctx context.Context, runtimeServerID string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByServer, runtimeServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.SourceKind,
			&i.SourceRepo,
			&i.SourceBranch,
			&i.SourceDeployKeyID,
			&i.BuildKind,
			&i.BuildDockerfilePath,
			&i.BuildContext,
			&i.RuntimeServerID,
			&i.RuntimePort,
			&i.RuntimeReplicas,
			&i.RouteDomain,
			&i.RouteHttps,
			&i.RoutePathPrefix,
			&i.HealthPath,
			&i.HealthIntervalSeconds,
			&i.HealthTimeoutSeconds,
			&i.HealthRetries,
			&i.WebhookID,
			&i.WebhookSecretCt,
			&i.WebhookSecretNonce,
			&i.DesiredRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationDesiredRevision = `-- name: SetApplicationDesiredRevision :one
UPDATE applications
SET desired_revision_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at
`

type SetApplicationDesiredRevisionParams struct {
	ID                string
	DesiredRevisionID pgtype.Text
}

func (q *Queries) SetApplicationDesiredRevision(ctx context.Context, arg SetApplicationDesiredRevisionParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationDesiredRevision, arg.ID, arg.DesiredRevisionID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
