// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    id, environment_id, name,
    source_kind, source_repo, source_branch, source_deploy_key_id,
    build_kind, build_dockerfile_path, build_context,
    runtime_server_id, runtime_port, runtime_replicas,
    route_domain, route_https, route_path_prefix,
    health_path, health_interval_seconds, health_timeout_seconds, health_retries,
    webhook_id, webhook_secret_ct, webhook_secret_nonce,
    preview_enabled, preview_base_domain, preview_ttl_hours,
    cpu_limit, memory_limit_mb, volumes,
    ports, health_kind, source_image
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19, $20,
    $21, $22, $23,
    $24, $25, $26,
    $27, $28, $29,
    $30, $31, $32
)
RETURNING id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at, status, status_detail, observed_revision_id, status_observed_at, preview_enabled, preview_base_domain, preview_ttl_hours, cpu_limit, memory_limit_mb, volumes, ports, health_kind, source_image, env_applied_at
`

type CreateApplicationParams struct {
	ID                    string
	EnvironmentID         string
	Name                  string
	SourceKind            string
	SourceRepo            string
	SourceBranch          string
	SourceDeployKeyID     pgtype.Text
	BuildKind             string
	BuildDockerfilePath   string
	BuildContext          string
	RuntimeServerID       string
	RuntimePort           int32
	RuntimeReplicas       int32
	RouteDomain           string
	RouteHttps            bool
	RoutePathPrefix       string
	HealthPath            string
	HealthIntervalSeconds int32
	HealthTimeoutSeconds  int32
	HealthRetries         int32
	WebhookID             string
	WebhookSecretCt       []byte
	WebhookSecretNonce    []byte
	PreviewEnabled        bool
	PreviewBaseDomain     string
	PreviewTtlHours       int32
	CpuLimit              pgtype.Float4
	MemoryLimitMb         pgtype.Int4
	Volumes               []byte
	Ports                 []byte
	HealthKind            string
	SourceImage           string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.SourceKind,
		arg.SourceRepo,
		arg.SourceBranch,
		arg.SourceDeployKeyID,
		arg.BuildKind,
		arg.BuildDockerfilePath,
		arg.BuildContext,
		arg.RuntimeServerID,
		arg.RuntimePort,
		arg.RuntimeReplicas,
		arg.RouteDomain,
		arg.RouteHttps,
		arg.RoutePathPrefix,
		arg.HealthPath,
		arg.HealthIntervalSeconds,
		arg.HealthTimeoutSeconds,
		arg.HealthRetries,
		arg.WebhookID,
		arg.WebhookSecretCt,
		arg.WebhookSecretNonce,
		arg.PreviewEnabled,
		arg.PreviewBaseDomain,
		arg.PreviewTtlHours,
		arg.CpuLimit,
		arg.MemoryLimitMb,
		arg.Volumes,
		arg.Ports,
		arg.HealthKind,
		arg.SourceImage,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PreviewEnabled,
		&i.PreviewBaseDomain,
		&i.PreviewTtlHours,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Volumes,
		&i.Ports,
		&i.HealthKind,
		&i.SourceImage,
		&i.EnvAppliedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at, status, status_detail, observed_revision_id, status_observed_at, preview_enabled, preview_base_domain, preview_ttl_hours, cpu_limit, memory_limit_mb, volumes, ports, health_kind, source_image, env_applied_at FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PreviewEnabled,
		&i.PreviewBaseDomain,
		&i.PreviewTtlHours,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Volumes,
		&i.Ports,
		&i.HealthKind,
		&i.SourceImage,
		&i.EnvAppliedAt,
	)
	return i, err
}

const getApplicationByWebhookID = `-- name: GetApplicationByWebhookID :one
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at, status, status_detail, observed_revision_id, status_observed_at, preview_enabled, preview_base_domain, preview_ttl_hours, cpu_limit, memory_limit_mb, volumes, ports, health_kind, source_image, env_applied_at FROM applications WHERE webhook_id = $1
`

func (q *Queries) GetApplicationByWebhookID(ctx context.Context, webhookID string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByWebhookID, webhookID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PreviewEnabled,
		&i.PreviewBaseDomain,
		&i.PreviewTtlHours,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Volumes,
		&i.Ports,
		&i.HealthKind,
		&i.SourceImage,
		&i.EnvAppliedAt,
	)
	return i, err
}

const listApplicationsByDeployKey = `-- name: ListApplicationsByDeployKey :many
SELECT id, name FROM applications WHERE source_deploy_key_id = $1 ORDER BY name, id
`

type ListApplicationsByDeployKeyRow struct {
	ID   string
	Name string
}

// ListApplicationsByDeployKey names the applications still referencing a
// deploy key, so a refused delete can say which (deploy-key-private-repos.md
// §3; control-plane-hardening.md §8).
func (q *Queries) ListApplicationsByDeployKey(ctx context.Context, sourceDeployKeyID pgtype.Text) ([]ListApplicationsByDeployKeyRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByDeployKey, sourceDeployKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByDeployKeyRow{}
	for rows.Next() {
		var i ListApplicationsByDeployKeyRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByEnvironment = `-- name: ListApplicationsByEnvironment :many
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at, status, status_detail, observed_revision_id, status_observed_at, preview_enabled, preview_base_domain, preview_ttl_hours, cpu_limit, memory_limit_mb, volumes, ports, health_kind, source_image, env_applied_at FROM applications WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByEnvironment(ctx context.Context, environmentID string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.SourceKind,
			&i.SourceRepo,
			&i.SourceBranch,
			&i.SourceDeployKeyID,
			&i.BuildKind,
			&i.BuildDockerfilePath,
			&i.BuildContext,
			&i.RuntimeServerID,
			&i.RuntimePort,
			&i.RuntimeReplicas,
			&i.RouteDomain,
			&i.RouteHttps,
			&i.RoutePathPrefix,
			&i.HealthPath,
			&i.HealthIntervalSeconds,
			&i.HealthTimeoutSeconds,
			&i.HealthRetries,
			&i.WebhookID,
			&i.WebhookSecretCt,
			&i.WebhookSecretNonce,
			&i.DesiredRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.StatusDetail,
			&i.ObservedRevisionID,
			&i.StatusObservedAt,
			&i.PreviewEnabled,
			&i.PreviewBaseDomain,
			&i.PreviewTtlHours,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.Volumes,
			&i.Ports,
			&i.HealthKind,
			&i.SourceImage,
			&i.EnvAppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByServer = `-- name: ListApplicationsByServer :many
SELECT id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at, status, status_detail, observed_revision_id, status_observed_at, preview_enabled, preview_base_domain, preview_ttl_hours, cpu_limit, memory_limit_mb, volumes, ports, health_kind, source_image, env_applied_at FROM applications WHERE runtime_server_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByServer(ctx context.Context, runtimeServerID string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByServer, runtimeServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.SourceKind,
			&i.SourceRepo,
			&i.SourceBranch,
			&i.SourceDeployKeyID,
			&i.BuildKind,
			&i.BuildDockerfilePath,
			&i.BuildContext,
			&i.RuntimeServerID,
			&i.RuntimePort,
			&i.RuntimeReplicas,
			&i.RouteDomain,
			&i.RouteHttps,
			&i.RoutePathPrefix,
			&i.HealthPath,
			&i.HealthIntervalSeconds,
			&i.HealthTimeoutSeconds,
			&i.HealthRetries,
			&i.WebhookID,
			&i.WebhookSecretCt,
			&i.WebhookSecretNonce,
			&i.DesiredRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.StatusDetail,
			&i.ObservedRevisionID,
			&i.StatusObservedAt,
			&i.PreviewEnabled,
			&i.PreviewBaseDomain,
			&i.PreviewTtlHours,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.Volumes,
			&i.Ports,
			&i.HealthKind,
			&i.SourceImage,
			&i.EnvAppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationDesiredRevision = `-- name: SetApplicationDesiredRevision :one
UPDATE applications
SET desired_revision_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at, status, status_detail, observed_revision_id, status_observed_at, preview_enabled, preview_base_domain, preview_ttl_hours, cpu_limit, memory_limit_mb, volumes, ports, health_kind, source_image, env_applied_at
`

type SetApplicationDesiredRevisionParams struct {
	ID                string
	DesiredRevisionID pgtype.Text
}

func (q *Queries) SetApplicationDesiredRevision(ctx context.Context, arg SetApplicationDesiredRevisionParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationDesiredRevision, arg.ID, arg.DesiredRevisionID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PreviewEnabled,
		&i.PreviewBaseDomain,
		&i.PreviewTtlHours,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Volumes,
		&i.Ports,
		&i.HealthKind,
		&i.SourceImage,
		&i.EnvAppliedAt,
	)
	return i, err
}

const setApplicationObservedStatus = `-- name: SetApplicationObservedStatus :exec
UPDATE applications
SET status = $2, status_detail = $3, observed_revision_id = $4,
    status_observed_at = $5, updated_at = now()
WHERE id = $1
`

type SetApplicationObservedStatusParams struct {
	ID                 string
	Status             string
	StatusDetail       string
	ObservedRevisionID string
	StatusObservedAt   pgtype.Timestamptz
}

func (q *Queries) SetApplicationObservedStatus(ctx context.Context, arg SetApplicationObservedStatusParams) error {
	_, err := q.db.Exec(ctx, setApplicationObservedStatus,
		arg.ID,
		arg.Status,
		arg.StatusDetail,
		arg.ObservedRevisionID,
		arg.StatusObservedAt,
	)
	return err
}

const setApplicationStatus = `-- name: SetApplicationStatus :exec
UPDATE applications SET status = $2, status_detail = $3, updated_at = now() WHERE id = $1
`

type SetApplicationStatusParams struct {
	ID           string
	Status       string
	StatusDetail string
}

func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) error {
	_, err := q.db.Exec(ctx, setApplicationStatus, arg.ID, arg.Status, arg.StatusDetail)
	return err
}

const updateApplicationConfig = `-- name: UpdateApplicationConfig :one
UPDATE applications
SET name = $2,
    source_kind = $3, source_repo = $4, source_branch = $5, source_deploy_key_id = $6,
    build_kind = $7, build_dockerfile_path = $8, build_context = $9,
    runtime_port = $10, runtime_replicas = $11,
    route_domain = $12, route_https = $13, route_path_prefix = $14,
    health_path = $15, health_interval_seconds = $16, health_timeout_seconds = $17, health_retries = $18,
    preview_enabled = $19, preview_base_domain = $20, preview_ttl_hours = $21,
    cpu_limit = $22, memory_limit_mb = $23, volumes = $24,
    ports = $25, health_kind = $26, source_image = $27,
    updated_at = now()
WHERE id = $1
RETURNING id, environment_id, name, source_kind, source_repo, source_branch, source_deploy_key_id, build_kind, build_dockerfile_path, build_context, runtime_server_id, runtime_port, runtime_replicas, route_domain, route_https, route_path_prefix, health_path, health_interval_seconds, health_timeout_seconds, health_retries, webhook_id, webhook_secret_ct, webhook_secret_nonce, desired_revision_id, created_at, updated_at, status, status_detail, observed_revision_id, status_observed_at, preview_enabled, preview_base_domain, preview_ttl_hours, cpu_limit, memory_limit_mb, volumes, ports, health_kind, source_image, env_applied_at
`

type UpdateApplicationConfigParams struct {
	ID                    string
	Name                  string
	SourceKind            string
	SourceRepo            string
	SourceBranch          string
	SourceDeployKeyID     pgtype.Text
	BuildKind             string
	BuildDockerfilePath   string
	BuildContext          string
	RuntimePort           int32
	RuntimeReplicas       int32
	RouteDomain           string
	RouteHttps            bool
	RoutePathPrefix       string
	HealthPath            string
	HealthIntervalSeconds int32
	HealthTimeoutSeconds  int32
	HealthRetries         int32
	PreviewEnabled        bool
	PreviewBaseDomain     string
	PreviewTtlHours       int32
	CpuLimit              pgtype.Float4
	MemoryLimitMb         pgtype.Int4
	Volumes               []byte
	Ports                 []byte
	HealthKind            string
	SourceImage           string
}

func (q *Queries) UpdateApplicationConfig(ctx context.Context, arg UpdateApplicationConfigParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationConfig,
		arg.ID,
		arg.Name,
		arg.SourceKind,
		arg.SourceRepo,
		arg.SourceBranch,
		arg.SourceDeployKeyID,
		arg.BuildKind,
		arg.BuildDockerfilePath,
		arg.BuildContext,
		arg.RuntimePort,
		arg.RuntimeReplicas,
		arg.RouteDomain,
		arg.RouteHttps,
		arg.RoutePathPrefix,
		arg.HealthPath,
		arg.HealthIntervalSeconds,
		arg.HealthTimeoutSeconds,
		arg.HealthRetries,
		arg.PreviewEnabled,
		arg.PreviewBaseDomain,
		arg.PreviewTtlHours,
		arg.CpuLimit,
		arg.MemoryLimitMb,
		arg.Volumes,
		arg.Ports,
		arg.HealthKind,
		arg.SourceImage,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.SourceKind,
		&i.SourceRepo,
		&i.SourceBranch,
		&i.SourceDeployKeyID,
		&i.BuildKind,
		&i.BuildDockerfilePath,
		&i.BuildContext,
		&i.RuntimeServerID,
		&i.RuntimePort,
		&i.RuntimeReplicas,
		&i.RouteDomain,
		&i.RouteHttps,
		&i.RoutePathPrefix,
		&i.HealthPath,
		&i.HealthIntervalSeconds,
		&i.HealthTimeoutSeconds,
		&i.HealthRetries,
		&i.WebhookID,
		&i.WebhookSecretCt,
		&i.WebhookSecretNonce,
		&i.DesiredRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PreviewEnabled,
		&i.PreviewBaseDomain,
		&i.PreviewTtlHours,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.Volumes,
		&i.Ports,
		&i.HealthKind,
		&i.SourceImage,
		&i.EnvAppliedAt,
	)
	return i, err
}
