// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT id, at, action, outcome, actor_kind, actor_user_id, actor_token_id, actor_label, resource_kind, resource_id, resource_name, team_id, project_id, environment_id, detail, trace_id, client_ip FROM audit_events WHERE id = $1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id string) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Action,
		&i.Outcome,
		&i.ActorKind,
		&i.ActorUserID,
		&i.ActorTokenID,
		&i.ActorLabel,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourceName,
		&i.TeamID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Detail,
		&i.TraceID,
		&i.ClientIp,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one

INSERT INTO audit_events (
    id, action, outcome,
    actor_kind, actor_user_id, actor_token_id, actor_label,
    resource_kind, resource_id, resource_name,
    team_id, project_id, environment_id,
    detail, trace_id, client_ip
) VALUES (
    $1, $2, $3,
    $4, $5::text, $6::text, $7,
    $8, $9, $10,
    COALESCE(
        $11::text,
        (SELECT p.team_id FROM projects p WHERE p.id = $12::text),
        (SELECT p.team_id FROM projects p
           JOIN environments e ON e.project_id = p.id
          WHERE e.id = $13::text)
    ),
    COALESCE(
        $12::text,
        (SELECT e.project_id FROM environments e WHERE e.id = $13::text)
    ),
    $13::text,
    $14::jsonb, $15, $16
)
RETURNING id, at, action, outcome, actor_kind, actor_user_id, actor_token_id, actor_label, resource_kind, resource_id, resource_name, team_id, project_id, environment_id, detail, trace_id, client_ip
`

type InsertAuditEventParams struct {
	ID            string
	Action        string
	Outcome       string
	ActorKind     string
	ActorUserID   pgtype.Text
	ActorTokenID  pgtype.Text
	ActorLabel    string
	ResourceKind  string
	ResourceID    string
	ResourceName  string
	TeamID        pgtype.Text
	ProjectID     pgtype.Text
	EnvironmentID pgtype.Text
	Detail        []byte
	TraceID       string
	ClientIp      string
}

// Audit log (audit-log.md §2, §4, §7). One immutable row per sensitive action.
// There is no UPDATE here on purpose: the log is evidence, and evidence that
// can be edited is not evidence. The only mutation is the retention purge.
// InsertAuditEvent writes one row, resolving the ownership chain IN THE SAME
// STATEMENT from whichever link the caller happened to know (§4). A handler
// that knows only an environment gets project_id and team_id filled in; one
// that knows only a project gets team_id; one that knows the team passes it
// and nothing is looked up.
//
// Resolving here rather than in Go is what makes the snapshot atomic with the
// write: there is no window in which a project could move to another team
// between the lookup and the insert, and a delete handler that passes team_id
// explicitly still records the scope after the project row is gone.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ID,
		arg.Action,
		arg.Outcome,
		arg.ActorKind,
		arg.ActorUserID,
		arg.ActorTokenID,
		arg.ActorLabel,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ResourceName,
		arg.TeamID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Detail,
		arg.TraceID,
		arg.ClientIp,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Action,
		&i.Outcome,
		&i.ActorKind,
		&i.ActorUserID,
		&i.ActorTokenID,
		&i.ActorLabel,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourceName,
		&i.TeamID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Detail,
		&i.TraceID,
		&i.ClientIp,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
WITH visible AS NOT MATERIALIZED (
    SELECT e.id, e.at, e.action, e.outcome, e.actor_kind, e.actor_user_id, e.actor_token_id, e.actor_label, e.resource_kind, e.resource_id, e.resource_name, e.team_id, e.project_id, e.environment_id, e.detail, e.trace_id, e.client_ip FROM audit_events e
    WHERE $11::boolean
       OR (e.team_id IS NOT NULL AND e.team_id = ANY($12::text[]))
       OR (e.team_id IS NULL AND $13::boolean)
       OR (e.actor_user_id IS NOT NULL AND e.actor_user_id = $14::text)
)
SELECT v.id, v.at, v.action, v.outcome,
       v.actor_kind, v.actor_user_id, v.actor_token_id, v.actor_label,
       v.resource_kind, v.resource_id, v.resource_name,
       v.team_id, v.project_id, v.environment_id,
       v.detail, v.trace_id, v.client_ip
FROM visible v
WHERE ($1::text = '' OR v.team_id = $1::text)
  AND ($2::text = '' OR v.project_id = $2::text)
  AND ($3::text = '' OR v.resource_id = $3::text)
  -- An action filter matches the exact verb or its whole family: ` + "`" + `deploy` + "`" + `
  -- selects deploy.started, deploy.rolled_back and every later sibling, so a
  -- filter UI needs three coarse choices rather than the full vocabulary.
  AND ($4::text = '' OR v.action = $4::text OR v.action LIKE $4::text || '.%')
  -- An actor is named by id or by the label snapshot, so "priya@acme.com"
  -- works without first resolving it to a usr_… id.
  AND ($5::text = '' OR v.actor_user_id = $5::text OR v.actor_label = $5::text)
  AND ($6::text = '' OR v.outcome = $6::text)
  AND (NOT $7::boolean OR v.at >= $8::timestamptz)
  AND ($9::text = '' OR (v.at, v.id) < (
        SELECT c.at, c.id FROM visible c WHERE c.id = $9::text
  ))
ORDER BY v.at DESC, v.id DESC
LIMIT $10
`

type ListAuditEventsParams struct {
	TeamID     string
	ProjectID  string
	ResourceID string
	Action     string
	Actor      string
	Outcome    string
	SinceSet   bool
	Since      pgtype.Timestamptz
	Before     string
	RowLimit   int32
	AllScopes  bool
	TeamIds    []string
	PanelScope bool
	ViewerID   string
}

type ListAuditEventsRow struct {
	ID            string
	At            pgtype.Timestamptz
	Action        string
	Outcome       string
	ActorKind     string
	ActorUserID   pgtype.Text
	ActorTokenID  pgtype.Text
	ActorLabel    string
	ResourceKind  string
	ResourceID    string
	ResourceName  string
	TeamID        pgtype.Text
	ProjectID     pgtype.Text
	EnvironmentID pgtype.Text
	Detail        []byte
	TraceID       string
	ClientIp      string
}

// ListAuditEvents pages the log newest-first, with the caller's visibility
// applied BEFORE any operator-supplied filter (§5). The `visible` CTE is the
// whole tenancy story:
//
//   - a panel owner sees everything (@all_scopes) — the same superadmin bypass
//     teams.RoleInTeam already grants;
//   - anyone sees the rows of the teams they belong to (@team_ids);
//   - a panel admin additionally sees PANEL-scoped rows — a server, a user, the
//     mail/DNS/TLS settings — which belong to no team (@panel_scope);
//   - everyone sees their OWN actions, whatever scope they landed in, so
//     "what did I do?" never depends on still being in the team.
//
// The cursor subquery reads from `visible`, not from the base table, so a
// cursor naming an event the caller may not see yields an empty page instead of
// restarting at the newest row — the same posture the inbox takes.
//
// NOT MATERIALIZED is load-bearing, not decoration. `visible` is referenced
// twice (the page and the cursor lookup), and from PostgreSQL 12 a
// multiply-referenced CTE is materialized by default: the caller's ENTIRE
// visible set would be built and spooled, then top-N sorted, before LIMIT — a
// sequential scan and a temp-file sort on every page, growing with the whole
// retention window, and cheap for any authenticated caller to loop. Inlining it
// lets the planner push the predicate and the ordering into
// idx_audit_events_at, which is what §2's index rationale promises. Measured on
// 200k rows: CTE Scan + Sort 140 ms, Index Only Scan 0.14 ms.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.TeamID,
		arg.ProjectID,
		arg.ResourceID,
		arg.Action,
		arg.Actor,
		arg.Outcome,
		arg.SinceSet,
		arg.Since,
		arg.Before,
		arg.RowLimit,
		arg.AllScopes,
		arg.TeamIds,
		arg.PanelScope,
		arg.ViewerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Action,
			&i.Outcome,
			&i.ActorKind,
			&i.ActorUserID,
			&i.ActorTokenID,
			&i.ActorLabel,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourceName,
			&i.TeamID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Detail,
			&i.TraceID,
			&i.ClientIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditEvents = `-- name: PurgeAuditEvents :one
WITH doomed AS (
    SELECT e.id FROM audit_events e WHERE e.at < $1 ORDER BY e.at LIMIT $2
), deleted AS (
    DELETE FROM audit_events a WHERE a.id IN (SELECT d.id FROM doomed d) RETURNING 1 AS one
)
SELECT count(*)::bigint FROM deleted
`

type PurgeAuditEventsParams struct {
	Cutoff   pgtype.Timestamptz
	RowLimit int32
}

// PurgeAuditEvents deletes one BOUNDED batch of rows older than the cutoff and
// reports how many it removed, so the retention loop can drain a long backlog
// in steps instead of taking one lock over the whole table (§8). The oldest
// rows go first, which is also the order the index is already in.
func (q *Queries) PurgeAuditEvents(ctx context.Context, arg PurgeAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, purgeAuditEvents, arg.Cutoff, arg.RowLimit)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
