// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_revisions.sql

package db

import (
	"context"
)

const createDatabaseRevision = `-- name: CreateDatabaseRevision :one
INSERT INTO database_revisions (id, database_id, config_snapshot)
VALUES ($1, $2, $3)
RETURNING id, database_id, config_snapshot, created_at
`

type CreateDatabaseRevisionParams struct {
	ID             string
	DatabaseID     string
	ConfigSnapshot []byte
}

func (q *Queries) CreateDatabaseRevision(ctx context.Context, arg CreateDatabaseRevisionParams) (DatabaseRevision, error) {
	row := q.db.QueryRow(ctx, createDatabaseRevision, arg.ID, arg.DatabaseID, arg.ConfigSnapshot)
	var i DatabaseRevision
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.ConfigSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseRevision = `-- name: GetDatabaseRevision :one
SELECT id, database_id, config_snapshot, created_at FROM database_revisions WHERE id = $1
`

func (q *Queries) GetDatabaseRevision(ctx context.Context, id string) (DatabaseRevision, error) {
	row := q.db.QueryRow(ctx, getDatabaseRevision, id)
	var i DatabaseRevision
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.ConfigSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDatabaseRevision = `-- name: GetLatestDatabaseRevision :one
SELECT id, database_id, config_snapshot, created_at FROM database_revisions
WHERE database_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestDatabaseRevision(ctx context.Context, databaseID string) (DatabaseRevision, error) {
	row := q.db.QueryRow(ctx, getLatestDatabaseRevision, databaseID)
	var i DatabaseRevision
	err := row.Scan(
		&i.ID,
		&i.DatabaseID,
		&i.ConfigSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listDatabaseRevisions = `-- name: ListDatabaseRevisions :many
SELECT id, database_id, config_snapshot, created_at FROM database_revisions
WHERE database_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDatabaseRevisions(ctx context.Context, databaseID string) ([]DatabaseRevision, error) {
	rows, err := q.db.Query(ctx, listDatabaseRevisions, databaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DatabaseRevision{}
	for rows.Next() {
		var i DatabaseRevision
		if err := rows.Scan(
			&i.ID,
			&i.DatabaseID,
			&i.ConfigSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
