// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: databases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (
    id, environment_id, name, engine, version,
    server_id, cpu_limit, memory_limit_mb,
    volume_name, data_path, expose_port, network,
    root_user, root_password_ct, root_password_nonce, require_password,
    status, status_detail, initial_database
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19
)
RETURNING id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database
`

type CreateDatabaseParams struct {
	ID                string
	EnvironmentID     string
	Name              string
	Engine            string
	Version           string
	ServerID          string
	CpuLimit          pgtype.Float4
	MemoryLimitMb     pgtype.Int4
	VolumeName        string
	DataPath          string
	ExposePort        pgtype.Int4
	Network           string
	RootUser          string
	RootPasswordCt    []byte
	RootPasswordNonce []byte
	RequirePassword   bool
	Status            string
	StatusDetail      string
	InitialDatabase   string
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRow(ctx, createDatabase,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Engine,
		arg.Version,
		arg.ServerID,
		arg.CpuLimit,
		arg.MemoryLimitMb,
		arg.VolumeName,
		arg.DataPath,
		arg.ExposePort,
		arg.Network,
		arg.RootUser,
		arg.RootPasswordCt,
		arg.RootPasswordNonce,
		arg.RequirePassword,
		arg.Status,
		arg.StatusDetail,
		arg.InitialDatabase,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.ServerID,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.VolumeName,
		&i.DataPath,
		&i.ExposePort,
		&i.Network,
		&i.RootUser,
		&i.RootPasswordCt,
		&i.RootPasswordNonce,
		&i.RequirePassword,
		&i.DesiredRevisionID,
		&i.DesiredState,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PendingDelete,
		&i.DeleteVolume,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialDatabase,
	)
	return i, err
}

const deleteDatabase = `-- name: DeleteDatabase :exec
DELETE FROM databases WHERE id = $1
`

func (q *Queries) DeleteDatabase(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDatabase, id)
	return err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database FROM databases WHERE id = $1
`

func (q *Queries) GetDatabase(ctx context.Context, id string) (Database, error) {
	row := q.db.QueryRow(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.ServerID,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.VolumeName,
		&i.DataPath,
		&i.ExposePort,
		&i.Network,
		&i.RootUser,
		&i.RootPasswordCt,
		&i.RootPasswordNonce,
		&i.RequirePassword,
		&i.DesiredRevisionID,
		&i.DesiredState,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PendingDelete,
		&i.DeleteVolume,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialDatabase,
	)
	return i, err
}

const listDatabasesByEnvironment = `-- name: ListDatabasesByEnvironment :many
SELECT id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database FROM databases WHERE environment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDatabasesByEnvironment(ctx context.Context, environmentID string) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.ServerID,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.VolumeName,
			&i.DataPath,
			&i.ExposePort,
			&i.Network,
			&i.RootUser,
			&i.RootPasswordCt,
			&i.RootPasswordNonce,
			&i.RequirePassword,
			&i.DesiredRevisionID,
			&i.DesiredState,
			&i.Status,
			&i.StatusDetail,
			&i.ObservedRevisionID,
			&i.StatusObservedAt,
			&i.PendingDelete,
			&i.DeleteVolume,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InitialDatabase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabasesByServer = `-- name: ListDatabasesByServer :many
SELECT id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database FROM databases WHERE server_id = $1 AND pending_delete = false ORDER BY created_at DESC
`

func (q *Queries) ListDatabasesByServer(ctx context.Context, serverID string) ([]Database, error) {
	rows, err := q.db.Query(ctx, listDatabasesByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.ServerID,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.VolumeName,
			&i.DataPath,
			&i.ExposePort,
			&i.Network,
			&i.RootUser,
			&i.RootPasswordCt,
			&i.RootPasswordNonce,
			&i.RequirePassword,
			&i.DesiredRevisionID,
			&i.DesiredState,
			&i.Status,
			&i.StatusDetail,
			&i.ObservedRevisionID,
			&i.StatusObservedAt,
			&i.PendingDelete,
			&i.DeleteVolume,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InitialDatabase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeleteDatabases = `-- name: ListPendingDeleteDatabases :many
SELECT id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database FROM databases WHERE pending_delete = true
`

func (q *Queries) ListPendingDeleteDatabases(ctx context.Context) ([]Database, error) {
	rows, err := q.db.Query(ctx, listPendingDeleteDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Database{}
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.ServerID,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.VolumeName,
			&i.DataPath,
			&i.ExposePort,
			&i.Network,
			&i.RootUser,
			&i.RootPasswordCt,
			&i.RootPasswordNonce,
			&i.RequirePassword,
			&i.DesiredRevisionID,
			&i.DesiredState,
			&i.Status,
			&i.StatusDetail,
			&i.ObservedRevisionID,
			&i.StatusObservedAt,
			&i.PendingDelete,
			&i.DeleteVolume,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InitialDatabase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDatabaseDesiredRevision = `-- name: SetDatabaseDesiredRevision :one
UPDATE databases
SET desired_revision_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database
`

type SetDatabaseDesiredRevisionParams struct {
	ID                string
	DesiredRevisionID pgtype.Text
}

func (q *Queries) SetDatabaseDesiredRevision(ctx context.Context, arg SetDatabaseDesiredRevisionParams) (Database, error) {
	row := q.db.QueryRow(ctx, setDatabaseDesiredRevision, arg.ID, arg.DesiredRevisionID)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.ServerID,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.VolumeName,
		&i.DataPath,
		&i.ExposePort,
		&i.Network,
		&i.RootUser,
		&i.RootPasswordCt,
		&i.RootPasswordNonce,
		&i.RequirePassword,
		&i.DesiredRevisionID,
		&i.DesiredState,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PendingDelete,
		&i.DeleteVolume,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialDatabase,
	)
	return i, err
}

const setDatabaseDesiredState = `-- name: SetDatabaseDesiredState :one
UPDATE databases SET desired_state = $2, updated_at = now() WHERE id = $1 RETURNING id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database
`

type SetDatabaseDesiredStateParams struct {
	ID           string
	DesiredState string
}

func (q *Queries) SetDatabaseDesiredState(ctx context.Context, arg SetDatabaseDesiredStateParams) (Database, error) {
	row := q.db.QueryRow(ctx, setDatabaseDesiredState, arg.ID, arg.DesiredState)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.ServerID,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.VolumeName,
		&i.DataPath,
		&i.ExposePort,
		&i.Network,
		&i.RootUser,
		&i.RootPasswordCt,
		&i.RootPasswordNonce,
		&i.RequirePassword,
		&i.DesiredRevisionID,
		&i.DesiredState,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PendingDelete,
		&i.DeleteVolume,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialDatabase,
	)
	return i, err
}

const setDatabaseObservedStatus = `-- name: SetDatabaseObservedStatus :exec
UPDATE databases
SET status = $2, status_detail = $3, observed_revision_id = $4,
    status_observed_at = $5, updated_at = now()
WHERE id = $1
`

type SetDatabaseObservedStatusParams struct {
	ID                 string
	Status             string
	StatusDetail       string
	ObservedRevisionID string
	StatusObservedAt   pgtype.Timestamptz
}

func (q *Queries) SetDatabaseObservedStatus(ctx context.Context, arg SetDatabaseObservedStatusParams) error {
	_, err := q.db.Exec(ctx, setDatabaseObservedStatus,
		arg.ID,
		arg.Status,
		arg.StatusDetail,
		arg.ObservedRevisionID,
		arg.StatusObservedAt,
	)
	return err
}

const setDatabasePendingDelete = `-- name: SetDatabasePendingDelete :exec
UPDATE databases SET pending_delete = true, delete_volume = $2, updated_at = now() WHERE id = $1
`

type SetDatabasePendingDeleteParams struct {
	ID           string
	DeleteVolume bool
}

func (q *Queries) SetDatabasePendingDelete(ctx context.Context, arg SetDatabasePendingDeleteParams) error {
	_, err := q.db.Exec(ctx, setDatabasePendingDelete, arg.ID, arg.DeleteVolume)
	return err
}

const setDatabaseStatus = `-- name: SetDatabaseStatus :exec
UPDATE databases SET status = $2, status_detail = $3, updated_at = now() WHERE id = $1
`

type SetDatabaseStatusParams struct {
	ID           string
	Status       string
	StatusDetail string
}

func (q *Queries) SetDatabaseStatus(ctx context.Context, arg SetDatabaseStatusParams) error {
	_, err := q.db.Exec(ctx, setDatabaseStatus, arg.ID, arg.Status, arg.StatusDetail)
	return err
}

const updateDatabaseConfig = `-- name: UpdateDatabaseConfig :one
UPDATE databases
SET name = $2,
    version = $3,
    cpu_limit = $4,
    memory_limit_mb = $5,
    expose_port = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, environment_id, name, engine, version, server_id, cpu_limit, memory_limit_mb, volume_name, data_path, expose_port, network, root_user, root_password_ct, root_password_nonce, require_password, desired_revision_id, desired_state, status, status_detail, observed_revision_id, status_observed_at, pending_delete, delete_volume, created_at, updated_at, initial_database
`

type UpdateDatabaseConfigParams struct {
	ID            string
	Name          string
	Version       string
	CpuLimit      pgtype.Float4
	MemoryLimitMb pgtype.Int4
	ExposePort    pgtype.Int4
}

func (q *Queries) UpdateDatabaseConfig(ctx context.Context, arg UpdateDatabaseConfigParams) (Database, error) {
	row := q.db.QueryRow(ctx, updateDatabaseConfig,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CpuLimit,
		arg.MemoryLimitMb,
		arg.ExposePort,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.ServerID,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.VolumeName,
		&i.DataPath,
		&i.ExposePort,
		&i.Network,
		&i.RootUser,
		&i.RootPasswordCt,
		&i.RootPasswordNonce,
		&i.RequirePassword,
		&i.DesiredRevisionID,
		&i.DesiredState,
		&i.Status,
		&i.StatusDetail,
		&i.ObservedRevisionID,
		&i.StatusObservedAt,
		&i.PendingDelete,
		&i.DeleteVolume,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialDatabase,
	)
	return i, err
}

const updateDatabasePassword = `-- name: UpdateDatabasePassword :exec
UPDATE databases
SET root_password_ct = $2, root_password_nonce = $3, updated_at = now()
WHERE id = $1
`

type UpdateDatabasePasswordParams struct {
	ID                string
	RootPasswordCt    []byte
	RootPasswordNonce []byte
}

func (q *Queries) UpdateDatabasePassword(ctx context.Context, arg UpdateDatabasePasswordParams) error {
	_, err := q.db.Exec(ctx, updateDatabasePassword, arg.ID, arg.RootPasswordCt, arg.RootPasswordNonce)
	return err
}
