// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deploy_protection.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBreakGlassGrants = `-- name: CountActiveBreakGlassGrants :one
SELECT count(*) FROM break_glass_grants
WHERE environment_id = $1 AND expires_at > $2
`

type CountActiveBreakGlassGrantsParams struct {
	EnvironmentID string
	Now           pgtype.Timestamptz
}

// CountActiveBreakGlassGrants asks the one question the freeze gate needs: is
// an unexpired grant open right now. @now is the plane's injected clock, not
// the database's, so the gate and its tests read the same time source.
func (q *Queries) CountActiveBreakGlassGrants(ctx context.Context, arg CountActiveBreakGlassGrantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBreakGlassGrants, arg.EnvironmentID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQualifiedApprovers = `-- name: CountQualifiedApprovers :one
SELECT count(*) FROM projects p
JOIN team_members m ON m.team_id = p.team_id
WHERE p.id = $1
  AND m.user_id <> $2
  AND (CASE m.role WHEN 'owner' THEN 3 WHEN 'admin' THEN 2 WHEN 'member' THEN 1 ELSE 0 END)
      >= (CASE $3::text WHEN 'owner' THEN 3 WHEN 'admin' THEN 2 WHEN 'member' THEN 1 ELSE 0 END)
`

type CountQualifiedApproversParams struct {
	ProjectID     string
	ExcludeUserID string
	MinRole       string
}

// CountQualifiedApprovers counts the members of the project's team who rank at
// or above @min_role, EXCLUDING @exclude_user_id. Zero means the excluded user
// is the only qualifying approver, which is what lifts the no-self-approval
// rule for a solo operator (§5). Panel owners are deliberately not counted:
// their implicit rank is an authorization escape hatch, not a second person.
func (q *Queries) CountQualifiedApprovers(ctx context.Context, arg CountQualifiedApproversParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQualifiedApprovers, arg.ProjectID, arg.ExcludeUserID, arg.MinRole)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBreakGlassGrant = `-- name: CreateBreakGlassGrant :one

INSERT INTO break_glass_grants (id, environment_id, opened_by, reason, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, environment_id, opened_by, reason, created_at, expires_at
`

type CreateBreakGlassGrantParams struct {
	ID            string
	EnvironmentID string
	OpenedBy      pgtype.Text
	Reason        string
	ExpiresAt     pgtype.Timestamptz
}

// ─── Break glass ────────────────────────────────────────────────────────────
func (q *Queries) CreateBreakGlassGrant(ctx context.Context, arg CreateBreakGlassGrantParams) (BreakGlassGrant, error) {
	row := q.db.QueryRow(ctx, createBreakGlassGrant,
		arg.ID,
		arg.EnvironmentID,
		arg.OpenedBy,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i BreakGlassGrant
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.OpenedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createDeployApproval = `-- name: CreateDeployApproval :one

INSERT INTO deploy_approvals (
    deployment_id, environment_id, requested_by, required_role, state
) VALUES ($1, $2, $3, $4, 'pending')
RETURNING deployment_id, environment_id, requested_by, required_role, state, decided_by, decided_at, reason, created_at
`

type CreateDeployApprovalParams struct {
	DeploymentID  string
	EnvironmentID string
	RequestedBy   pgtype.Text
	RequiredRole  string
}

// ─── Approvals ──────────────────────────────────────────────────────────────
func (q *Queries) CreateDeployApproval(ctx context.Context, arg CreateDeployApprovalParams) (DeployApproval, error) {
	row := q.db.QueryRow(ctx, createDeployApproval,
		arg.DeploymentID,
		arg.EnvironmentID,
		arg.RequestedBy,
		arg.RequiredRole,
	)
	var i DeployApproval
	err := row.Scan(
		&i.DeploymentID,
		&i.EnvironmentID,
		&i.RequestedBy,
		&i.RequiredRole,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const decideDeployApproval = `-- name: DecideDeployApproval :one
UPDATE deploy_approvals
SET state = $1, decided_by = $2, decided_at = now(), reason = $3
WHERE deployment_id = $4 AND state = 'pending'
RETURNING deployment_id, environment_id, requested_by, required_role, state, decided_by, decided_at, reason, created_at
`

type DecideDeployApprovalParams struct {
	State        string
	DecidedBy    pgtype.Text
	Reason       string
	DeploymentID string
}

// DecideDeployApproval is once-only by construction: the WHERE clause matches
// nothing on an already-decided row, so a second approve (or an approve racing
// a reject) writes nothing and the caller answers 409 (§5). No read-then-write,
// so no window between the check and the update.
func (q *Queries) DecideDeployApproval(ctx context.Context, arg DecideDeployApprovalParams) (DeployApproval, error) {
	row := q.db.QueryRow(ctx, decideDeployApproval,
		arg.State,
		arg.DecidedBy,
		arg.Reason,
		arg.DeploymentID,
	)
	var i DeployApproval
	err := row.Scan(
		&i.DeploymentID,
		&i.EnvironmentID,
		&i.RequestedBy,
		&i.RequiredRole,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFreezeWindows = `-- name: DeleteFreezeWindows :exec
DELETE FROM freeze_windows WHERE environment_id = $1
`

func (q *Queries) DeleteFreezeWindows(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, deleteFreezeWindows, environmentID)
	return err
}

const getDeployApproval = `-- name: GetDeployApproval :one
SELECT a.deployment_id, a.environment_id, a.requested_by, a.required_role, a.state, a.decided_by, a.decided_at, a.reason, a.created_at, COALESCE(rq.email, '') AS requested_by_email,
             COALESCE(dc.email, '') AS decided_by_email
FROM deploy_approvals a
LEFT JOIN users rq ON rq.id = a.requested_by
LEFT JOIN users dc ON dc.id = a.decided_by
WHERE a.deployment_id = $1
`

type GetDeployApprovalRow struct {
	DeploymentID     string
	EnvironmentID    string
	RequestedBy      pgtype.Text
	RequiredRole     string
	State            string
	DecidedBy        pgtype.Text
	DecidedAt        pgtype.Timestamptz
	Reason           string
	CreatedAt        pgtype.Timestamptz
	RequestedByEmail string
	DecidedByEmail   string
}

// GetDeployApproval joins the two user rows the pending card renders, so the
// screen needs no second lookup to say "requested by alex@acme.com". A user
// deleted since (ON DELETE SET NULL) leaves both id and email empty, which the
// card reads as "pushed via webhook or by a since-removed account".
func (q *Queries) GetDeployApproval(ctx context.Context, deploymentID string) (GetDeployApprovalRow, error) {
	row := q.db.QueryRow(ctx, getDeployApproval, deploymentID)
	var i GetDeployApprovalRow
	err := row.Scan(
		&i.DeploymentID,
		&i.EnvironmentID,
		&i.RequestedBy,
		&i.RequiredRole,
		&i.State,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.CreatedAt,
		&i.RequestedByEmail,
		&i.DecidedByEmail,
	)
	return i, err
}

const getEnvironmentProtection = `-- name: GetEnvironmentProtection :one

SELECT environment_id, require_approval, min_approver_role, freeze_enabled, created_at, updated_at FROM environment_protection WHERE environment_id = $1
`

// Deploy protection (deploy-protection.md §2, §4, §5): the protection document
// per environment, its freeze windows, the one gate decision per deployment,
// and the bounded break-glass grant that suspends a freeze.
//
// Nothing here evaluates a window: minute-of-week arithmetic happens in
// core/protection against an injected clock, because a window is wall clock in
// its OWN zone and the database's now() knows nothing about that zone.
func (q *Queries) GetEnvironmentProtection(ctx context.Context, environmentID string) (EnvironmentProtection, error) {
	row := q.db.QueryRow(ctx, getEnvironmentProtection, environmentID)
	var i EnvironmentProtection
	err := row.Scan(
		&i.EnvironmentID,
		&i.RequireApproval,
		&i.MinApproverRole,
		&i.FreezeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFreezeWindows = `-- name: InsertFreezeWindows :exec
INSERT INTO freeze_windows (
    id, environment_id, start_dow, start_minute, end_dow, end_minute, timezone
)
SELECT unnest($1::text[]),
       $2::text,
       unnest($3::smallint[]),
       unnest($4::int[]),
       unnest($5::smallint[]),
       unnest($6::int[]),
       unnest($7::text[])
`

type InsertFreezeWindowsParams struct {
	Ids           []string
	EnvironmentID string
	StartDows     []int16
	StartMinutes  []int32
	EndDows       []int16
	EndMinutes    []int32
	Timezones     []string
}

// InsertFreezeWindows writes a whole window list in one statement — the
// replace half of the wholesale PUT. Positional unnests expand in lockstep
// (PostgreSQL 10+), so column i of every array belongs to window i.
func (q *Queries) InsertFreezeWindows(ctx context.Context, arg InsertFreezeWindowsParams) error {
	_, err := q.db.Exec(ctx, insertFreezeWindows,
		arg.Ids,
		arg.EnvironmentID,
		arg.StartDows,
		arg.StartMinutes,
		arg.EndDows,
		arg.EndMinutes,
		arg.Timezones,
	)
	return err
}

const listBreakGlassGrants = `-- name: ListBreakGlassGrants :many
SELECT g.id, g.environment_id, g.opened_by, g.reason, g.created_at, g.expires_at, COALESCE(u.email, '') AS opened_by_email
FROM break_glass_grants g
LEFT JOIN users u ON u.id = g.opened_by
WHERE g.environment_id = $1
ORDER BY g.created_at DESC
LIMIT $2
`

type ListBreakGlassGrantsParams struct {
	EnvironmentID string
	Limit         int32
}

type ListBreakGlassGrantsRow struct {
	ID            string
	EnvironmentID string
	OpenedBy      pgtype.Text
	Reason        string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	OpenedByEmail string
}

// ListBreakGlassGrants shows who broke glass, why, and when it lapses —
// newest first, bounded, because the screen shows "active + recent" and a
// year of incidents is not a screen (§6).
func (q *Queries) ListBreakGlassGrants(ctx context.Context, arg ListBreakGlassGrantsParams) ([]ListBreakGlassGrantsRow, error) {
	rows, err := q.db.Query(ctx, listBreakGlassGrants, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBreakGlassGrantsRow{}
	for rows.Next() {
		var i ListBreakGlassGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.OpenedBy,
			&i.Reason,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.OpenedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployApprovalsByApplication = `-- name: ListDeployApprovalsByApplication :many
SELECT a.deployment_id, a.environment_id, a.requested_by, a.required_role, a.state, a.decided_by, a.decided_at, a.reason, a.created_at, COALESCE(rq.email, '') AS requested_by_email,
             COALESCE(dc.email, '') AS decided_by_email
FROM deploy_approvals a
JOIN deployments d ON d.id = a.deployment_id
LEFT JOIN users rq ON rq.id = a.requested_by
LEFT JOIN users dc ON dc.id = a.decided_by
WHERE d.application_id = $1
  AND a.deployment_id = ANY($2::text[])
`

type ListDeployApprovalsByApplicationParams struct {
	ApplicationID string
	DeploymentIds []string
}

type ListDeployApprovalsByApplicationRow struct {
	DeploymentID     string
	EnvironmentID    string
	RequestedBy      pgtype.Text
	RequiredRole     string
	State            string
	DecidedBy        pgtype.Text
	DecidedAt        pgtype.Timestamptz
	Reason           string
	CreatedAt        pgtype.Timestamptz
	RequestedByEmail string
	DecidedByEmail   string
}

// ListDeployApprovalsByApplication answers "which of THESE deployments has a
// gate decision" for one page of a Deployments tab in one round trip, rather
// than one lookup per row.
//
// The deployment ids are the page the caller is decorating, not the
// application's whole history: an application deploys forever, and a read model
// that grows with it is a read model that eventually stops answering. The
// application_id join stays as the tenancy assertion — an id from another
// application matches nothing.
func (q *Queries) ListDeployApprovalsByApplication(ctx context.Context, arg ListDeployApprovalsByApplicationParams) ([]ListDeployApprovalsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listDeployApprovalsByApplication, arg.ApplicationID, arg.DeploymentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployApprovalsByApplicationRow{}
	for rows.Next() {
		var i ListDeployApprovalsByApplicationRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.EnvironmentID,
			&i.RequestedBy,
			&i.RequiredRole,
			&i.State,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.CreatedAt,
			&i.RequestedByEmail,
			&i.DecidedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployApprovalsByEnvironment = `-- name: ListDeployApprovalsByEnvironment :many
SELECT a.deployment_id, a.environment_id, a.requested_by, a.required_role, a.state, a.decided_by, a.decided_at, a.reason, a.created_at, COALESCE(rq.email, '') AS requested_by_email,
             COALESCE(dc.email, '') AS decided_by_email
FROM deploy_approvals a
LEFT JOIN users rq ON rq.id = a.requested_by
LEFT JOIN users dc ON dc.id = a.decided_by
WHERE a.environment_id = $1
  AND ($2::text = '' OR a.state = $2::text)
ORDER BY a.created_at DESC
LIMIT $3::int
`

type ListDeployApprovalsByEnvironmentParams struct {
	EnvironmentID string
	State         string
	RowLimit      int32
}

type ListDeployApprovalsByEnvironmentRow struct {
	DeploymentID     string
	EnvironmentID    string
	RequestedBy      pgtype.Text
	RequiredRole     string
	State            string
	DecidedBy        pgtype.Text
	DecidedAt        pgtype.Timestamptz
	Reason           string
	CreatedAt        pgtype.Timestamptz
	RequestedByEmail string
	DecidedByEmail   string
}

// ListDeployApprovalsByEnvironment is the environment's approval queue. An
// empty @state means every state, so one query serves both the pending card and
// the decision history (§6).
//
// BOUNDED, like every other listing beside it: @state = ” asks for the whole
// decision history of a long-lived environment, which is not a screen and is
// not a response. Newest first, so the bound drops the oldest.
func (q *Queries) ListDeployApprovalsByEnvironment(ctx context.Context, arg ListDeployApprovalsByEnvironmentParams) ([]ListDeployApprovalsByEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listDeployApprovalsByEnvironment, arg.EnvironmentID, arg.State, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployApprovalsByEnvironmentRow{}
	for rows.Next() {
		var i ListDeployApprovalsByEnvironmentRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.EnvironmentID,
			&i.RequestedBy,
			&i.RequiredRole,
			&i.State,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.CreatedAt,
			&i.RequestedByEmail,
			&i.DecidedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreezeWindows = `-- name: ListFreezeWindows :many
SELECT id, environment_id, start_dow, start_minute, end_dow, end_minute, timezone, created_at FROM freeze_windows
WHERE environment_id = $1
ORDER BY start_dow, start_minute, id
`

func (q *Queries) ListFreezeWindows(ctx context.Context, environmentID string) ([]FreezeWindow, error) {
	rows, err := q.db.Query(ctx, listFreezeWindows, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FreezeWindow{}
	for rows.Next() {
		var i FreezeWindow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.StartDow,
			&i.StartMinute,
			&i.EndDow,
			&i.EndMinute,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironmentProtection = `-- name: UpsertEnvironmentProtection :one
INSERT INTO environment_protection (
    environment_id, require_approval, min_approver_role, freeze_enabled
) VALUES ($1, $2, $3, $4)
ON CONFLICT (environment_id) DO UPDATE
SET require_approval  = EXCLUDED.require_approval,
    min_approver_role = EXCLUDED.min_approver_role,
    freeze_enabled    = EXCLUDED.freeze_enabled,
    updated_at        = now()
RETURNING environment_id, require_approval, min_approver_role, freeze_enabled, created_at, updated_at
`

type UpsertEnvironmentProtectionParams struct {
	EnvironmentID   string
	RequireApproval bool
	MinApproverRole string
	FreezeEnabled   bool
}

// UpsertEnvironmentProtection replaces the whole document: PUT carries desired
// state, so there is no partial-update path that could leave the flags and the
// windows describing different intents (§6).
func (q *Queries) UpsertEnvironmentProtection(ctx context.Context, arg UpsertEnvironmentProtectionParams) (EnvironmentProtection, error) {
	row := q.db.QueryRow(ctx, upsertEnvironmentProtection,
		arg.EnvironmentID,
		arg.RequireApproval,
		arg.MinApproverRole,
		arg.FreezeEnabled,
	)
	var i EnvironmentProtection
	err := row.Scan(
		&i.EnvironmentID,
		&i.RequireApproval,
		&i.MinApproverRole,
		&i.FreezeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
