// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deploy_keys.sql

package db

import (
	"context"
)

const createDeployKey = `-- name: CreateDeployKey :one
INSERT INTO deploy_keys (
    id, name, public_key, fingerprint, private_key_ct, private_key_nonce
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, public_key, fingerprint, private_key_ct, private_key_nonce, created_at
`

type CreateDeployKeyParams struct {
	ID              string
	Name            string
	PublicKey       string
	Fingerprint     string
	PrivateKeyCt    []byte
	PrivateKeyNonce []byte
}

// Create a new deploy key. The private key is sealed (threat-model §5.1).
func (q *Queries) CreateDeployKey(ctx context.Context, arg CreateDeployKeyParams) (DeployKey, error) {
	row := q.db.QueryRow(ctx, createDeployKey,
		arg.ID,
		arg.Name,
		arg.PublicKey,
		arg.Fingerprint,
		arg.PrivateKeyCt,
		arg.PrivateKeyNonce,
	)
	var i DeployKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.PrivateKeyCt,
		&i.PrivateKeyNonce,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeployKey = `-- name: DeleteDeployKey :exec
DELETE FROM deploy_keys WHERE id = $1
`

// Delete a deploy key (RESTRICT-gated by application references).
func (q *Queries) DeleteDeployKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDeployKey, id)
	return err
}

const getDeployKey = `-- name: GetDeployKey :one
SELECT id, name, public_key, fingerprint, private_key_ct, private_key_nonce, created_at FROM deploy_keys WHERE id = $1 LIMIT 1
`

// Get a deploy key by ID.
func (q *Queries) GetDeployKey(ctx context.Context, id string) (DeployKey, error) {
	row := q.db.QueryRow(ctx, getDeployKey, id)
	var i DeployKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.Fingerprint,
		&i.PrivateKeyCt,
		&i.PrivateKeyNonce,
		&i.CreatedAt,
	)
	return i, err
}

const listDeployKeys = `-- name: ListDeployKeys :many
SELECT id, name, public_key, fingerprint, private_key_ct, private_key_nonce, created_at FROM deploy_keys ORDER BY created_at DESC
`

// List all deploy keys.
func (q *Queries) ListDeployKeys(ctx context.Context) ([]DeployKey, error) {
	rows, err := q.db.Query(ctx, listDeployKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployKey{}
	for rows.Next() {
		var i DeployKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicKey,
			&i.Fingerprint,
			&i.PrivateKeyCt,
			&i.PrivateKeyNonce,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
