// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDNSZones = `-- name: CountDNSZones :one
SELECT count(*) FROM dns_zones
`

func (q *Queries) CountDNSZones(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDNSZones)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countManagedRecordsByZone = `-- name: CountManagedRecordsByZone :many
SELECT zone_id, count(*)::bigint AS managed_records
FROM dns_records
WHERE desired = 'present'
GROUP BY zone_id
`

type CountManagedRecordsByZoneRow struct {
	ZoneID         string
	ManagedRecords int64
}

// Managed records per zone, counting only what the panel still wants to exist.
// A tombstoned row (desired='absent') is on its way out and would overstate
// what disconnecting the provider affects.
func (q *Queries) CountManagedRecordsByZone(ctx context.Context) ([]CountManagedRecordsByZoneRow, error) {
	rows, err := q.db.Query(ctx, countManagedRecordsByZone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountManagedRecordsByZoneRow{}
	for rows.Next() {
		var i CountManagedRecordsByZoneRow
		if err := rows.Scan(&i.ZoneID, &i.ManagedRecords); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDNSProvider = `-- name: DeleteDNSProvider :exec
DELETE FROM dns_providers WHERE id = 1
`

func (q *Queries) DeleteDNSProvider(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteDNSProvider)
	return err
}

const deleteDNSRecordRow = `-- name: DeleteDNSRecordRow :exec
DELETE FROM dns_records WHERE id = $1
`

func (q *Queries) DeleteDNSRecordRow(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDNSRecordRow, id)
	return err
}

const deleteDNSZonesNotIn = `-- name: DeleteDNSZonesNotIn :exec
DELETE FROM dns_zones WHERE name <> ALL($1::text[])
`

// ReplaceDNSZones is how a refresh lands: the provider's answer is the whole
// truth, so anything it no longer lists is no longer ours to manage. Zones with
// records still attached are protected by dns_records' ON DELETE RESTRICT, so a
// zone that still has managed records cannot silently vanish from the cache —
// the refresh fails loudly instead, which is the safe direction.
func (q *Queries) DeleteDNSZonesNotIn(ctx context.Context, names []string) error {
	_, err := q.db.Exec(ctx, deleteDNSZonesNotIn, names)
	return err
}

const failDNSRecord = `-- name: FailDNSRecord :exec
UPDATE dns_records
SET last_error = $2, attempt = $3, next_attempt_at = $4, updated_at = now()
WHERE id = $1
`

type FailDNSRecordParams struct {
	ID            string
	LastError     string
	Attempt       int32
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) FailDNSRecord(ctx context.Context, arg FailDNSRecordParams) error {
	_, err := q.db.Exec(ctx, failDNSRecord,
		arg.ID,
		arg.LastError,
		arg.Attempt,
		arg.NextAttemptAt,
	)
	return err
}

const getDNSProvider = `-- name: GetDNSProvider :one

SELECT kind, config_ct, config_nonce, updated_at FROM dns_providers WHERE id = 1
`

type GetDNSProviderRow struct {
	Kind        string
	ConfigCt    []byte
	ConfigNonce []byte
	UpdatedAt   pgtype.Timestamptz
}

// DNS automation (dns-automation.md). The provider is a singleton on
// panel_mail's shape; zones are a cache; records are desired state.
func (q *Queries) GetDNSProvider(ctx context.Context) (GetDNSProviderRow, error) {
	row := q.db.QueryRow(ctx, getDNSProvider)
	var i GetDNSProviderRow
	err := row.Scan(
		&i.Kind,
		&i.ConfigCt,
		&i.ConfigNonce,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSRecord = `-- name: GetDNSRecord :one

SELECT id, application_id, zone_id, name, type, content, desired, provider_record_id, last_error, attempt, next_attempt_at, created_at, updated_at FROM dns_records WHERE id = $1
`

// ─── Records (desired state) ────────────────────────────────────────────────
func (q *Queries) GetDNSRecord(ctx context.Context, id string) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, getDNSRecord, id)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Desired,
		&i.ProviderRecordID,
		&i.LastError,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSRecordByApplication = `-- name: GetDNSRecordByApplication :one
SELECT id, application_id, zone_id, name, type, content, desired, provider_record_id, last_error, attempt, next_attempt_at, created_at, updated_at FROM dns_records WHERE application_id = $1 AND desired = 'present'
`

func (q *Queries) GetDNSRecordByApplication(ctx context.Context, applicationID pgtype.Text) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, getDNSRecordByApplication, applicationID)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Desired,
		&i.ProviderRecordID,
		&i.LastError,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSZoneByName = `-- name: GetDNSZoneByName :one
SELECT id, provider_zone_id, name, refreshed_at, status FROM dns_zones WHERE name = $1
`

func (q *Queries) GetDNSZoneByName(ctx context.Context, name string) (DnsZone, error) {
	row := q.db.QueryRow(ctx, getDNSZoneByName, name)
	var i DnsZone
	err := row.Scan(
		&i.ID,
		&i.ProviderZoneID,
		&i.Name,
		&i.RefreshedAt,
		&i.Status,
	)
	return i, err
}

const listApplicationsWantingDNS = `-- name: ListApplicationsWantingDNS :many
SELECT a.id, a.route_domain, s.public_address
FROM applications a
JOIN servers s ON s.id = a.runtime_server_id
WHERE a.route_domain <> '' AND s.public_address <> ''
ORDER BY a.id
`

type ListApplicationsWantingDNSRow struct {
	ID            string
	RouteDomain   string
	PublicAddress string
}

// ListApplicationsWantingDNS is what makes record CREATION state-owned rather
// than event-owned.
//
// Hooking the two application REST handlers was not enough: a template install
// creates applications through templates.Install, a preview environment through
// its own path, and each new caller would silently produce no DNS at all. The
// first real use of this feature hit exactly that — a Grafana template with a
// verified domain and no record, because no hook fired. Deriving the desired
// set from the applications table on every sweep makes it impossible for a
// creation path to be forgotten (§4.3, and research/coolify.md's lesson that
// lifecycle must be owned by state, not events).
//
// Applications whose server has no public address are excluded here rather than
// filtered later: there is nothing to point a record at, and §6 reports that as
// its own state.
func (q *Queries) ListApplicationsWantingDNS(ctx context.Context) ([]ListApplicationsWantingDNSRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsWantingDNS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsWantingDNSRow{}
	for rows.Next() {
		var i ListApplicationsWantingDNSRow
		if err := rows.Scan(&i.ID, &i.RouteDomain, &i.PublicAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsWithManagedDNS = `-- name: ListApplicationsWithManagedDNS :many
SELECT r.application_id, a.name AS application_name, r.name AS domain, z.name AS zone_name
FROM dns_records r
JOIN dns_zones z ON z.id = r.zone_id
JOIN applications a ON a.id = r.application_id
WHERE r.desired = 'present' AND r.application_id IS NOT NULL
ORDER BY z.name, r.name
`

type ListApplicationsWithManagedDNSRow struct {
	ApplicationID   pgtype.Text
	ApplicationName string
	Domain          string
	ZoneName        string
}

// The applications whose domains are verified through the connected provider,
// which is exactly what stops being verified if it is disconnected. Ordered so
// a confirmation dialog reads the same way twice.
func (q *Queries) ListApplicationsWithManagedDNS(ctx context.Context) ([]ListApplicationsWithManagedDNSRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsWithManagedDNS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsWithManagedDNSRow{}
	for rows.Next() {
		var i ListApplicationsWithManagedDNSRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.ApplicationName,
			&i.Domain,
			&i.ZoneName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSRecordsForServer = `-- name: ListDNSRecordsForServer :many
SELECT r.id, r.application_id, r.zone_id, r.name, r.type, r.content, r.desired, r.provider_record_id, r.last_error, r.attempt, r.next_attempt_at, r.created_at, r.updated_at FROM dns_records r
JOIN applications a ON a.id = r.application_id
WHERE a.runtime_server_id = $1 AND r.desired = 'present'
`

// ListDNSRecordsForServerChange re-points every record whose application runs
// on a server whose public address just changed (§4.3).
func (q *Queries) ListDNSRecordsForServer(ctx context.Context, runtimeServerID string) ([]DnsRecord, error) {
	rows, err := q.db.Query(ctx, listDNSRecordsForServer, runtimeServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ZoneID,
			&i.Name,
			&i.Type,
			&i.Content,
			&i.Desired,
			&i.ProviderRecordID,
			&i.LastError,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSZones = `-- name: ListDNSZones :many

SELECT id, provider_zone_id, name, refreshed_at, status FROM dns_zones ORDER BY name
`

// ─── Zones (a cache of what the provider says we may manage) ────────────────
func (q *Queries) ListDNSZones(ctx context.Context) ([]DnsZone, error) {
	rows, err := q.db.Query(ctx, listDNSZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsZone{}
	for rows.Next() {
		var i DnsZone
		if err := rows.Scan(
			&i.ID,
			&i.ProviderZoneID,
			&i.Name,
			&i.RefreshedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDNSRecords = `-- name: ListDueDNSRecords :many
SELECT r.id, r.application_id, r.zone_id, r.name, r.type, r.content, r.desired, r.provider_record_id, r.last_error, r.attempt, r.next_attempt_at, r.created_at, r.updated_at, z.provider_zone_id, z.name AS zone_name
FROM dns_records r
JOIN dns_zones z ON z.id = r.zone_id
WHERE (r.next_attempt_at IS NOT NULL AND r.next_attempt_at <= $1)
  AND ((r.desired = 'present' AND r.provider_record_id IS NULL)
    OR (r.desired = 'absent'  AND r.provider_record_id IS NOT NULL))
ORDER BY r.next_attempt_at
LIMIT $2
`

type ListDueDNSRecordsParams struct {
	NextAttemptAt pgtype.Timestamptz
	Limit         int32
}

type ListDueDNSRecordsRow struct {
	ID               string
	ApplicationID    pgtype.Text
	ZoneID           string
	Name             string
	Type             string
	Content          string
	Desired          string
	ProviderRecordID pgtype.Text
	LastError        string
	Attempt          int32
	NextAttemptAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ProviderZoneID   string
	ZoneName         string
}

// ListDueDNSRecords is the sweeper's working set: rows whose observed state
// does not match `desired` and whose backoff has elapsed.
func (q *Queries) ListDueDNSRecords(ctx context.Context, arg ListDueDNSRecordsParams) ([]ListDueDNSRecordsRow, error) {
	rows, err := q.db.Query(ctx, listDueDNSRecords, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueDNSRecordsRow{}
	for rows.Next() {
		var i ListDueDNSRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ZoneID,
			&i.Name,
			&i.Type,
			&i.Content,
			&i.Desired,
			&i.ProviderRecordID,
			&i.LastError,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderZoneID,
			&i.ZoneName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDNSRecordCreated = `-- name: MarkDNSRecordCreated :one
UPDATE dns_records
SET provider_record_id = $2, last_error = '', attempt = 0, next_attempt_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, application_id, zone_id, name, type, content, desired, provider_record_id, last_error, attempt, next_attempt_at, created_at, updated_at
`

type MarkDNSRecordCreatedParams struct {
	ID               string
	ProviderRecordID pgtype.Text
}

// MarkDNSRecordCreated records the observation that the record now exists.
// next_attempt_at goes NULL: converged rows are not work.
func (q *Queries) MarkDNSRecordCreated(ctx context.Context, arg MarkDNSRecordCreatedParams) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, markDNSRecordCreated, arg.ID, arg.ProviderRecordID)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Desired,
		&i.ProviderRecordID,
		&i.LastError,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDNSProvider = `-- name: SetDNSProvider :exec
INSERT INTO dns_providers (id, kind, config_ct, config_nonce, updated_at)
VALUES (1, $1, $2, $3, now())
ON CONFLICT (id) DO UPDATE
SET kind = EXCLUDED.kind, config_ct = EXCLUDED.config_ct,
    config_nonce = EXCLUDED.config_nonce, updated_at = now()
`

type SetDNSProviderParams struct {
	Kind        string
	ConfigCt    []byte
	ConfigNonce []byte
}

func (q *Queries) SetDNSProvider(ctx context.Context, arg SetDNSProviderParams) error {
	_, err := q.db.Exec(ctx, setDNSProvider, arg.Kind, arg.ConfigCt, arg.ConfigNonce)
	return err
}

const setServerPublicAddress = `-- name: SetServerPublicAddress :one

UPDATE servers SET public_address = $2, updated_at = now() WHERE id = $1 RETURNING id, name, status, driver, agent_version, hostname, enrolled_at, last_seen_at, created_at, updated_at, role, public_address
`

type SetServerPublicAddressParams struct {
	ID            string
	PublicAddress string
}

// ─── Server public address ──────────────────────────────────────────────────
func (q *Queries) SetServerPublicAddress(ctx context.Context, arg SetServerPublicAddressParams) (Server, error) {
	row := q.db.QueryRow(ctx, setServerPublicAddress, arg.ID, arg.PublicAddress)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Driver,
		&i.AgentVersion,
		&i.Hostname,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.PublicAddress,
	)
	return i, err
}

const tombstoneDNSRecord = `-- name: TombstoneDNSRecord :exec
UPDATE dns_records
SET desired = 'absent', next_attempt_at = now(), attempt = 0, last_error = '', updated_at = now()
WHERE id = $1
`

// TombstoneDNSRecord is deletion, expressed as desired state. The row is NOT
// removed: it is the only remaining record of what has to be deleted from the
// provider, and dropping it here is exactly how an orphan leaks (§3.3).
func (q *Queries) TombstoneDNSRecord(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, tombstoneDNSRecord, id)
	return err
}

const tombstoneDNSRecordsForApplication = `-- name: TombstoneDNSRecordsForApplication :exec
UPDATE dns_records
SET desired = 'absent', next_attempt_at = now(), attempt = 0, last_error = '', updated_at = now()
WHERE application_id = $1 AND desired = 'present'
`

func (q *Queries) TombstoneDNSRecordsForApplication(ctx context.Context, applicationID pgtype.Text) error {
	_, err := q.db.Exec(ctx, tombstoneDNSRecordsForApplication, applicationID)
	return err
}

const tombstoneDNSRecordsForEnvironment = `-- name: TombstoneDNSRecordsForEnvironment :exec
UPDATE dns_records r
SET desired = 'absent', next_attempt_at = now(), attempt = 0, last_error = '', updated_at = now()
FROM applications a
WHERE r.application_id = a.id AND a.environment_id = $1 AND r.desired = 'present'
`

func (q *Queries) TombstoneDNSRecordsForEnvironment(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, tombstoneDNSRecordsForEnvironment, environmentID)
	return err
}

const tombstoneDNSRecordsForProject = `-- name: TombstoneDNSRecordsForProject :exec
UPDATE dns_records r
SET desired = 'absent', next_attempt_at = now(), attempt = 0, last_error = '', updated_at = now()
FROM applications a
JOIN environments e ON e.id = a.environment_id
WHERE r.application_id = a.id AND e.project_id = $1 AND r.desired = 'present'
`

// TombstoneDNSRecordsForProject reaches every application under a project,
// through environments, so deleting a project reaps its records too (§4.3).
func (q *Queries) TombstoneDNSRecordsForProject(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, tombstoneDNSRecordsForProject, projectID)
	return err
}

const tombstoneOrphanedDNSRecords = `-- name: TombstoneOrphanedDNSRecords :exec
UPDATE dns_records
SET desired = 'absent', next_attempt_at = now(), attempt = 0, last_error = '', updated_at = now()
WHERE application_id IS NULL AND desired = 'present'
`

// TombstoneOrphanedDNSRecords is how deletion actually becomes reliable.
//
// dns_records.application_id is ON DELETE SET NULL, and environments and
// projects cascade to applications — so deleting an application, an environment
// or a whole project all leave the SAME trace: a record with no application. A
// record with no application has no reason to exist, so this one statement
// reaps all three cases without a hook per case, and without depending on an
// event that might not fire (§4.3, and research/coolify.md's orphan lesson).
func (q *Queries) TombstoneOrphanedDNSRecords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, tombstoneOrphanedDNSRecords)
	return err
}

const upsertDNSRecord = `-- name: UpsertDNSRecord :one
INSERT INTO dns_records (id, application_id, zone_id, name, type, content, desired, next_attempt_at)
VALUES ($1, $2, $3, $4, $5, $6, 'present', now())
ON CONFLICT (zone_id, name, type) DO UPDATE
SET application_id = EXCLUDED.application_id,
    content        = EXCLUDED.content,
    desired        = 'present',
    -- Re-arm: a row coming back to 'present', or changing content, is work
    -- again. Clearing the error and the attempt count is what makes a fixed
    -- misconfiguration retry immediately instead of waiting out the old
    -- backoff.
    last_error      = '',
    attempt         = 0,
    next_attempt_at = now(),
    updated_at      = now()
RETURNING id, application_id, zone_id, name, type, content, desired, provider_record_id, last_error, attempt, next_attempt_at, created_at, updated_at
`

type UpsertDNSRecordParams struct {
	ID            string
	ApplicationID pgtype.Text
	ZoneID        string
	Name          string
	Type          string
	Content       string
}

func (q *Queries) UpsertDNSRecord(ctx context.Context, arg UpsertDNSRecordParams) (DnsRecord, error) {
	row := q.db.QueryRow(ctx, upsertDNSRecord,
		arg.ID,
		arg.ApplicationID,
		arg.ZoneID,
		arg.Name,
		arg.Type,
		arg.Content,
	)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ZoneID,
		&i.Name,
		&i.Type,
		&i.Content,
		&i.Desired,
		&i.ProviderRecordID,
		&i.LastError,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDNSZone = `-- name: UpsertDNSZone :one
INSERT INTO dns_zones (id, provider_zone_id, name, status, refreshed_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (name) DO UPDATE
SET provider_zone_id = EXCLUDED.provider_zone_id, status = EXCLUDED.status, refreshed_at = now()
RETURNING id, provider_zone_id, name, refreshed_at, status
`

type UpsertDNSZoneParams struct {
	ID             string
	ProviderZoneID string
	Name           string
	Status         string
}

func (q *Queries) UpsertDNSZone(ctx context.Context, arg UpsertDNSZoneParams) (DnsZone, error) {
	row := q.db.QueryRow(ctx, upsertDNSZone,
		arg.ID,
		arg.ProviderZoneID,
		arg.Name,
		arg.Status,
	)
	var i DnsZone
	err := row.Scan(
		&i.ID,
		&i.ProviderZoneID,
		&i.Name,
		&i.RefreshedAt,
		&i.Status,
	)
	return i, err
}
