// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package db

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, project_id, name) VALUES ($1, $2, $3) RETURNING id, project_id, name, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID        string
	ProjectID string
	Name      string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ID, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, name, created_at, updated_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, created_at, updated_at FROM environments WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID string) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
