// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTeamInvite = `-- name: AcceptTeamInvite :one
UPDATE team_invites
SET accepted_at = now()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
RETURNING id, team_id, email, role, token_hash, invited_by, invited_by_label, expires_at, accepted_at, revoked_at, created_at
`

// AcceptTeamInvite is the spend, and it is ONE statement on purpose: no row
// back means expired, revoked, or already accepted by whoever got there first.
// A read-then-write would grant the same invite twice under a double-submit.
func (q *Queries) AcceptTeamInvite(ctx context.Context, id string) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, acceptTeamInvite, id)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.InvitedByLabel,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamInvite = `-- name: CreateTeamInvite :one

INSERT INTO team_invites (
    id, team_id, email, role, token_hash, invited_by, invited_by_label, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, team_id, email, role, token_hash, invited_by, invited_by_label, expires_at, accepted_at, revoked_at, created_at
`

type CreateTeamInviteParams struct {
	ID             string
	TeamID         string
	Email          string
	Role           string
	TokenHash      []byte
	InvitedBy      pgtype.Text
	InvitedByLabel string
	ExpiresAt      pgtype.Timestamptz
}

// Team invitations (invitations-and-access-requests.md §2, §4).
//
// The wire token is `<id>.<secret>`: every lookup here is by the row's own id,
// and only the HASH of the secret is stored, so the caller compares in constant
// time before anything is spent. Nothing in this file selects by token_hash,
// because nothing needs to — and a query that did would invite a plaintext
// token to travel to the database.
func (q *Queries) CreateTeamInvite(ctx context.Context, arg CreateTeamInviteParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, createTeamInvite,
		arg.ID,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.InvitedByLabel,
		arg.ExpiresAt,
	)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.InvitedByLabel,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamInvite = `-- name: GetTeamInvite :one
SELECT id, team_id, email, role, token_hash, invited_by, invited_by_label, expires_at, accepted_at, revoked_at, created_at FROM team_invites WHERE id = $1
`

func (q *Queries) GetTeamInvite(ctx context.Context, id string) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, getTeamInvite, id)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.InvitedByLabel,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamInvites = `-- name: ListTeamInvites :many
SELECT id, team_id, email, role, token_hash, invited_by, invited_by_label, expires_at, accepted_at, revoked_at, created_at FROM team_invites
WHERE team_id = $1
  AND ($2::boolean
       OR (accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()))
ORDER BY created_at DESC
`

type ListTeamInvitesParams struct {
	TeamID         string
	IncludeDecided bool
}

// ListTeamInvites serves the admin listing. include_decided=false is the
// default view: only invites that can still be accepted, which is what an
// operator means by "outstanding" (an expired one is not actionable, and it is
// excluded here rather than filtered in Go so the page and the count agree).
func (q *Queries) ListTeamInvites(ctx context.Context, arg ListTeamInvitesParams) ([]TeamInvite, error) {
	rows, err := q.db.Query(ctx, listTeamInvites, arg.TeamID, arg.IncludeDecided)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamInvite{}
	for rows.Next() {
		var i TeamInvite
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.InvitedByLabel,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLiveTeamInvitesBy = `-- name: RevokeLiveTeamInvitesBy :execrows
UPDATE team_invites
SET revoked_at = now()
WHERE team_id = $1 AND invited_by = $2
  AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeLiveTeamInvitesByParams struct {
	TeamID    string
	InvitedBy pgtype.Text
}

// RevokeLiveTeamInvitesBy revokes the invitations one member issued for one
// team. Called when that member is removed: an invite outlives its issuer's
// session, but not their membership — otherwise a removed admin keeps a 7-day
// back door in an envelope (§8).
func (q *Queries) RevokeLiveTeamInvitesBy(ctx context.Context, arg RevokeLiveTeamInvitesByParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLiveTeamInvitesBy, arg.TeamID, arg.InvitedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLiveTeamInvitesFor = `-- name: RevokeLiveTeamInvitesFor :execrows
UPDATE team_invites
SET revoked_at = now()
WHERE team_id = $1 AND email = $2
  AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeLiveTeamInvitesForParams struct {
	TeamID string
	Email  string
}

// RevokeLiveTeamInvitesFor supersedes: re-inviting an address kills whatever is
// outstanding for it on this team, so the partial unique index can never be
// violated by an ordinary re-invite and an operator is never stuck behind a
// link they cannot see (§2).
func (q *Queries) RevokeLiveTeamInvitesFor(ctx context.Context, arg RevokeLiveTeamInvitesForParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLiveTeamInvitesFor, arg.TeamID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTeamInvite = `-- name: RevokeTeamInvite :one
UPDATE team_invites
SET revoked_at = now()
WHERE id = $1 AND team_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
RETURNING id, team_id, email, role, token_hash, invited_by, invited_by_label, expires_at, accepted_at, revoked_at, created_at
`

type RevokeTeamInviteParams struct {
	ID     string
	TeamID string
}

// RevokeTeamInvite is idempotent by predicate: no row back means it was
// already revoked, already accepted, or never existed — one undifferentiated
// answer, which is the same discipline the accept path uses.
func (q *Queries) RevokeTeamInvite(ctx context.Context, arg RevokeTeamInviteParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, revokeTeamInvite, arg.ID, arg.TeamID)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.InvitedByLabel,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
