// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: join_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeJoinToken = `-- name: ConsumeJoinToken :one
UPDATE join_tokens
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, server_id, token_hash, expires_at, consumed_at, created_at
`

// ConsumeJoinToken atomically marks a token used, but only if it is still
// unconsumed and unexpired. A concurrent second enrollment attempt with the
// same token returns no row — this is the single-use guarantee (threat-model
// §5.3), enforced by the database, not by application-level checking.
func (q *Queries) ConsumeJoinToken(ctx context.Context, id string) (JoinToken, error) {
	row := q.db.QueryRow(ctx, consumeJoinToken, id)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinToken = `-- name: CreateJoinToken :one
INSERT INTO join_tokens (id, server_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, server_id, token_hash, expires_at, consumed_at, created_at
`

type CreateJoinTokenParams struct {
	ID        string
	ServerID  string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateJoinToken(ctx context.Context, arg CreateJoinTokenParams) (JoinToken, error) {
	row := q.db.QueryRow(ctx, createJoinToken,
		arg.ID,
		arg.ServerID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJoinToken = `-- name: GetJoinToken :one
SELECT id, server_id, token_hash, expires_at, consumed_at, created_at FROM join_tokens WHERE id = $1
`

func (q *Queries) GetJoinToken(ctx context.Context, id string) (JoinToken, error) {
	row := q.db.QueryRow(ctx, getJoinToken, id)
	var i JoinToken
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
