// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  []byte
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	Abilities  []string
}

type AppEnvVar struct {
	ApplicationID string
	Key           string
	ValueCt       []byte
	ValueNonce    []byte
	SharedRefs    []string
}

type Application struct {
	ID                    string
	EnvironmentID         string
	Name                  string
	SourceKind            string
	SourceRepo            string
	SourceBranch          string
	SourceDeployKeyID     pgtype.Text
	BuildKind             string
	BuildDockerfilePath   string
	BuildContext          string
	RuntimeServerID       string
	RuntimePort           int32
	RuntimeReplicas       int32
	RouteDomain           string
	RouteHttps            bool
	RoutePathPrefix       string
	HealthPath            string
	HealthIntervalSeconds int32
	HealthTimeoutSeconds  int32
	HealthRetries         int32
	WebhookID             string
	WebhookSecretCt       []byte
	WebhookSecretNonce    []byte
	DesiredRevisionID     pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Status                string
	StatusDetail          string
	ObservedRevisionID    string
	StatusObservedAt      pgtype.Timestamptz
	PreviewEnabled        bool
	PreviewBaseDomain     string
	PreviewTtlHours       int32
	CpuLimit              pgtype.Float4
	MemoryLimitMb         pgtype.Int4
	Volumes               []byte
	Ports                 []byte
	HealthKind            string
	SourceImage           string
	EnvAppliedAt          pgtype.Timestamptz
}

type BackupRecord struct {
	ID               string
	DatabaseBackupID string
	ObjectKey        string
	SizeBytes        int64
	Status           string
	Detail           string
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type BackupTarget struct {
	ID             string
	Name           string
	Endpoint       string
	Bucket         string
	Region         string
	AccessKeyCt    []byte
	AccessKeyNonce []byte
	SecretKeyCt    []byte
	SecretKeyNonce []byte
	PathPrefix     string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Database struct {
	ID                 string
	EnvironmentID      string
	Name               string
	Engine             string
	Version            string
	ServerID           string
	CpuLimit           pgtype.Float4
	MemoryLimitMb      pgtype.Int4
	VolumeName         string
	DataPath           string
	ExposePort         pgtype.Int4
	Network            string
	RootUser           string
	RootPasswordCt     []byte
	RootPasswordNonce  []byte
	RequirePassword    bool
	DesiredRevisionID  pgtype.Text
	DesiredState       string
	Status             string
	StatusDetail       string
	ObservedRevisionID string
	StatusObservedAt   pgtype.Timestamptz
	PendingDelete      bool
	DeleteVolume       bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	InitialDatabase    string
}

type DatabaseBackup struct {
	ID             string
	DatabaseID     string
	TargetID       string
	Schedule       string
	RetentionCount int32
	Enabled        bool
	LastRunAt      pgtype.Timestamptz
	LastStatus     string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type DatabaseRevision struct {
	ID             string
	DatabaseID     string
	ConfigSnapshot []byte
	CreatedAt      pgtype.Timestamptz
}

type DeployKey struct {
	ID              string
	Name            string
	PublicKey       string
	Fingerprint     string
	PrivateKeyCt    []byte
	PrivateKeyNonce []byte
	CreatedAt       pgtype.Timestamptz
}

type Deployment struct {
	ID              string
	ApplicationID   string
	RevisionID      string
	Status          string
	Trigger         string
	Detail          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	BuilderServerID pgtype.Text
	EnvResolvedAt   pgtype.Timestamptz
}

type DnsProvider struct {
	ID          int32
	Kind        string
	ConfigCt    []byte
	ConfigNonce []byte
	UpdatedAt   pgtype.Timestamptz
}

type DnsRecord struct {
	ID               string
	ApplicationID    pgtype.Text
	ZoneID           string
	Name             string
	Type             string
	Content          string
	Desired          string
	ProviderRecordID pgtype.Text
	LastError        string
	Attempt          int32
	NextAttemptAt    pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type DnsZone struct {
	ID             string
	ProviderZoneID string
	Name           string
	RefreshedAt    pgtype.Timestamptz
	Status         string
}

type EmailChange struct {
	ID         string
	UserID     string
	NewEmail   string
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Environment struct {
	ID        string
	ProjectID string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Kind      string
}

type InboxItem struct {
	ID         string
	UserID     string
	ProjectID  pgtype.Text
	Kind       string
	Severity   string
	Digest     bool
	Title      string
	Body       string
	Link       string
	LinkLabel  string
	CountOk    int32
	CountTotal int32
	Sources    []string
	DedupeKey  string
	ReadAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type InboxPreference struct {
	UserID     string
	MutedKinds []string
	UpdatedAt  pgtype.Timestamptz
}

type JoinToken struct {
	ID         string
	ServerID   string
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Notifier struct {
	ID          string
	ProjectID   string
	Name        string
	Channel     string
	ConfigCt    []byte
	ConfigNonce []byte
	Events      []string
	Enabled     bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PanelMail struct {
	ID          int32
	ConfigCt    []byte
	ConfigNonce []byte
	UpdatedAt   pgtype.Timestamptz
}

type PanelTl struct {
	ID           int32
	AcmeEmail    string
	AcmeCaServer string
	UpdatedAt    pgtype.Timestamptz
}

type PlaneCa struct {
	ID           int32
	CertPem      []byte
	EncryptedKey []byte
	KeyNonce     []byte
	CreatedAt    pgtype.Timestamptz
}

type Preview struct {
	ID            string
	SourceAppID   string
	EnvironmentID string
	PreviewAppID  pgtype.Text
	PrNumber      int32
	PrBranch      string
	Domain        string
	Status        string
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Project struct {
	ID                   string
	Name                 string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	TeamID               string
	Slug                 string
	DefaultEnvironmentID pgtype.Text
	LastActivityAt       pgtype.Timestamptz
}

type Revision struct {
	ID             string
	ApplicationID  string
	Image          string
	SourceCommit   string
	ConfigSnapshot []byte
	CreatedAt      pgtype.Timestamptz
}

type ScheduledTask struct {
	ID            string
	ApplicationID string
	Name          string
	Schedule      string
	Command       []string
	Enabled       bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ScheduledTaskRun struct {
	ID         string
	TaskID     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	ExitCode   pgtype.Int4
	Status     string
	OutputTail string
	CreatedAt  pgtype.Timestamptz
}

type Server struct {
	ID            string
	Name          string
	Status        string
	Driver        string
	AgentVersion  string
	Hostname      string
	EnrolledAt    pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Role          string
	PublicAddress string
}

type Session struct {
	ID        string
	UserID    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type SharedVariable struct {
	ID            string
	ProjectID     string
	EnvironmentID pgtype.Text
	Key           string
	ValueCt       []byte
	ValueNonce    []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Team struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TeamMember struct {
	TeamID    string
	UserID    string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type TotpRecoveryCode struct {
	ID        string
	UserID    string
	CodeHash  []byte
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID              string
	Email           string
	PasswordHash    string
	Role            string
	TotpSecretEnc   []byte
	TotpSecretNonce []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	TotpEnabled     bool
	DisplayName     string
	Timezone        string
}

type UserAvatar struct {
	UserID      string
	ContentType string
	Bytes       []byte
	Etag        string
	UpdatedAt   pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID            string
	EndpointID    string
	EventType     string
	ResourceKind  string
	ResourceID    string
	ResourceName  string
	Payload       string
	Status        string
	Attempt       int32
	NextAttemptAt pgtype.Timestamptz
	RedeliveryOf  pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type WebhookDeliveryAttempt struct {
	DeliveryID     string
	Attempt        int32
	ResponseStatus pgtype.Int4
	DurationMs     int32
	Error          string
	At             pgtype.Timestamptz
}

type WebhookEndpoint struct {
	ID          string
	ProjectID   string
	Url         string
	SecretCt    []byte
	SecretNonce []byte
	Events      []string
	Enabled     bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
