// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JoinToken struct {
	ID         string
	ServerID   string
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PlaneCa struct {
	ID           int32
	CertPem      []byte
	EncryptedKey []byte
	KeyNonce     []byte
	CreatedAt    pgtype.Timestamptz
}

type Server struct {
	ID           string
	Name         string
	Status       string
	Driver       string
	AgentVersion string
	Hostname     string
	EnrolledAt   pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Session struct {
	ID        string
	UserID    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
