// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: panel_mail.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePanelMail = `-- name: DeletePanelMail :exec
DELETE FROM panel_mail WHERE id = 1
`

func (q *Queries) DeletePanelMail(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletePanelMail)
	return err
}

const getPanelMail = `-- name: GetPanelMail :one
SELECT config_ct, config_nonce, updated_at FROM panel_mail WHERE id = 1
`

type GetPanelMailRow struct {
	ConfigCt    []byte
	ConfigNonce []byte
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetPanelMail(ctx context.Context) (GetPanelMailRow, error) {
	row := q.db.QueryRow(ctx, getPanelMail)
	var i GetPanelMailRow
	err := row.Scan(&i.ConfigCt, &i.ConfigNonce, &i.UpdatedAt)
	return i, err
}

const setPanelMail = `-- name: SetPanelMail :exec
INSERT INTO panel_mail (id, config_ct, config_nonce, updated_at)
VALUES (1, $1, $2, now())
ON CONFLICT (id) DO UPDATE
SET config_ct = EXCLUDED.config_ct, config_nonce = EXCLUDED.config_nonce, updated_at = now()
`

type SetPanelMailParams struct {
	ConfigCt    []byte
	ConfigNonce []byte
}

func (q *Queries) SetPanelMail(ctx context.Context, arg SetPanelMailParams) error {
	_, err := q.db.Exec(ctx, setPanelMail, arg.ConfigCt, arg.ConfigNonce)
	return err
}
