// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: panel_tls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePanelTLS = `-- name: DeletePanelTLS :exec
DELETE FROM panel_tls WHERE id = 1
`

func (q *Queries) DeletePanelTLS(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletePanelTLS)
	return err
}

const getPanelTLS = `-- name: GetPanelTLS :one

SELECT acme_email, acme_ca_server, updated_at FROM panel_tls WHERE id = 1
`

type GetPanelTLSRow struct {
	AcmeEmail    string
	AcmeCaServer string
	UpdatedAt    pgtype.Timestamptz
}

// Panel TLS settings (agent-identity-and-tls.md §4). A singleton on
// panel_mail's shape; the values are public (see the migration), so there is
// no _ct/_nonce pair here.
func (q *Queries) GetPanelTLS(ctx context.Context) (GetPanelTLSRow, error) {
	row := q.db.QueryRow(ctx, getPanelTLS)
	var i GetPanelTLSRow
	err := row.Scan(&i.AcmeEmail, &i.AcmeCaServer, &i.UpdatedAt)
	return i, err
}

const setPanelTLS = `-- name: SetPanelTLS :exec
INSERT INTO panel_tls (id, acme_email, acme_ca_server, updated_at)
VALUES (1, $1, $2, now())
ON CONFLICT (id) DO UPDATE
SET acme_email = EXCLUDED.acme_email,
    acme_ca_server = EXCLUDED.acme_ca_server,
    updated_at = now()
`

type SetPanelTLSParams struct {
	AcmeEmail    string
	AcmeCaServer string
}

func (q *Queries) SetPanelTLS(ctx context.Context, arg SetPanelTLSParams) error {
	_, err := q.db.Exec(ctx, setPanelTLS, arg.AcmeEmail, arg.AcmeCaServer)
	return err
}
