// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: panel_upgrades.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPanelUpgradeSnapshot = `-- name: AttachPanelUpgradeSnapshot :exec
UPDATE panel_upgrades SET snapshot_id = $2 WHERE id = $1
`

type AttachPanelUpgradeSnapshotParams struct {
	ID         string
	SnapshotID pgtype.Text
}

func (q *Queries) AttachPanelUpgradeSnapshot(ctx context.Context, arg AttachPanelUpgradeSnapshotParams) error {
	_, err := q.db.Exec(ctx, attachPanelUpgradeSnapshot, arg.ID, arg.SnapshotID)
	return err
}

const countRunningWork = `-- name: CountRunningWork :one
SELECT (
    (SELECT COUNT(*) FROM deployments WHERE status IN ('queued', 'building', 'distributing', 'rolling_out'))
  + (SELECT COUNT(*) FROM database_restores WHERE finished_at IS NULL)
)::BIGINT
`

// Running work is a COURTESY count, not a correctness requirement: builds and
// restores execute on agents, and a plane that restarts mid-deploy does not
// interrupt one. What waiting buys is attribution.
func (q *Queries) CountRunningWork(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningWork)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPanelSnapshot = `-- name: CreatePanelSnapshot :one
INSERT INTO panel_snapshots (id, version, path, size_bytes, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, version, path, size_bytes, created_at, expires_at, pinned
`

type CreatePanelSnapshotParams struct {
	ID        string
	Version   string
	Path      string
	SizeBytes int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePanelSnapshot(ctx context.Context, arg CreatePanelSnapshotParams) (PanelSnapshot, error) {
	row := q.db.QueryRow(ctx, createPanelSnapshot,
		arg.ID,
		arg.Version,
		arg.Path,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	var i PanelSnapshot
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Path,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Pinned,
	)
	return i, err
}

const createPanelUpgrade = `-- name: CreatePanelUpgrade :one
INSERT INTO panel_upgrades (id, from_version, to_version, actor, rollback, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, from_version, to_version, phase, detail, actor, rollback, snapshot_id, started_at, finished_at, expires_at
`

type CreatePanelUpgradeParams struct {
	ID          string
	FromVersion string
	ToVersion   string
	Actor       string
	Rollback    bool
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreatePanelUpgrade(ctx context.Context, arg CreatePanelUpgradeParams) (PanelUpgrade, error) {
	row := q.db.QueryRow(ctx, createPanelUpgrade,
		arg.ID,
		arg.FromVersion,
		arg.ToVersion,
		arg.Actor,
		arg.Rollback,
		arg.ExpiresAt,
	)
	var i PanelUpgrade
	err := row.Scan(
		&i.ID,
		&i.FromVersion,
		&i.ToVersion,
		&i.Phase,
		&i.Detail,
		&i.Actor,
		&i.Rollback,
		&i.SnapshotID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const databaseSizeBytes = `-- name: DatabaseSizeBytes :one
SELECT pg_database_size(current_database())::BIGINT
`

// The pre-flight's disk check: the snapshot needs room for a dump of this,
// twice, because a restore must be able to exist beside the thing it replaces.
func (q *Queries) DatabaseSizeBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, databaseSizeBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePanelSnapshot = `-- name: DeletePanelSnapshot :exec
DELETE FROM panel_snapshots WHERE id = $1
`

func (q *Queries) DeletePanelSnapshot(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePanelSnapshot, id)
	return err
}

const expireStalePanelUpgrades = `-- name: ExpireStalePanelUpgrades :exec
UPDATE panel_upgrades
SET phase = 'failed', detail = 'The upgrade helper stopped reporting and the lock expired.', finished_at = now()
WHERE finished_at IS NULL AND expires_at < $1
`

// Any request finding an expired lock clears it: a helper that died between
// phases must not leave the panel read-only forever.
func (q *Queries) ExpireStalePanelUpgrades(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireStalePanelUpgrades, expiresAt)
	return err
}

const getActivePanelUpgrade = `-- name: GetActivePanelUpgrade :one
SELECT id, from_version, to_version, phase, detail, actor, rollback, snapshot_id, started_at, finished_at, expires_at FROM panel_upgrades WHERE finished_at IS NULL
`

func (q *Queries) GetActivePanelUpgrade(ctx context.Context) (PanelUpgrade, error) {
	row := q.db.QueryRow(ctx, getActivePanelUpgrade)
	var i PanelUpgrade
	err := row.Scan(
		&i.ID,
		&i.FromVersion,
		&i.ToVersion,
		&i.Phase,
		&i.Detail,
		&i.Actor,
		&i.Rollback,
		&i.SnapshotID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPanelSnapshot = `-- name: GetPanelSnapshot :one
SELECT id, version, path, size_bytes, created_at, expires_at, pinned FROM panel_snapshots WHERE id = $1
`

func (q *Queries) GetPanelSnapshot(ctx context.Context, id string) (PanelSnapshot, error) {
	row := q.db.QueryRow(ctx, getPanelSnapshot, id)
	var i PanelSnapshot
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Path,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Pinned,
	)
	return i, err
}

const getPanelUpgrade = `-- name: GetPanelUpgrade :one
SELECT id, from_version, to_version, phase, detail, actor, rollback, snapshot_id, started_at, finished_at, expires_at FROM panel_upgrades WHERE id = $1
`

func (q *Queries) GetPanelUpgrade(ctx context.Context, id string) (PanelUpgrade, error) {
	row := q.db.QueryRow(ctx, getPanelUpgrade, id)
	var i PanelUpgrade
	err := row.Scan(
		&i.ID,
		&i.FromVersion,
		&i.ToVersion,
		&i.Phase,
		&i.Detail,
		&i.Actor,
		&i.Rollback,
		&i.SnapshotID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredPanelSnapshots = `-- name: ListExpiredPanelSnapshots :many
SELECT id, version, path, size_bytes, created_at, expires_at, pinned FROM panel_snapshots WHERE pinned = false AND expires_at IS NOT NULL AND expires_at < $1
`

// A pinned snapshot is never swept, whatever its expiry says: pinning is the
// operator saying "keep this one", and a sweep that overrode it would be the
// panel deciding for them.
func (q *Queries) ListExpiredPanelSnapshots(ctx context.Context, expiresAt pgtype.Timestamptz) ([]PanelSnapshot, error) {
	rows, err := q.db.Query(ctx, listExpiredPanelSnapshots, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PanelSnapshot{}
	for rows.Next() {
		var i PanelSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Path,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPanelSnapshots = `-- name: ListPanelSnapshots :many
SELECT id, version, path, size_bytes, created_at, expires_at, pinned FROM panel_snapshots ORDER BY created_at DESC
`

func (q *Queries) ListPanelSnapshots(ctx context.Context) ([]PanelSnapshot, error) {
	rows, err := q.db.Query(ctx, listPanelSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PanelSnapshot{}
	for rows.Next() {
		var i PanelSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Path,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPanelUpgrades = `-- name: ListPanelUpgrades :many
SELECT id, from_version, to_version, phase, detail, actor, rollback, snapshot_id, started_at, finished_at, expires_at FROM panel_upgrades ORDER BY started_at DESC LIMIT $1
`

func (q *Queries) ListPanelUpgrades(ctx context.Context, limit int32) ([]PanelUpgrade, error) {
	rows, err := q.db.Query(ctx, listPanelUpgrades, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PanelUpgrade{}
	for rows.Next() {
		var i PanelUpgrade
		if err := rows.Scan(
			&i.ID,
			&i.FromVersion,
			&i.ToVersion,
			&i.Phase,
			&i.Detail,
			&i.Actor,
			&i.Rollback,
			&i.SnapshotID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPanelSnapshotRetention = `-- name: SetPanelSnapshotRetention :one
UPDATE panel_snapshots SET expires_at = $3, pinned = $2 WHERE id = $1 RETURNING id, version, path, size_bytes, created_at, expires_at, pinned
`

type SetPanelSnapshotRetentionParams struct {
	ID        string
	Pinned    bool
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) SetPanelSnapshotRetention(ctx context.Context, arg SetPanelSnapshotRetentionParams) (PanelSnapshot, error) {
	row := q.db.QueryRow(ctx, setPanelSnapshotRetention, arg.ID, arg.Pinned, arg.ExpiresAt)
	var i PanelSnapshot
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Path,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Pinned,
	)
	return i, err
}

const setPanelUpgradePhase = `-- name: SetPanelUpgradePhase :exec
UPDATE panel_upgrades
SET phase = $2, detail = $3,
    finished_at = CASE WHEN $2 IN ('succeeded', 'rolled_back', 'failed') THEN now() ELSE finished_at END
WHERE id = $1
`

type SetPanelUpgradePhaseParams struct {
	ID     string
	Phase  string
	Detail string
}

func (q *Queries) SetPanelUpgradePhase(ctx context.Context, arg SetPanelUpgradePhaseParams) error {
	_, err := q.db.Exec(ctx, setPanelUpgradePhase, arg.ID, arg.Phase, arg.Detail)
	return err
}
