// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: previews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPreview = `-- name: CreatePreview :one
INSERT INTO previews (
    id, source_app_id, environment_id, preview_app_id,
    pr_number, pr_branch, domain, status, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, source_app_id, environment_id, preview_app_id, pr_number, pr_branch, domain, status, expires_at, created_at, updated_at
`

type CreatePreviewParams struct {
	ID            string
	SourceAppID   string
	EnvironmentID string
	PreviewAppID  pgtype.Text
	PrNumber      int32
	PrBranch      string
	Domain        string
	Status        string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreatePreview(ctx context.Context, arg CreatePreviewParams) (Preview, error) {
	row := q.db.QueryRow(ctx, createPreview,
		arg.ID,
		arg.SourceAppID,
		arg.EnvironmentID,
		arg.PreviewAppID,
		arg.PrNumber,
		arg.PrBranch,
		arg.Domain,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.SourceAppID,
		&i.EnvironmentID,
		&i.PreviewAppID,
		&i.PrNumber,
		&i.PrBranch,
		&i.Domain,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePreview = `-- name: DeletePreview :exec
DELETE FROM previews WHERE id = $1
`

func (q *Queries) DeletePreview(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePreview, id)
	return err
}

const getPreview = `-- name: GetPreview :one
SELECT id, source_app_id, environment_id, preview_app_id, pr_number, pr_branch, domain, status, expires_at, created_at, updated_at FROM previews WHERE id = $1
`

func (q *Queries) GetPreview(ctx context.Context, id string) (Preview, error) {
	row := q.db.QueryRow(ctx, getPreview, id)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.SourceAppID,
		&i.EnvironmentID,
		&i.PreviewAppID,
		&i.PrNumber,
		&i.PrBranch,
		&i.Domain,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreviewByPR = `-- name: GetPreviewByPR :one
SELECT id, source_app_id, environment_id, preview_app_id, pr_number, pr_branch, domain, status, expires_at, created_at, updated_at FROM previews WHERE source_app_id = $1 AND pr_number = $2
`

type GetPreviewByPRParams struct {
	SourceAppID string
	PrNumber    int32
}

func (q *Queries) GetPreviewByPR(ctx context.Context, arg GetPreviewByPRParams) (Preview, error) {
	row := q.db.QueryRow(ctx, getPreviewByPR, arg.SourceAppID, arg.PrNumber)
	var i Preview
	err := row.Scan(
		&i.ID,
		&i.SourceAppID,
		&i.EnvironmentID,
		&i.PreviewAppID,
		&i.PrNumber,
		&i.PrBranch,
		&i.Domain,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredPreviews = `-- name: ListExpiredPreviews :many
SELECT id, source_app_id, environment_id, preview_app_id, pr_number, pr_branch, domain, status, expires_at, created_at, updated_at FROM previews
WHERE expires_at IS NOT NULL AND expires_at < $1 AND status != 'destroying'
ORDER BY expires_at
`

func (q *Queries) ListExpiredPreviews(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Preview, error) {
	rows, err := q.db.Query(ctx, listExpiredPreviews, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.SourceAppID,
			&i.EnvironmentID,
			&i.PreviewAppID,
			&i.PrNumber,
			&i.PrBranch,
			&i.Domain,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewsBySourceApp = `-- name: ListPreviewsBySourceApp :many
SELECT id, source_app_id, environment_id, preview_app_id, pr_number, pr_branch, domain, status, expires_at, created_at, updated_at FROM previews WHERE source_app_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPreviewsBySourceApp(ctx context.Context, sourceAppID string) ([]Preview, error) {
	rows, err := q.db.Query(ctx, listPreviewsBySourceApp, sourceAppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Preview{}
	for rows.Next() {
		var i Preview
		if err := rows.Scan(
			&i.ID,
			&i.SourceAppID,
			&i.EnvironmentID,
			&i.PreviewAppID,
			&i.PrNumber,
			&i.PrBranch,
			&i.Domain,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPreviewStatus = `-- name: SetPreviewStatus :exec
UPDATE previews SET status = $2, updated_at = now() WHERE id = $1
`

type SetPreviewStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetPreviewStatus(ctx context.Context, arg SetPreviewStatusParams) error {
	_, err := q.db.Exec(ctx, setPreviewStatus, arg.ID, arg.Status)
	return err
}
