// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, team_id, slug) VALUES ($1, $2, $3, $4) RETURNING id, name, created_at, updated_at, team_id, slug, default_environment_id, last_activity_at
`

type CreateProjectParams struct {
	ID     string
	Name   string
	TeamID string
	Slug   string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.TeamID,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.Slug,
		&i.DefaultEnvironmentID,
		&i.LastActivityAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, created_at, updated_at, team_id, slug, default_environment_id, last_activity_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.Slug,
		&i.DefaultEnvironmentID,
		&i.LastActivityAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, created_at, updated_at, team_id, slug, default_environment_id, last_activity_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.Slug,
			&i.DefaultEnvironmentID,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectRollups = `-- name: ProjectRollups :many
WITH resources AS (
    SELECT e.project_id, a.status, 'application' AS kind
    FROM applications a JOIN environments e ON e.id = a.environment_id
    UNION ALL
    SELECT e.project_id, d.status, 'database' AS kind
    FROM databases d JOIN environments e ON e.id = d.environment_id
)
SELECT
    project_id,
    count(*) FILTER (WHERE kind = 'application')::bigint AS application_count,
    count(*) FILTER (WHERE kind = 'database')::bigint    AS database_count,
    count(*) FILTER (WHERE status = 'error')::bigint     AS error_count,
    -- Ranks the two observed vocabularies together: applications use
    -- deploying/degraded, managed databases use provisioning, and a project
    -- rollup has to speak for both.
    max(CASE status
            WHEN 'error'        THEN 5
            WHEN 'degraded'     THEN 4
            WHEN 'deploying'    THEN 3
            WHEN 'provisioning' THEN 3
            WHEN 'running'      THEN 1
            ELSE 0
        END)::int AS worst_rank
FROM resources
GROUP BY project_id
`

type ProjectRollupsRow struct {
	ProjectID        string
	ApplicationCount int64
	DatabaseCount    int64
	ErrorCount       int64
	WorstRank        int32
}

// ProjectRollups is the projects list in one query: resource counts and the
// worst status among them, per project. Rendering the list one project at a
// time would be N+1 against the operator's whole portfolio.
//
// "Worst" is ranked here rather than in Go so the ordering is the database's
// job and cannot drift between callers: error beats degraded beats deploying
// beats everything healthy.
func (q *Queries) ProjectRollups(ctx context.Context) ([]ProjectRollupsRow, error) {
	rows, err := q.db.Query(ctx, projectRollups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectRollupsRow{}
	for rows.Next() {
		var i ProjectRollupsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ApplicationCount,
			&i.DatabaseCount,
			&i.ErrorCount,
			&i.WorstRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugTakenInTeam = `-- name: SlugTakenInTeam :one
SELECT EXISTS (SELECT 1 FROM projects WHERE team_id = $1 AND slug = $2)
`

type SlugTakenInTeamParams struct {
	TeamID string
	Slug   string
}

// SlugTakenInTeam answers the collision question the service asks while
// choosing a slug. Scoped to the team, matching the unique index.
func (q *Queries) SlugTakenInTeam(ctx context.Context, arg SlugTakenInTeamParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugTakenInTeam, arg.TeamID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchProject = `-- name: TouchProject :exec
UPDATE projects SET last_activity_at = now() WHERE id = $1
`

// TouchProject records that something happened here. Called on the paths that
// change what an operator would want to see on the projects list, so "2 h ago"
// means what it says.
func (q *Queries) TouchProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchProject, id)
	return err
}

const touchProjectForEnvironment = `-- name: TouchProjectForEnvironment :exec
UPDATE projects p SET last_activity_at = now()
FROM environments e
WHERE e.id = $1 AND p.id = e.project_id
`

// TouchProjectForEnvironment reaches the project through an environment, which
// is the id most callers actually hold.
func (q *Queries) TouchProjectForEnvironment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchProjectForEnvironment, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name                   = COALESCE($1, name),
    team_id                = COALESCE($2, team_id),
    slug                   = COALESCE($3, slug),
    default_environment_id = CASE
                                 WHEN $4::bool THEN NULL
                                 ELSE COALESCE($5, default_environment_id)
                             END,
    updated_at             = now()
WHERE id = $6
RETURNING id, name, created_at, updated_at, team_id, slug, default_environment_id, last_activity_at
`

type UpdateProjectParams struct {
	Name                 pgtype.Text
	TeamID               pgtype.Text
	Slug                 pgtype.Text
	ClearDefault         pgtype.Bool
	DefaultEnvironmentID pgtype.Text
	ID                   string
}

// UpdateProject applies a partial edit. COALESCE keeps every omitted field, so
// one statement serves rename, transfer and default-environment changes without
// a read-modify-write race between them.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.TeamID,
		arg.Slug,
		arg.ClearDefault,
		arg.DefaultEnvironmentID,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.Slug,
		&i.DefaultEnvironmentID,
		&i.LastActivityAt,
	)
	return i, err
}
