// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applicationsUsingRegistry = `-- name: ApplicationsUsingRegistry :many
SELECT a.id, a.name, e.name AS environment_name, p.name AS project_name,
       (a.source_registry_id = $1) AS pulls,
       (a.build_push_registry_id = $1) AS pushes
FROM applications a
JOIN environments e ON e.id = a.environment_id
JOIN projects p ON p.id = e.project_id
WHERE a.source_registry_id = $1 OR a.build_push_registry_id = $1
ORDER BY p.name, e.name, a.name
`

type ApplicationsUsingRegistryRow struct {
	ID              string
	Name            string
	EnvironmentName string
	ProjectName     string
	Pulls           bool
	Pushes          bool
}

// The applications that would break if this registry went away: the ones that
// pull through it, and the ones that push to it. Named rather than counted,
// because "3 applications" is not something an operator can act on.
func (q *Queries) ApplicationsUsingRegistry(ctx context.Context, sourceRegistryID pgtype.Text) ([]ApplicationsUsingRegistryRow, error) {
	rows, err := q.db.Query(ctx, applicationsUsingRegistry, sourceRegistryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationsUsingRegistryRow{}
	for rows.Next() {
		var i ApplicationsUsingRegistryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnvironmentName,
			&i.ProjectName,
			&i.Pulls,
			&i.Pushes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registries (id, team_id, name, url, username, token_ct, token_nonce, can_pull, can_push)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, team_id, name, url, username, token_ct, token_nonce, can_pull, can_push, last_test_at, last_test_ok, last_test_detail, created_at, updated_at
`

type CreateRegistryParams struct {
	ID         string
	TeamID     string
	Name       string
	Url        string
	Username   string
	TokenCt    []byte
	TokenNonce []byte
	CanPull    bool
	CanPush    bool
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, createRegistry,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Url,
		arg.Username,
		arg.TokenCt,
		arg.TokenNonce,
		arg.CanPull,
		arg.CanPush,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.TokenCt,
		&i.TokenNonce,
		&i.CanPull,
		&i.CanPush,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRegistry = `-- name: DeleteRegistry :exec
DELETE FROM registries WHERE id = $1
`

func (q *Queries) DeleteRegistry(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRegistry, id)
	return err
}

const getRegistry = `-- name: GetRegistry :one
SELECT id, team_id, name, url, username, token_ct, token_nonce, can_pull, can_push, last_test_at, last_test_ok, last_test_detail, created_at, updated_at FROM registries WHERE id = $1
`

func (q *Queries) GetRegistry(ctx context.Context, id string) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistry, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.TokenCt,
		&i.TokenNonce,
		&i.CanPull,
		&i.CanPush,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistriesByTeams = `-- name: ListRegistriesByTeams :many
SELECT id, team_id, name, url, username, token_ct, token_nonce, can_pull, can_push, last_test_at, last_test_ok, last_test_detail, created_at, updated_at FROM registries WHERE team_id = ANY($1::text[]) ORDER BY name
`

func (q *Queries) ListRegistriesByTeams(ctx context.Context, teamIds []string) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistriesByTeams, teamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Url,
			&i.Username,
			&i.TokenCt,
			&i.TokenNonce,
			&i.CanPull,
			&i.CanPush,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.LastTestDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRegistryTest = `-- name: RecordRegistryTest :one
UPDATE registries
SET last_test_at = now(), last_test_ok = $2, last_test_detail = $3
WHERE id = $1
RETURNING id, team_id, name, url, username, token_ct, token_nonce, can_pull, can_push, last_test_at, last_test_ok, last_test_detail, created_at, updated_at
`

type RecordRegistryTestParams struct {
	ID             string
	LastTestOk     bool
	LastTestDetail string
}

func (q *Queries) RecordRegistryTest(ctx context.Context, arg RecordRegistryTestParams) (Registry, error) {
	row := q.db.QueryRow(ctx, recordRegistryTest, arg.ID, arg.LastTestOk, arg.LastTestDetail)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.TokenCt,
		&i.TokenNonce,
		&i.CanPull,
		&i.CanPush,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRegistry = `-- name: UpdateRegistry :one
UPDATE registries
SET name        = COALESCE($1, name),
    url         = COALESCE($2, url),
    username    = COALESCE($3, username),
    token_ct    = COALESCE($4, token_ct),
    token_nonce = COALESCE($5, token_nonce),
    can_pull    = COALESCE($6, can_pull),
    can_push    = COALESCE($7, can_push),
    updated_at  = now()
WHERE id = $8
RETURNING id, team_id, name, url, username, token_ct, token_nonce, can_pull, can_push, last_test_at, last_test_ok, last_test_detail, created_at, updated_at
`

type UpdateRegistryParams struct {
	Name       pgtype.Text
	Url        pgtype.Text
	Username   pgtype.Text
	TokenCt    []byte
	TokenNonce []byte
	CanPull    pgtype.Bool
	CanPush    pgtype.Bool
	ID         string
}

// UpdateRegistry is a partial edit: a NULL argument leaves the column alone, so
// rotating a token does not mean re-sending the URL, and renaming does not mean
// re-sending the token.
func (q *Queries) UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error) {
	row := q.db.QueryRow(ctx, updateRegistry,
		arg.Name,
		arg.Url,
		arg.Username,
		arg.TokenCt,
		arg.TokenNonce,
		arg.CanPull,
		arg.CanPush,
		arg.ID,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Url,
		&i.Username,
		&i.TokenCt,
		&i.TokenNonce,
		&i.CanPull,
		&i.CanPush,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
