// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scheduled_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduledTask = `-- name: CreateScheduledTask :one
INSERT INTO scheduled_tasks (
    id, application_id, name, schedule, command, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, application_id, name, schedule, command, enabled, created_at, updated_at
`

type CreateScheduledTaskParams struct {
	ID            string
	ApplicationID string
	Name          string
	Schedule      string
	Command       []string
	Enabled       bool
}

func (q *Queries) CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, createScheduledTask,
		arg.ID,
		arg.ApplicationID,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.Enabled,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskRun = `-- name: CreateTaskRun :one
INSERT INTO scheduled_task_runs (
    id, task_id, started_at, finished_at, exit_code, status, output_tail
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, task_id, started_at, finished_at, exit_code, status, output_tail, created_at
`

type CreateTaskRunParams struct {
	ID         string
	TaskID     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	ExitCode   pgtype.Int4
	Status     string
	OutputTail string
}

func (q *Queries) CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (ScheduledTaskRun, error) {
	row := q.db.QueryRow(ctx, createTaskRun,
		arg.ID,
		arg.TaskID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ExitCode,
		arg.Status,
		arg.OutputTail,
	)
	var i ScheduledTaskRun
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.Status,
		&i.OutputTail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldTaskRuns = `-- name: DeleteOldTaskRuns :exec
DELETE FROM scheduled_task_runs r
WHERE r.task_id = $1
  AND r.id NOT IN (
      SELECT keep.id FROM scheduled_task_runs keep
      WHERE keep.task_id = $1
      ORDER BY keep.started_at DESC
      LIMIT $2
  )
`

type DeleteOldTaskRunsParams struct {
	TaskID string
	Limit  int32
}

func (q *Queries) DeleteOldTaskRuns(ctx context.Context, arg DeleteOldTaskRunsParams) error {
	_, err := q.db.Exec(ctx, deleteOldTaskRuns, arg.TaskID, arg.Limit)
	return err
}

const deleteScheduledTask = `-- name: DeleteScheduledTask :exec
DELETE FROM scheduled_tasks WHERE id = $1
`

func (q *Queries) DeleteScheduledTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteScheduledTask, id)
	return err
}

const getScheduledTask = `-- name: GetScheduledTask :one
SELECT id, application_id, name, schedule, command, enabled, created_at, updated_at FROM scheduled_tasks WHERE id = $1
`

func (q *Queries) GetScheduledTask(ctx context.Context, id string) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, getScheduledTask, id)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledScheduledTasksByApp = `-- name: ListEnabledScheduledTasksByApp :many
SELECT id, application_id, name, schedule, command, enabled, created_at, updated_at FROM scheduled_tasks WHERE application_id = $1 AND enabled = true ORDER BY created_at
`

func (q *Queries) ListEnabledScheduledTasksByApp(ctx context.Context, applicationID string) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listEnabledScheduledTasksByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledTask{}
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTasksByApp = `-- name: ListScheduledTasksByApp :many
SELECT id, application_id, name, schedule, command, enabled, created_at, updated_at FROM scheduled_tasks WHERE application_id = $1 ORDER BY created_at
`

func (q *Queries) ListScheduledTasksByApp(ctx context.Context, applicationID string) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listScheduledTasksByApp, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledTask{}
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRuns = `-- name: ListTaskRuns :many
SELECT id, task_id, started_at, finished_at, exit_code, status, output_tail, created_at FROM scheduled_task_runs WHERE task_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListTaskRunsParams struct {
	TaskID string
	Limit  int32
}

func (q *Queries) ListTaskRuns(ctx context.Context, arg ListTaskRunsParams) ([]ScheduledTaskRun, error) {
	rows, err := q.db.Query(ctx, listTaskRuns, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledTaskRun{}
	for rows.Next() {
		var i ScheduledTaskRun
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.Status,
			&i.OutputTail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledTask = `-- name: UpdateScheduledTask :one
UPDATE scheduled_tasks
SET name = $2, schedule = $3, command = $4, enabled = $5, updated_at = now()
WHERE id = $1
RETURNING id, application_id, name, schedule, command, enabled, created_at, updated_at
`

type UpdateScheduledTaskParams struct {
	ID       string
	Name     string
	Schedule string
	Command  []string
	Enabled  bool
}

func (q *Queries) UpdateScheduledTask(ctx context.Context, arg UpdateScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, updateScheduledTask,
		arg.ID,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.Enabled,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
