// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (id, name)
VALUES ($1, $2)
RETURNING id, name, status, driver, agent_version, hostname, enrolled_at, last_seen_at, created_at, updated_at, role, public_address
`

type CreateServerParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer, arg.ID, arg.Name)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Driver,
		&i.AgentVersion,
		&i.Hostname,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.PublicAddress,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const getServer = `-- name: GetServer :one
SELECT id, name, status, driver, agent_version, hostname, enrolled_at, last_seen_at, created_at, updated_at, role, public_address FROM servers WHERE id = $1
`

func (q *Queries) GetServer(ctx context.Context, id string) (Server, error) {
	row := q.db.QueryRow(ctx, getServer, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Driver,
		&i.AgentVersion,
		&i.Hostname,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.PublicAddress,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, name, status, driver, agent_version, hostname, enrolled_at, last_seen_at, created_at, updated_at, role, public_address FROM servers ORDER BY created_at DESC
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Driver,
			&i.AgentVersion,
			&i.Hostname,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.PublicAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markServerEnrolled = `-- name: MarkServerEnrolled :one
UPDATE servers
SET enrolled_at = now(),
    hostname = $2,
    agent_version = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, driver, agent_version, hostname, enrolled_at, last_seen_at, created_at, updated_at, role, public_address
`

type MarkServerEnrolledParams struct {
	ID           string
	Hostname     string
	AgentVersion string
}

func (q *Queries) MarkServerEnrolled(ctx context.Context, arg MarkServerEnrolledParams) (Server, error) {
	row := q.db.QueryRow(ctx, markServerEnrolled, arg.ID, arg.Hostname, arg.AgentVersion)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Driver,
		&i.AgentVersion,
		&i.Hostname,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.PublicAddress,
	)
	return i, err
}

const markStaleServersUnknown = `-- name: MarkStaleServersUnknown :many
UPDATE servers
SET status = 'unknown',
    updated_at = now()
WHERE enrolled_at IS NOT NULL
  AND status <> 'unknown'
  AND (last_seen_at IS NULL OR last_seen_at < $1)
RETURNING id
`

func (q *Queries) MarkStaleServersUnknown(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, markStaleServersUnknown, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordHeartbeat = `-- name: RecordHeartbeat :one
UPDATE servers
SET status = $2,
    agent_version = $3,
    driver = $4,
    role = $5,
    last_seen_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, driver, agent_version, hostname, enrolled_at, last_seen_at, created_at, updated_at, role, public_address
`

type RecordHeartbeatParams struct {
	ID           string
	Status       string
	AgentVersion string
	Driver       string
	Role         string
}

func (q *Queries) RecordHeartbeat(ctx context.Context, arg RecordHeartbeatParams) (Server, error) {
	row := q.db.QueryRow(ctx, recordHeartbeat,
		arg.ID,
		arg.Status,
		arg.AgentVersion,
		arg.Driver,
		arg.Role,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Driver,
		&i.AgentVersion,
		&i.Hostname,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.PublicAddress,
	)
	return i, err
}

const serverIsEnrolled = `-- name: ServerIsEnrolled :one
SELECT EXISTS(
    SELECT 1 FROM servers WHERE id = $1 AND enrolled_at IS NOT NULL
) AS enrolled
`

// ServerIsEnrolled backs the bus's connection-time revocation check
// (threat-model §8 req 6): a certificate whose server row is gone or was
// never enrolled is refused, however cryptographically valid it still is.
func (q *Queries) ServerIsEnrolled(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, serverIsEnrolled, id)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}
