// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shared_variables.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applicationRedeployPending = `-- name: ApplicationRedeployPending :one
SELECT EXISTS (
    SELECT 1
    FROM applications a
    JOIN environments e ON e.id = a.environment_id
    JOIN app_env_vars v ON v.application_id = a.id
    JOIN shared_variables sv
      ON sv.project_id = e.project_id
     AND (sv.environment_id IS NULL OR sv.environment_id = e.id)
     AND sv.key = ANY (v.shared_refs)
    WHERE a.id = $1
      AND (a.env_applied_at IS NULL OR sv.updated_at > a.env_applied_at)
      AND (sv.environment_id IS NOT NULL OR NOT EXISTS (
          SELECT 1 FROM shared_variables sh
          WHERE sh.project_id = sv.project_id
            AND sh.environment_id = e.id
            AND sh.key = sv.key
      ))
) AS redeploy_pending
`

// ApplicationRedeployPending is the drift marker for one application (§5):
// some shared variable in its scope, named in one of its shared_refs, changed
// after the environment it is actually running was frozen onto the wire.
func (q *Queries) ApplicationRedeployPending(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, applicationRedeployPending, id)
	var redeploy_pending bool
	err := row.Scan(&redeploy_pending)
	return redeploy_pending, err
}

const applyDeploymentEnvStamp = `-- name: ApplyDeploymentEnvStamp :exec
UPDATE applications a
SET env_applied_at = d.env_resolved_at
FROM deployments d
WHERE d.id = $1
  AND a.id = d.application_id
  AND d.env_resolved_at IS NOT NULL
`

// ApplyDeploymentEnvStamp copies a deployment's env_resolved_at onto its
// application, and is called only when that deployment is OBSERVED running
// (§5) — which is what makes a failed deploy unable to mark an app clean.
func (q *Queries) ApplyDeploymentEnvStamp(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, applyDeploymentEnvStamp, id)
	return err
}

const countSharedVariableUsage = `-- name: CountSharedVariableUsage :one
SELECT COUNT(*)::bigint AS used_by_count
FROM applications a
JOIN environments e ON e.id = a.environment_id
JOIN shared_variables sv ON sv.id = $1
WHERE e.project_id = sv.project_id
  AND (sv.environment_id IS NULL OR e.id = sv.environment_id)
  AND EXISTS (
      SELECT 1 FROM app_env_vars v
      WHERE v.application_id = a.id AND sv.key = ANY (v.shared_refs)
  )
  AND (sv.environment_id IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM shared_variables sh
      WHERE sh.project_id = sv.project_id
        AND sh.environment_id = e.id
        AND sh.key = sv.key
  ))
`

func (q *Queries) CountSharedVariableUsage(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedVariableUsage, id)
	var used_by_count int64
	err := row.Scan(&used_by_count)
	return used_by_count, err
}

const countSharedVariableUsageByProject = `-- name: CountSharedVariableUsageByProject :many
SELECT sv.id, (
    SELECT COUNT(*)
    FROM applications a
    JOIN environments e ON e.id = a.environment_id
    WHERE e.project_id = sv.project_id
      AND (sv.environment_id IS NULL OR e.id = sv.environment_id)
      AND EXISTS (
          SELECT 1 FROM app_env_vars v
          WHERE v.application_id = a.id AND sv.key = ANY (v.shared_refs)
      )
      AND (sv.environment_id IS NOT NULL OR NOT EXISTS (
          SELECT 1 FROM shared_variables sh
          WHERE sh.project_id = sv.project_id
            AND sh.environment_id = e.id
            AND sh.key = sv.key
      ))
)::bigint AS used_by_count
FROM shared_variables sv
WHERE sv.project_id = $1
`

type CountSharedVariableUsageByProjectRow struct {
	ID          string
	UsedByCount int64
}

func (q *Queries) CountSharedVariableUsageByProject(ctx context.Context, projectID string) ([]CountSharedVariableUsageByProjectRow, error) {
	rows, err := q.db.Query(ctx, countSharedVariableUsageByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSharedVariableUsageByProjectRow{}
	for rows.Next() {
		var i CountSharedVariableUsageByProjectRow
		if err := rows.Scan(&i.ID, &i.UsedByCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSharedVariable = `-- name: CreateSharedVariable :one

INSERT INTO shared_variables (
    id, project_id, environment_id, key, value_ct, value_nonce
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, project_id, environment_id, key, value_ct, value_nonce, created_at, updated_at
`

type CreateSharedVariableParams struct {
	ID            string
	ProjectID     string
	EnvironmentID pgtype.Text
	Key           string
	ValueCt       []byte
	ValueNonce    []byte
}

// Project shared variables (shared-variables.md §2, §5, §7).
//
// Two ideas recur below and are worth reading once:
//
//	SHADOWING — a key resolves to the row scoped to the application's own
//	environment when one exists, otherwise the project-scoped row. In SQL that
//	is `DISTINCT ON (key) … ORDER BY key, (environment_id IS NOT NULL) DESC`:
//	TRUE sorts before FALSE, so the environment row wins.
//
//	SCOPE-ACCURATE USAGE — an application whose own environment defines a
//	shadowing row of the same key does NOT use the project-scoped variable, so
//	it is excluded from that variable's count and listing (§7).
func (q *Queries) CreateSharedVariable(ctx context.Context, arg CreateSharedVariableParams) (SharedVariable, error) {
	row := q.db.QueryRow(ctx, createSharedVariable,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Key,
		arg.ValueCt,
		arg.ValueNonce,
	)
	var i SharedVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Key,
		&i.ValueCt,
		&i.ValueNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSharedVariable = `-- name: DeleteSharedVariable :exec
DELETE FROM shared_variables WHERE id = $1
`

func (q *Queries) DeleteSharedVariable(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSharedVariable, id)
	return err
}

const getSharedVariable = `-- name: GetSharedVariable :one
SELECT id, project_id, environment_id, key, value_ct, value_nonce, created_at, updated_at FROM shared_variables WHERE id = $1
`

func (q *Queries) GetSharedVariable(ctx context.Context, id string) (SharedVariable, error) {
	row := q.db.QueryRow(ctx, getSharedVariable, id)
	var i SharedVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Key,
		&i.ValueCt,
		&i.ValueNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRedeployPendingApplications = `-- name: ListRedeployPendingApplications :many
SELECT DISTINCT a.id
FROM applications a
JOIN environments e ON e.id = a.environment_id
JOIN app_env_vars v ON v.application_id = a.id
JOIN shared_variables sv
  ON sv.project_id = e.project_id
 AND (sv.environment_id IS NULL OR sv.environment_id = e.id)
 AND sv.key = ANY (v.shared_refs)
WHERE a.environment_id = $1
  AND (a.env_applied_at IS NULL OR sv.updated_at > a.env_applied_at)
  AND (sv.environment_id IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM shared_variables sh
      WHERE sh.project_id = sv.project_id
        AND sh.environment_id = e.id
        AND sh.key = sv.key
  ))
`

// ListRedeployPendingApplications answers the same question for a whole
// environment in one query, so listing applications stays a fixed number of
// round trips rather than one per row.
func (q *Queries) ListRedeployPendingApplications(ctx context.Context, environmentID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRedeployPendingApplications, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariableKeysByProject = `-- name: ListSharedVariableKeysByProject :many
SELECT key, environment_id FROM shared_variables
WHERE project_id = $1
ORDER BY key, environment_id NULLS FIRST
`

type ListSharedVariableKeysByProjectRow struct {
	Key           string
	EnvironmentID pgtype.Text
}

// Keys and scope, never the sealed value — so core/export's Store interface
// can be structurally incapable of holding a ciphertext (project-export.md §4).
func (q *Queries) ListSharedVariableKeysByProject(ctx context.Context, projectID string) ([]ListSharedVariableKeysByProjectRow, error) {
	rows, err := q.db.Query(ctx, listSharedVariableKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedVariableKeysByProjectRow{}
	for rows.Next() {
		var i ListSharedVariableKeysByProjectRow
		if err := rows.Scan(&i.Key, &i.EnvironmentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariableKeysInScope = `-- name: ListSharedVariableKeysInScope :many
SELECT DISTINCT key
FROM shared_variables
WHERE project_id = $1
  AND (environment_id IS NULL OR environment_id = $2)
ORDER BY key
`

type ListSharedVariableKeysInScopeParams struct {
	ProjectID     string
	EnvironmentID pgtype.Text
}

// ListSharedVariableKeysInScope is the same resolution reduced to key names —
// what the write-time reference check reads (§3). Keys only: nothing unseals.
func (q *Queries) ListSharedVariableKeysInScope(ctx context.Context, arg ListSharedVariableKeysInScopeParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedVariableKeysInScope, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariableUsage = `-- name: ListSharedVariableUsage :many
SELECT a.id            AS application_id,
       a.name          AS application_name,
       e.name          AS environment_name,
       (a.env_applied_at IS NULL OR sv.updated_at > a.env_applied_at) AS redeploy_pending
FROM applications a
JOIN environments e ON e.id = a.environment_id
JOIN shared_variables sv ON sv.id = $1
WHERE e.project_id = sv.project_id
  AND (sv.environment_id IS NULL OR e.id = sv.environment_id)
  AND EXISTS (
      SELECT 1 FROM app_env_vars v
      WHERE v.application_id = a.id AND sv.key = ANY (v.shared_refs)
  )
  AND (sv.environment_id IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM shared_variables sh
      WHERE sh.project_id = sv.project_id
        AND sh.environment_id = e.id
        AND sh.key = sv.key
  ))
ORDER BY e.name, a.name
`

type ListSharedVariableUsageRow struct {
	ApplicationID   string
	ApplicationName string
	EnvironmentName string
	RedeployPending pgtype.Bool
}

// ListSharedVariableUsage names the applications that reference one variable,
// each with its own drift marker relative to THIS variable (§7). A NULL
// env_applied_at means the application has never had a resolved environment
// observed running, so the current value has never been applied — pending.
func (q *Queries) ListSharedVariableUsage(ctx context.Context, id string) ([]ListSharedVariableUsageRow, error) {
	rows, err := q.db.Query(ctx, listSharedVariableUsage, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedVariableUsageRow{}
	for rows.Next() {
		var i ListSharedVariableUsageRow
		if err := rows.Scan(
			&i.ApplicationID,
			&i.ApplicationName,
			&i.EnvironmentName,
			&i.RedeployPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariablesByProject = `-- name: ListSharedVariablesByProject :many
SELECT id, project_id, environment_id, key, value_ct, value_nonce, created_at, updated_at FROM shared_variables
WHERE project_id = $1
ORDER BY key, environment_id NULLS FIRST
`

func (q *Queries) ListSharedVariablesByProject(ctx context.Context, projectID string) ([]SharedVariable, error) {
	rows, err := q.db.Query(ctx, listSharedVariablesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedVariable{}
	for rows.Next() {
		var i SharedVariable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Key,
			&i.ValueCt,
			&i.ValueNonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedVariablesInScope = `-- name: ListSharedVariablesInScope :many
SELECT DISTINCT ON (key) id, project_id, environment_id, key, value_ct, value_nonce, created_at, updated_at
FROM shared_variables
WHERE project_id = $1
  AND (environment_id IS NULL OR environment_id = $2)
ORDER BY key, (environment_id IS NOT NULL) DESC
`

type ListSharedVariablesInScopeParams struct {
	ProjectID     string
	EnvironmentID pgtype.Text
}

// ListSharedVariablesInScope resolves the variables in force for one
// environment: project-scoped rows, with environment-scoped rows of the same key
// shadowing them. This is the scheduler's single resolution point (§4).
func (q *Queries) ListSharedVariablesInScope(ctx context.Context, arg ListSharedVariablesInScopeParams) ([]SharedVariable, error) {
	rows, err := q.db.Query(ctx, listSharedVariablesInScope, arg.ProjectID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedVariable{}
	for rows.Next() {
		var i SharedVariable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Key,
			&i.ValueCt,
			&i.ValueNonce,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeploymentEnvResolved = `-- name: SetDeploymentEnvResolved :exec
UPDATE deployments SET env_resolved_at = now() WHERE id = $1
`

// SetDeploymentEnvResolved stamps the instant buildSpec froze this rollout's
// environment onto the wire (§5). The stamp is the DATABASE's now(), not the
// caller's clock, because it is only ever compared against
// shared_variables.updated_at — also a database now(). Reading two clocks would
// make the drift marker wrong by exactly the skew between the plane and
// Postgres, in whichever direction happened to hide a needed redeploy.
func (q *Queries) SetDeploymentEnvResolved(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setDeploymentEnvResolved, id)
	return err
}

const updateSharedVariableValue = `-- name: UpdateSharedVariableValue :one
UPDATE shared_variables
SET value_ct = $2, value_nonce = $3, updated_at = now()
WHERE id = $1
RETURNING id, project_id, environment_id, key, value_ct, value_nonce, created_at, updated_at
`

type UpdateSharedVariableValueParams struct {
	ID         string
	ValueCt    []byte
	ValueNonce []byte
}

// UpdateSharedVariableValue is the ONLY mutation: key and environment_id are
// immutable after create, because changing either would silently re-point or
// orphan every referencing application (§7). updated_at always moves, even when
// the plaintext is unchanged — AES-GCM with a fresh nonce yields different
// ciphertext for identical plaintext, so comparing would mean unsealing on every
// write, and a redeploy marker that turns out to be a no-op is safe while a
// missed one is not (§5).
func (q *Queries) UpdateSharedVariableValue(ctx context.Context, arg UpdateSharedVariableValueParams) (SharedVariable, error) {
	row := q.db.QueryRow(ctx, updateSharedVariableValue, arg.ID, arg.ValueCt, arg.ValueNonce)
	var i SharedVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Key,
		&i.ValueCt,
		&i.ValueNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
