// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status_pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeStatusInterval = `-- name: CloseStatusInterval :exec
UPDATE status_intervals SET ended_at = $2 WHERE id = $1 AND ended_at IS NULL
`

type CloseStatusIntervalParams struct {
	ID      string
	EndedAt pgtype.Timestamptz
}

func (q *Queries) CloseStatusInterval(ctx context.Context, arg CloseStatusIntervalParams) error {
	_, err := q.db.Exec(ctx, closeStatusInterval, arg.ID, arg.EndedAt)
	return err
}

const createStatusPageComponent = `-- name: CreateStatusPageComponent :one
INSERT INTO status_page_components (id, status_page_id, resource_kind, resource_id, label, position)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (status_page_id, resource_kind, resource_id) DO UPDATE
SET label = EXCLUDED.label, position = EXCLUDED.position
RETURNING id, status_page_id, resource_kind, resource_id, label, position, tracking_since
`

type CreateStatusPageComponentParams struct {
	ID           string
	StatusPageID string
	ResourceKind string
	ResourceID   string
	Label        string
	Position     int32
}

func (q *Queries) CreateStatusPageComponent(ctx context.Context, arg CreateStatusPageComponentParams) (StatusPageComponent, error) {
	row := q.db.QueryRow(ctx, createStatusPageComponent,
		arg.ID,
		arg.StatusPageID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Label,
		arg.Position,
	)
	var i StatusPageComponent
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.Label,
		&i.Position,
		&i.TrackingSince,
	)
	return i, err
}

const deleteStatusIntervalsBefore = `-- name: DeleteStatusIntervalsBefore :exec
DELETE FROM status_intervals si
WHERE si.id IN (
    SELECT s2.id FROM status_intervals s2
    WHERE s2.ended_at IS NOT NULL AND s2.ended_at < $1
    LIMIT $2
)
`

type DeleteStatusIntervalsBeforeParams struct {
	EndedAt pgtype.Timestamptz
	Limit   int32
}

func (q *Queries) DeleteStatusIntervalsBefore(ctx context.Context, arg DeleteStatusIntervalsBeforeParams) error {
	_, err := q.db.Exec(ctx, deleteStatusIntervalsBefore, arg.EndedAt, arg.Limit)
	return err
}

const deleteStatusPage = `-- name: DeleteStatusPage :exec
DELETE FROM status_pages WHERE project_id = $1
`

func (q *Queries) DeleteStatusPage(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteStatusPage, projectID)
	return err
}

const deleteStatusPageComponentsNotIn = `-- name: DeleteStatusPageComponentsNotIn :exec
DELETE FROM status_page_components
WHERE status_page_id = $1 AND NOT (id = ANY($2::text[]))
`

type DeleteStatusPageComponentsNotInParams struct {
	StatusPageID string
	KeepIds      []string
}

func (q *Queries) DeleteStatusPageComponentsNotIn(ctx context.Context, arg DeleteStatusPageComponentsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteStatusPageComponentsNotIn, arg.StatusPageID, arg.KeepIds)
	return err
}

const getLastEvaluation = `-- name: GetLastEvaluation :one
SELECT id, evaluated_at FROM status_evaluations WHERE id = 'singleton'
`

func (q *Queries) GetLastEvaluation(ctx context.Context) (StatusEvaluation, error) {
	row := q.db.QueryRow(ctx, getLastEvaluation)
	var i StatusEvaluation
	err := row.Scan(&i.ID, &i.EvaluatedAt)
	return i, err
}

const getOpenStatusInterval = `-- name: GetOpenStatusInterval :one
SELECT id, component_id, state, started_at, ended_at, message FROM status_intervals WHERE component_id = $1 AND ended_at IS NULL
`

func (q *Queries) GetOpenStatusInterval(ctx context.Context, componentID string) (StatusInterval, error) {
	row := q.db.QueryRow(ctx, getOpenStatusInterval, componentID)
	var i StatusInterval
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Message,
	)
	return i, err
}

const getStatusInterval = `-- name: GetStatusInterval :one
SELECT id, component_id, state, started_at, ended_at, message FROM status_intervals WHERE id = $1
`

func (q *Queries) GetStatusInterval(ctx context.Context, id string) (StatusInterval, error) {
	row := q.db.QueryRow(ctx, getStatusInterval, id)
	var i StatusInterval
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Message,
	)
	return i, err
}

const getStatusPage = `-- name: GetStatusPage :one
SELECT id, project_id, slug, title, enabled, domain, https, route_server_id, created_at, updated_at FROM status_pages WHERE id = $1
`

func (q *Queries) GetStatusPage(ctx context.Context, id string) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPage, id)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.Domain,
		&i.Https,
		&i.RouteServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageByProject = `-- name: GetStatusPageByProject :one
SELECT id, project_id, slug, title, enabled, domain, https, route_server_id, created_at, updated_at FROM status_pages WHERE project_id = $1
`

func (q *Queries) GetStatusPageByProject(ctx context.Context, projectID string) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageByProject, projectID)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.Domain,
		&i.Https,
		&i.RouteServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT id, project_id, slug, title, enabled, domain, https, route_server_id, created_at, updated_at FROM status_pages WHERE slug = $1
`

func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.Domain,
		&i.Https,
		&i.RouteServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTrackedComponents = `-- name: ListAllTrackedComponents :many
SELECT c.id, c.status_page_id, c.resource_kind, c.resource_id, c.label, c.position, c.tracking_since FROM status_page_components c
JOIN status_pages p ON p.id = c.status_page_id
WHERE p.enabled = true
ORDER BY c.status_page_id, c.position
`

func (q *Queries) ListAllTrackedComponents(ctx context.Context) ([]StatusPageComponent, error) {
	rows, err := q.db.Query(ctx, listAllTrackedComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageComponent{}
	for rows.Next() {
		var i StatusPageComponent
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Label,
			&i.Position,
			&i.TrackingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledStatusPages = `-- name: ListEnabledStatusPages :many
SELECT id, project_id, slug, title, enabled, domain, https, route_server_id, created_at, updated_at FROM status_pages WHERE enabled = true ORDER BY slug
`

func (q *Queries) ListEnabledStatusPages(ctx context.Context) ([]StatusPage, error) {
	rows, err := q.db.Query(ctx, listEnabledStatusPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Enabled,
			&i.Domain,
			&i.Https,
			&i.RouteServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutableStatusPages = `-- name: ListRoutableStatusPages :many
SELECT id, project_id, slug, title, enabled, domain, https, route_server_id, created_at, updated_at FROM status_pages
WHERE enabled = true AND domain <> '' AND route_server_id IS NOT NULL
`

// Every enabled page with a domain and a serving node, for the desired-state
// build. A page with no route_server_id is served at the panel origin only.
func (q *Queries) ListRoutableStatusPages(ctx context.Context) ([]StatusPage, error) {
	rows, err := q.db.Query(ctx, listRoutableStatusPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Enabled,
			&i.Domain,
			&i.Https,
			&i.RouteServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusIntervalsSince = `-- name: ListStatusIntervalsSince :many
SELECT id, component_id, state, started_at, ended_at, message FROM status_intervals
WHERE component_id = $1 AND (ended_at IS NULL OR ended_at >= $2)
ORDER BY started_at
`

type ListStatusIntervalsSinceParams struct {
	ComponentID string
	EndedAt     pgtype.Timestamptz
}

// Intervals overlapping the window, for the bars and the uptime figure. An
// open interval (ended_at IS NULL) overlaps by definition.
func (q *Queries) ListStatusIntervalsSince(ctx context.Context, arg ListStatusIntervalsSinceParams) ([]StatusInterval, error) {
	rows, err := q.db.Query(ctx, listStatusIntervalsSince, arg.ComponentID, arg.EndedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusInterval{}
	for rows.Next() {
		var i StatusInterval
		if err := rows.Scan(
			&i.ID,
			&i.ComponentID,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageComponents = `-- name: ListStatusPageComponents :many
SELECT id, status_page_id, resource_kind, resource_id, label, position, tracking_since FROM status_page_components WHERE status_page_id = $1 ORDER BY position, id
`

func (q *Queries) ListStatusPageComponents(ctx context.Context, statusPageID string) ([]StatusPageComponent, error) {
	rows, err := q.db.Query(ctx, listStatusPageComponents, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageComponent{}
	for rows.Next() {
		var i StatusPageComponent
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.Label,
			&i.Position,
			&i.TrackingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openStatusInterval = `-- name: OpenStatusInterval :one
INSERT INTO status_intervals (id, component_id, state, started_at)
VALUES ($1, $2, $3, $4)
RETURNING id, component_id, state, started_at, ended_at, message
`

type OpenStatusIntervalParams struct {
	ID          string
	ComponentID string
	State       string
	StartedAt   pgtype.Timestamptz
}

func (q *Queries) OpenStatusInterval(ctx context.Context, arg OpenStatusIntervalParams) (StatusInterval, error) {
	row := q.db.QueryRow(ctx, openStatusInterval,
		arg.ID,
		arg.ComponentID,
		arg.State,
		arg.StartedAt,
	)
	var i StatusInterval
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Message,
	)
	return i, err
}

const setStatusIntervalMessage = `-- name: SetStatusIntervalMessage :exec
UPDATE status_intervals SET message = $2 WHERE id = $1
`

type SetStatusIntervalMessageParams struct {
	ID      string
	Message string
}

func (q *Queries) SetStatusIntervalMessage(ctx context.Context, arg SetStatusIntervalMessageParams) error {
	_, err := q.db.Exec(ctx, setStatusIntervalMessage, arg.ID, arg.Message)
	return err
}

const stampEvaluation = `-- name: StampEvaluation :exec
INSERT INTO status_evaluations (id, evaluated_at) VALUES ('singleton', $1)
ON CONFLICT (id) DO UPDATE SET evaluated_at = EXCLUDED.evaluated_at
`

func (q *Queries) StampEvaluation(ctx context.Context, evaluatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, stampEvaluation, evaluatedAt)
	return err
}

const upsertStatusPage = `-- name: UpsertStatusPage :one
INSERT INTO status_pages (id, project_id, slug, title, enabled, domain, https, route_server_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (project_id) DO UPDATE
SET slug = EXCLUDED.slug,
    title = EXCLUDED.title,
    enabled = EXCLUDED.enabled,
    domain = EXCLUDED.domain,
    https = EXCLUDED.https,
    route_server_id = EXCLUDED.route_server_id,
    updated_at = now()
RETURNING id, project_id, slug, title, enabled, domain, https, route_server_id, created_at, updated_at
`

type UpsertStatusPageParams struct {
	ID            string
	ProjectID     string
	Slug          string
	Title         string
	Enabled       bool
	Domain        string
	Https         bool
	RouteServerID pgtype.Text
}

func (q *Queries) UpsertStatusPage(ctx context.Context, arg UpsertStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, upsertStatusPage,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.Title,
		arg.Enabled,
		arg.Domain,
		arg.Https,
		arg.RouteServerID,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Enabled,
		&i.Domain,
		&i.Https,
		&i.RouteServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
