// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    id, endpoint_id, event_type, resource_kind, resource_id, resource_name,
    payload, status, attempt, next_attempt_at, redelivery_of
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, endpoint_id, event_type, resource_kind, resource_id, resource_name, payload, status, attempt, next_attempt_at, redelivery_of, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	ID            string
	EndpointID    string
	EventType     string
	ResourceKind  string
	ResourceID    string
	ResourceName  string
	Payload       string
	Status        string
	Attempt       int32
	NextAttemptAt pgtype.Timestamptz
	RedeliveryOf  pgtype.Text
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.ID,
		arg.EndpointID,
		arg.EventType,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ResourceName,
		arg.Payload,
		arg.Status,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.RedeliveryOf,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourceName,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.RedeliveryOf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookDeliveryAttempt = `-- name: CreateWebhookDeliveryAttempt :one
INSERT INTO webhook_delivery_attempts (
    delivery_id, attempt, response_status, duration_ms, error
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING delivery_id, attempt, response_status, duration_ms, error, at
`

type CreateWebhookDeliveryAttemptParams struct {
	DeliveryID     string
	Attempt        int32
	ResponseStatus pgtype.Int4
	DurationMs     int32
	Error          string
}

func (q *Queries) CreateWebhookDeliveryAttempt(ctx context.Context, arg CreateWebhookDeliveryAttemptParams) (WebhookDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createWebhookDeliveryAttempt,
		arg.DeliveryID,
		arg.Attempt,
		arg.ResponseStatus,
		arg.DurationMs,
		arg.Error,
	)
	var i WebhookDeliveryAttempt
	err := row.Scan(
		&i.DeliveryID,
		&i.Attempt,
		&i.ResponseStatus,
		&i.DurationMs,
		&i.Error,
		&i.At,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one

INSERT INTO webhook_endpoints (
    id, project_id, url, secret_ct, secret_nonce, events, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, project_id, url, secret_ct, secret_nonce, events, enabled, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ID          string
	ProjectID   string
	Url         string
	SecretCt    []byte
	SecretNonce []byte
	Events      []string
	Enabled     bool
}

// Outbound webhooks (outbound-webhooks.md §2, §4): endpoints, deliveries, and
// the per-attempt record.
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ID,
		arg.ProjectID,
		arg.Url,
		arg.SecretCt,
		arg.SecretNonce,
		arg.Events,
		arg.Enabled,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.SecretCt,
		&i.SecretNonce,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldWebhookDeliveries = `-- name: DeleteOldWebhookDeliveries :exec
DELETE FROM webhook_deliveries d
WHERE d.endpoint_id = $1
  AND d.id NOT IN (
      SELECT keep.id FROM webhook_deliveries keep
      WHERE keep.endpoint_id = $1
      ORDER BY keep.created_at DESC, keep.id DESC
      LIMIT $2
  )
`

type DeleteOldWebhookDeliveriesParams struct {
	EndpointID string
	Limit      int32
}

// DeleteOldWebhookDeliveries prunes the delivery log to the most recent keep
// rows per endpoint, attempts cascading (outbound-webhooks.md §6).
func (q *Queries) DeleteOldWebhookDeliveries(ctx context.Context, arg DeleteOldWebhookDeliveriesParams) error {
	_, err := q.db.Exec(ctx, deleteOldWebhookDeliveries, arg.EndpointID, arg.Limit)
	return err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, id)
	return err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, endpoint_id, event_type, resource_kind, resource_id, resource_name, payload, status, attempt, next_attempt_at, redelivery_of, created_at, updated_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourceName,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.RedeliveryOf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, project_id, url, secret_ct, secret_nonce, events, enabled, created_at, updated_at FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) GetWebhookEndpoint(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.SecretCt,
		&i.SecretNonce,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastWebhookDeliveryAt = `-- name: LastWebhookDeliveryAt :one
SELECT created_at FROM webhook_deliveries
WHERE endpoint_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) LastWebhookDeliveryAt(ctx context.Context, endpointID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastWebhookDeliveryAt, endpointID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT id, endpoint_id, event_type, resource_kind, resource_id, resource_name, payload, status, attempt, next_attempt_at, redelivery_of, created_at, updated_at FROM webhook_deliveries
WHERE status = 'pending' AND next_attempt_at IS NOT NULL AND next_attempt_at <= $1
ORDER BY next_attempt_at
LIMIT $2
`

type ListDueWebhookDeliveriesParams struct {
	NextAttemptAt pgtype.Timestamptz
	Limit         int32
}

func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, arg ListDueWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDueWebhookDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventType,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourceName,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.RedeliveryOf,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledWebhookEndpointsForEvent = `-- name: ListEnabledWebhookEndpointsForEvent :many
SELECT id, project_id, url, secret_ct, secret_nonce, events, enabled, created_at, updated_at FROM webhook_endpoints
WHERE project_id = $1 AND enabled = true AND $2::text = ANY(events)
ORDER BY created_at
`

type ListEnabledWebhookEndpointsForEventParams struct {
	ProjectID string
	EventType string
}

func (q *Queries) ListEnabledWebhookEndpointsForEvent(ctx context.Context, arg ListEnabledWebhookEndpointsForEventParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhookEndpointsForEvent, arg.ProjectID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.SecretCt,
			&i.SecretNonce,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestWebhookDeliveryAttempts = `-- name: ListLatestWebhookDeliveryAttempts :many
SELECT DISTINCT ON (delivery_id) delivery_id, attempt, response_status, duration_ms, error, at
FROM webhook_delivery_attempts
WHERE delivery_id = ANY($1::text[])
ORDER BY delivery_id, attempt DESC
`

// ListLatestWebhookDeliveryAttempts returns the most recent attempt for each of
// the given deliveries — what the feed reads its "200 - 84ms" from
// (outbound-webhooks.md section 7). It is a second query rather than a join on
// the paging queries so every column keeps the nullability its own table
// declares: a delivery with no attempt yet is simply absent from the result.
func (q *Queries) ListLatestWebhookDeliveryAttempts(ctx context.Context, deliveryIds []string) ([]WebhookDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listLatestWebhookDeliveryAttempts, deliveryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDeliveryAttempt{}
	for rows.Next() {
		var i WebhookDeliveryAttempt
		if err := rows.Scan(
			&i.DeliveryID,
			&i.Attempt,
			&i.ResponseStatus,
			&i.DurationMs,
			&i.Error,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTerminalWebhookDeliveryStatuses = `-- name: ListRecentTerminalWebhookDeliveryStatuses :many
SELECT status FROM webhook_deliveries
WHERE endpoint_id = $1 AND status <> 'pending'
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRecentTerminalWebhookDeliveryStatusesParams struct {
	EndpointID string
	Limit      int32
}

// ListRecentTerminalWebhookDeliveryStatuses feeds the derived Endpoint Health
// (outbound-webhooks.md §4) — newest first, pending rows excluded.
func (q *Queries) ListRecentTerminalWebhookDeliveryStatuses(ctx context.Context, arg ListRecentTerminalWebhookDeliveryStatusesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRecentTerminalWebhookDeliveryStatuses, arg.EndpointID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var status string
		if err := rows.Scan(&status); err != nil {
			return nil, err
		}
		items = append(items, status)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesBefore = `-- name: ListWebhookDeliveriesBefore :many
SELECT d.id, d.endpoint_id, d.event_type, d.resource_kind, d.resource_id, d.resource_name, d.payload, d.status, d.attempt, d.next_attempt_at, d.redelivery_of, d.created_at, d.updated_at FROM webhook_deliveries d
WHERE d.endpoint_id = $1
  AND (d.created_at, d.id) < (
      SELECT c.created_at, c.id FROM webhook_deliveries c WHERE c.id = $2
  )
ORDER BY d.created_at DESC, d.id DESC
LIMIT $3
`

type ListWebhookDeliveriesBeforeParams struct {
	EndpointID string
	ID         string
	Limit      int32
}

// ListWebhookDeliveriesBefore is the seek page (outbound-webhooks.md §7):
// everything strictly older than the cursor row on (created_at, id) DESC. An
// unknown or already-pruned cursor makes the row comparison NULL, so the page
// comes back empty rather than restarting at the newest row.
func (q *Queries) ListWebhookDeliveriesBefore(ctx context.Context, arg ListWebhookDeliveriesBeforeParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesBefore, arg.EndpointID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventType,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourceName,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.RedeliveryOf,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByEndpoint = `-- name: ListWebhookDeliveriesByEndpoint :many
SELECT d.id, d.endpoint_id, d.event_type, d.resource_kind, d.resource_id, d.resource_name, d.payload, d.status, d.attempt, d.next_attempt_at, d.redelivery_of, d.created_at, d.updated_at FROM webhook_deliveries d
WHERE d.endpoint_id = $1
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListWebhookDeliveriesByEndpointParams struct {
	EndpointID string
	Limit      int32
}

func (q *Queries) ListWebhookDeliveriesByEndpoint(ctx context.Context, arg ListWebhookDeliveriesByEndpointParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByEndpoint, arg.EndpointID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventType,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ResourceName,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.RedeliveryOf,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveryAttempts = `-- name: ListWebhookDeliveryAttempts :many
SELECT delivery_id, attempt, response_status, duration_ms, error, at FROM webhook_delivery_attempts WHERE delivery_id = $1 ORDER BY attempt
`

func (q *Queries) ListWebhookDeliveryAttempts(ctx context.Context, deliveryID string) ([]WebhookDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveryAttempts, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDeliveryAttempt{}
	for rows.Next() {
		var i WebhookDeliveryAttempt
		if err := rows.Scan(
			&i.DeliveryID,
			&i.Attempt,
			&i.ResponseStatus,
			&i.DurationMs,
			&i.Error,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsByProject = `-- name: ListWebhookEndpointsByProject :many
SELECT id, project_id, url, secret_ct, secret_nonce, events, enabled, created_at, updated_at FROM webhook_endpoints WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpointsByProject(ctx context.Context, projectID string) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.SecretCt,
			&i.SecretNonce,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateWebhookEndpointSecret = `-- name: RotateWebhookEndpointSecret :one
UPDATE webhook_endpoints
SET secret_ct = $2, secret_nonce = $3, updated_at = now()
WHERE id = $1
RETURNING id, project_id, url, secret_ct, secret_nonce, events, enabled, created_at, updated_at
`

type RotateWebhookEndpointSecretParams struct {
	ID          string
	SecretCt    []byte
	SecretNonce []byte
}

func (q *Queries) RotateWebhookEndpointSecret(ctx context.Context, arg RotateWebhookEndpointSecretParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, rotateWebhookEndpointSecret, arg.ID, arg.SecretCt, arg.SecretNonce)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.SecretCt,
		&i.SecretNonce,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookDeliveryProgress = `-- name: UpdateWebhookDeliveryProgress :one
UPDATE webhook_deliveries
SET status = $2, attempt = $3, next_attempt_at = $4, updated_at = now()
WHERE id = $1 AND attempt = $5
RETURNING id, endpoint_id, event_type, resource_kind, resource_id, resource_name, payload, status, attempt, next_attempt_at, redelivery_of, created_at, updated_at
`

type UpdateWebhookDeliveryProgressParams struct {
	ID            string
	Status        string
	Attempt       int32
	NextAttemptAt pgtype.Timestamptz
	FromAttempt   int32
}

// UpdateWebhookDeliveryProgress advances a delivery, but only from the attempt
// the caller actually started from: `from_attempt` is a compare-and-set, not a
// filter. Two workers can hold the same row — the detached first attempt and a
// sweeper tick that finds it due — and without this guard the slower one's
// write lands last and wins, flipping a delivery that already succeeded back to
// pending for another round of retries. Matching zero rows is the correct
// answer for the loser: someone else moved this delivery on.
func (q *Queries) UpdateWebhookDeliveryProgress(ctx context.Context, arg UpdateWebhookDeliveryProgressParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, updateWebhookDeliveryProgress,
		arg.ID,
		arg.Status,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.FromAttempt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ResourceName,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.RedeliveryOf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints
SET url = $2, events = $3, enabled = $4, updated_at = now()
WHERE id = $1
RETURNING id, project_id, url, secret_ct, secret_nonce, events, enabled, created_at, updated_at
`

type UpdateWebhookEndpointParams struct {
	ID      string
	Url     string
	Events  []string
	Enabled bool
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.ID,
		arg.Url,
		arg.Events,
		arg.Enabled,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.SecretCt,
		&i.SecretNonce,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
