/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppServersIndexRouteImport } from './routes/_app/servers/index'
import { Route as AppServersServerIdRouteImport } from './routes/_app/servers/$serverId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppSettingsBackupTargetsRouteImport } from './routes/_app/settings/backup-targets'
import { Route as AppSettingsDeployKeysRouteImport } from './routes/_app/settings/deploy-keys'
import { Route as AppSettingsDnsRouteImport } from './routes/_app/settings/dns'
import { Route as AppSettingsMailRouteImport } from './routes/_app/settings/mail'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsRegistriesRouteImport } from './routes/_app/settings/registries'
import { Route as AppSettingsTeamsRouteImport } from './routes/_app/settings/teams'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app/projects/$projectId/settings'
import { Route as AppProjectsProjectIdApplicationsAppIdRouteImport } from './routes/_app/projects/$projectId/applications/$appId'
import { Route as AppProjectsProjectIdComposeStackIdRouteImport } from './routes/_app/projects/$projectId/compose/$stackId'
import { Route as AppProjectsProjectIdDatabasesDbIdRouteImport } from './routes/_app/projects/$projectId/databases/$dbId'
import { Route as AppProjectsProjectIdSettingsIndexRouteImport } from './routes/_app/projects/$projectId/settings/index'
import { Route as AppProjectsProjectIdSettingsNotifiersRouteImport } from './routes/_app/projects/$projectId/settings/notifiers'
import { Route as AppProjectsProjectIdSettingsProtectionRouteImport } from './routes/_app/projects/$projectId/settings/protection'
import { Route as AppProjectsProjectIdSettingsSharedVariablesRouteImport } from './routes/_app/projects/$projectId/settings/shared-variables'
import { Route as AppProjectsProjectIdSettingsWebhooksRouteImport } from './routes/_app/projects/$projectId/settings/webhooks'
import { Route as AppProjectsProjectIdApplicationsAppIdIndexRouteImport } from './routes/_app/projects/$projectId/applications/$appId/index'
import { Route as AppProjectsProjectIdApplicationsAppIdDeploymentsRouteImport } from './routes/_app/projects/$projectId/applications/$appId/deployments'
import { Route as AppProjectsProjectIdApplicationsAppIdEnvRouteImport } from './routes/_app/projects/$projectId/applications/$appId/env'
import { Route as AppProjectsProjectIdApplicationsAppIdLogsRouteImport } from './routes/_app/projects/$projectId/applications/$appId/logs'
import { Route as AppProjectsProjectIdApplicationsAppIdPreviewsRouteImport } from './routes/_app/projects/$projectId/applications/$appId/previews'
import { Route as AppProjectsProjectIdApplicationsAppIdSettingsRouteImport } from './routes/_app/projects/$projectId/applications/$appId/settings'
import { Route as AppProjectsProjectIdApplicationsAppIdStorageRouteImport } from './routes/_app/projects/$projectId/applications/$appId/storage'
import { Route as AppProjectsProjectIdApplicationsAppIdTasksRouteImport } from './routes/_app/projects/$projectId/applications/$appId/tasks'
import { Route as AppProjectsProjectIdComposeStackIdIndexRouteImport } from './routes/_app/projects/$projectId/compose/$stackId/index'
import { Route as AppProjectsProjectIdComposeStackIdEnvRouteImport } from './routes/_app/projects/$projectId/compose/$stackId/env'
import { Route as AppProjectsProjectIdComposeStackIdLogsRouteImport } from './routes/_app/projects/$projectId/compose/$stackId/logs'
import { Route as AppProjectsProjectIdComposeStackIdRevisionsRouteImport } from './routes/_app/projects/$projectId/compose/$stackId/revisions'
import { Route as AppProjectsProjectIdComposeStackIdSettingsRouteImport } from './routes/_app/projects/$projectId/compose/$stackId/settings'
import { Route as AppProjectsProjectIdDatabasesDbIdIndexRouteImport } from './routes/_app/projects/$projectId/databases/$dbId/index'
import { Route as AppProjectsProjectIdDatabasesDbIdBackupsRouteImport } from './routes/_app/projects/$projectId/databases/$dbId/backups'
import { Route as AppProjectsProjectIdDatabasesDbIdConnectionRouteImport } from './routes/_app/projects/$projectId/databases/$dbId/connection'
import { Route as AppProjectsProjectIdDatabasesDbIdSettingsRouteImport } from './routes/_app/projects/$projectId/databases/$dbId/settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppServersIndexRoute = AppServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AppRoute,
} as any)
const AppServersServerIdRoute = AppServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBackupTargetsRoute =
  AppSettingsBackupTargetsRouteImport.update({
    id: '/backup-targets',
    path: '/backup-targets',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsDeployKeysRoute = AppSettingsDeployKeysRouteImport.update({
  id: '/deploy-keys',
  path: '/deploy-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDnsRoute = AppSettingsDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMailRoute = AppSettingsMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsRegistriesRoute = AppSettingsRegistriesRouteImport.update({
  id: '/registries',
  path: '/registries',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTeamsRoute = AppSettingsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdRoute =
  AppProjectsProjectIdApplicationsAppIdRouteImport.update({
    id: '/projects/$projectId/applications/$appId',
    path: '/projects/$projectId/applications/$appId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdComposeStackIdRoute =
  AppProjectsProjectIdComposeStackIdRouteImport.update({
    id: '/projects/$projectId/compose/$stackId',
    path: '/projects/$projectId/compose/$stackId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdDatabasesDbIdRoute =
  AppProjectsProjectIdDatabasesDbIdRouteImport.update({
    id: '/projects/$projectId/databases/$dbId',
    path: '/projects/$projectId/databases/$dbId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdSettingsIndexRoute =
  AppProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdSettingsRoute,
  } as any)
const AppProjectsProjectIdSettingsNotifiersRoute =
  AppProjectsProjectIdSettingsNotifiersRouteImport.update({
    id: '/notifiers',
    path: '/notifiers',
    getParentRoute: () => AppProjectsProjectIdSettingsRoute,
  } as any)
const AppProjectsProjectIdSettingsProtectionRoute =
  AppProjectsProjectIdSettingsProtectionRouteImport.update({
    id: '/protection',
    path: '/protection',
    getParentRoute: () => AppProjectsProjectIdSettingsRoute,
  } as any)
const AppProjectsProjectIdSettingsSharedVariablesRoute =
  AppProjectsProjectIdSettingsSharedVariablesRouteImport.update({
    id: '/shared-variables',
    path: '/shared-variables',
    getParentRoute: () => AppProjectsProjectIdSettingsRoute,
  } as any)
const AppProjectsProjectIdSettingsWebhooksRoute =
  AppProjectsProjectIdSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AppProjectsProjectIdSettingsRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdIndexRoute =
  AppProjectsProjectIdApplicationsAppIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdDeploymentsRoute =
  AppProjectsProjectIdApplicationsAppIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdEnvRoute =
  AppProjectsProjectIdApplicationsAppIdEnvRouteImport.update({
    id: '/env',
    path: '/env',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdLogsRoute =
  AppProjectsProjectIdApplicationsAppIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdPreviewsRoute =
  AppProjectsProjectIdApplicationsAppIdPreviewsRouteImport.update({
    id: '/previews',
    path: '/previews',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdSettingsRoute =
  AppProjectsProjectIdApplicationsAppIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdStorageRoute =
  AppProjectsProjectIdApplicationsAppIdStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdTasksRoute =
  AppProjectsProjectIdApplicationsAppIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdComposeStackIdIndexRoute =
  AppProjectsProjectIdComposeStackIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdComposeStackIdRoute,
  } as any)
const AppProjectsProjectIdComposeStackIdEnvRoute =
  AppProjectsProjectIdComposeStackIdEnvRouteImport.update({
    id: '/env',
    path: '/env',
    getParentRoute: () => AppProjectsProjectIdComposeStackIdRoute,
  } as any)
const AppProjectsProjectIdComposeStackIdLogsRoute =
  AppProjectsProjectIdComposeStackIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsProjectIdComposeStackIdRoute,
  } as any)
const AppProjectsProjectIdComposeStackIdRevisionsRoute =
  AppProjectsProjectIdComposeStackIdRevisionsRouteImport.update({
    id: '/revisions',
    path: '/revisions',
    getParentRoute: () => AppProjectsProjectIdComposeStackIdRoute,
  } as any)
const AppProjectsProjectIdComposeStackIdSettingsRoute =
  AppProjectsProjectIdComposeStackIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdComposeStackIdRoute,
  } as any)
const AppProjectsProjectIdDatabasesDbIdIndexRoute =
  AppProjectsProjectIdDatabasesDbIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdDatabasesDbIdRoute,
  } as any)
const AppProjectsProjectIdDatabasesDbIdBackupsRoute =
  AppProjectsProjectIdDatabasesDbIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AppProjectsProjectIdDatabasesDbIdRoute,
  } as any)
const AppProjectsProjectIdDatabasesDbIdConnectionRoute =
  AppProjectsProjectIdDatabasesDbIdConnectionRouteImport.update({
    id: '/connection',
    path: '/connection',
    getParentRoute: () => AppProjectsProjectIdDatabasesDbIdRoute,
  } as any)
const AppProjectsProjectIdDatabasesDbIdSettingsRoute =
  AppProjectsProjectIdDatabasesDbIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdDatabasesDbIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/backup-targets': typeof AppSettingsBackupTargetsRoute
  '/settings/deploy-keys': typeof AppSettingsDeployKeysRoute
  '/settings/dns': typeof AppSettingsDnsRoute
  '/settings/mail': typeof AppSettingsMailRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/registries': typeof AppSettingsRegistriesRoute
  '/settings/teams': typeof AppSettingsTeamsRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/servers/': typeof AppServersIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRouteWithChildren
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/applications/$appId': typeof AppProjectsProjectIdApplicationsAppIdRouteWithChildren
  '/projects/$projectId/compose/$stackId': typeof AppProjectsProjectIdComposeStackIdRouteWithChildren
  '/projects/$projectId/databases/$dbId': typeof AppProjectsProjectIdDatabasesDbIdRouteWithChildren
  '/projects/$projectId/settings/notifiers': typeof AppProjectsProjectIdSettingsNotifiersRoute
  '/projects/$projectId/settings/protection': typeof AppProjectsProjectIdSettingsProtectionRoute
  '/projects/$projectId/settings/shared-variables': typeof AppProjectsProjectIdSettingsSharedVariablesRoute
  '/projects/$projectId/settings/webhooks': typeof AppProjectsProjectIdSettingsWebhooksRoute
  '/projects/$projectId/settings/': typeof AppProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/applications/$appId/deployments': typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  '/projects/$projectId/applications/$appId/env': typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  '/projects/$projectId/applications/$appId/logs': typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  '/projects/$projectId/applications/$appId/previews': typeof AppProjectsProjectIdApplicationsAppIdPreviewsRoute
  '/projects/$projectId/applications/$appId/settings': typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  '/projects/$projectId/applications/$appId/storage': typeof AppProjectsProjectIdApplicationsAppIdStorageRoute
  '/projects/$projectId/applications/$appId/tasks': typeof AppProjectsProjectIdApplicationsAppIdTasksRoute
  '/projects/$projectId/compose/$stackId/env': typeof AppProjectsProjectIdComposeStackIdEnvRoute
  '/projects/$projectId/compose/$stackId/logs': typeof AppProjectsProjectIdComposeStackIdLogsRoute
  '/projects/$projectId/compose/$stackId/revisions': typeof AppProjectsProjectIdComposeStackIdRevisionsRoute
  '/projects/$projectId/compose/$stackId/settings': typeof AppProjectsProjectIdComposeStackIdSettingsRoute
  '/projects/$projectId/databases/$dbId/backups': typeof AppProjectsProjectIdDatabasesDbIdBackupsRoute
  '/projects/$projectId/databases/$dbId/connection': typeof AppProjectsProjectIdDatabasesDbIdConnectionRoute
  '/projects/$projectId/databases/$dbId/settings': typeof AppProjectsProjectIdDatabasesDbIdSettingsRoute
  '/projects/$projectId/applications/$appId/': typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
  '/projects/$projectId/compose/$stackId/': typeof AppProjectsProjectIdComposeStackIdIndexRoute
  '/projects/$projectId/databases/$dbId/': typeof AppProjectsProjectIdDatabasesDbIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/': typeof AppIndexRoute
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/backup-targets': typeof AppSettingsBackupTargetsRoute
  '/settings/deploy-keys': typeof AppSettingsDeployKeysRoute
  '/settings/dns': typeof AppSettingsDnsRoute
  '/settings/mail': typeof AppSettingsMailRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/registries': typeof AppSettingsRegistriesRoute
  '/settings/teams': typeof AppSettingsTeamsRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/projects': typeof AppProjectsIndexRoute
  '/servers': typeof AppServersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/settings/notifiers': typeof AppProjectsProjectIdSettingsNotifiersRoute
  '/projects/$projectId/settings/protection': typeof AppProjectsProjectIdSettingsProtectionRoute
  '/projects/$projectId/settings/shared-variables': typeof AppProjectsProjectIdSettingsSharedVariablesRoute
  '/projects/$projectId/settings/webhooks': typeof AppProjectsProjectIdSettingsWebhooksRoute
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/applications/$appId/deployments': typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  '/projects/$projectId/applications/$appId/env': typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  '/projects/$projectId/applications/$appId/logs': typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  '/projects/$projectId/applications/$appId/previews': typeof AppProjectsProjectIdApplicationsAppIdPreviewsRoute
  '/projects/$projectId/applications/$appId/settings': typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  '/projects/$projectId/applications/$appId/storage': typeof AppProjectsProjectIdApplicationsAppIdStorageRoute
  '/projects/$projectId/applications/$appId/tasks': typeof AppProjectsProjectIdApplicationsAppIdTasksRoute
  '/projects/$projectId/compose/$stackId/env': typeof AppProjectsProjectIdComposeStackIdEnvRoute
  '/projects/$projectId/compose/$stackId/logs': typeof AppProjectsProjectIdComposeStackIdLogsRoute
  '/projects/$projectId/compose/$stackId/revisions': typeof AppProjectsProjectIdComposeStackIdRevisionsRoute
  '/projects/$projectId/compose/$stackId/settings': typeof AppProjectsProjectIdComposeStackIdSettingsRoute
  '/projects/$projectId/databases/$dbId/backups': typeof AppProjectsProjectIdDatabasesDbIdBackupsRoute
  '/projects/$projectId/databases/$dbId/connection': typeof AppProjectsProjectIdDatabasesDbIdConnectionRoute
  '/projects/$projectId/databases/$dbId/settings': typeof AppProjectsProjectIdDatabasesDbIdSettingsRoute
  '/projects/$projectId/applications/$appId': typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
  '/projects/$projectId/compose/$stackId': typeof AppProjectsProjectIdComposeStackIdIndexRoute
  '/projects/$projectId/databases/$dbId': typeof AppProjectsProjectIdDatabasesDbIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/servers/$serverId': typeof AppServersServerIdRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/backup-targets': typeof AppSettingsBackupTargetsRoute
  '/_app/settings/deploy-keys': typeof AppSettingsDeployKeysRoute
  '/_app/settings/dns': typeof AppSettingsDnsRoute
  '/_app/settings/mail': typeof AppSettingsMailRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/registries': typeof AppSettingsRegistriesRoute
  '/_app/settings/teams': typeof AppSettingsTeamsRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/servers/': typeof AppServersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRouteWithChildren
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/applications/$appId': typeof AppProjectsProjectIdApplicationsAppIdRouteWithChildren
  '/_app/projects/$projectId/compose/$stackId': typeof AppProjectsProjectIdComposeStackIdRouteWithChildren
  '/_app/projects/$projectId/databases/$dbId': typeof AppProjectsProjectIdDatabasesDbIdRouteWithChildren
  '/_app/projects/$projectId/settings/notifiers': typeof AppProjectsProjectIdSettingsNotifiersRoute
  '/_app/projects/$projectId/settings/protection': typeof AppProjectsProjectIdSettingsProtectionRoute
  '/_app/projects/$projectId/settings/shared-variables': typeof AppProjectsProjectIdSettingsSharedVariablesRoute
  '/_app/projects/$projectId/settings/webhooks': typeof AppProjectsProjectIdSettingsWebhooksRoute
  '/_app/projects/$projectId/settings/': typeof AppProjectsProjectIdSettingsIndexRoute
  '/_app/projects/$projectId/applications/$appId/deployments': typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  '/_app/projects/$projectId/applications/$appId/env': typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  '/_app/projects/$projectId/applications/$appId/logs': typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  '/_app/projects/$projectId/applications/$appId/previews': typeof AppProjectsProjectIdApplicationsAppIdPreviewsRoute
  '/_app/projects/$projectId/applications/$appId/settings': typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  '/_app/projects/$projectId/applications/$appId/storage': typeof AppProjectsProjectIdApplicationsAppIdStorageRoute
  '/_app/projects/$projectId/applications/$appId/tasks': typeof AppProjectsProjectIdApplicationsAppIdTasksRoute
  '/_app/projects/$projectId/compose/$stackId/env': typeof AppProjectsProjectIdComposeStackIdEnvRoute
  '/_app/projects/$projectId/compose/$stackId/logs': typeof AppProjectsProjectIdComposeStackIdLogsRoute
  '/_app/projects/$projectId/compose/$stackId/revisions': typeof AppProjectsProjectIdComposeStackIdRevisionsRoute
  '/_app/projects/$projectId/compose/$stackId/settings': typeof AppProjectsProjectIdComposeStackIdSettingsRoute
  '/_app/projects/$projectId/databases/$dbId/backups': typeof AppProjectsProjectIdDatabasesDbIdBackupsRoute
  '/_app/projects/$projectId/databases/$dbId/connection': typeof AppProjectsProjectIdDatabasesDbIdConnectionRoute
  '/_app/projects/$projectId/databases/$dbId/settings': typeof AppProjectsProjectIdDatabasesDbIdSettingsRoute
  '/_app/projects/$projectId/applications/$appId/': typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
  '/_app/projects/$projectId/compose/$stackId/': typeof AppProjectsProjectIdComposeStackIdIndexRoute
  '/_app/projects/$projectId/databases/$dbId/': typeof AppProjectsProjectIdDatabasesDbIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inbox'
    | '/settings'
    | '/servers/$serverId'
    | '/settings/audit'
    | '/settings/backup-targets'
    | '/settings/deploy-keys'
    | '/settings/dns'
    | '/settings/mail'
    | '/settings/profile'
    | '/settings/registries'
    | '/settings/teams'
    | '/settings/users'
    | '/projects/'
    | '/servers/'
    | '/settings/'
    | '/templates/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/applications/$appId'
    | '/projects/$projectId/compose/$stackId'
    | '/projects/$projectId/databases/$dbId'
    | '/projects/$projectId/settings/notifiers'
    | '/projects/$projectId/settings/protection'
    | '/projects/$projectId/settings/shared-variables'
    | '/projects/$projectId/settings/webhooks'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/applications/$appId/deployments'
    | '/projects/$projectId/applications/$appId/env'
    | '/projects/$projectId/applications/$appId/logs'
    | '/projects/$projectId/applications/$appId/previews'
    | '/projects/$projectId/applications/$appId/settings'
    | '/projects/$projectId/applications/$appId/storage'
    | '/projects/$projectId/applications/$appId/tasks'
    | '/projects/$projectId/compose/$stackId/env'
    | '/projects/$projectId/compose/$stackId/logs'
    | '/projects/$projectId/compose/$stackId/revisions'
    | '/projects/$projectId/compose/$stackId/settings'
    | '/projects/$projectId/databases/$dbId/backups'
    | '/projects/$projectId/databases/$dbId/connection'
    | '/projects/$projectId/databases/$dbId/settings'
    | '/projects/$projectId/applications/$appId/'
    | '/projects/$projectId/compose/$stackId/'
    | '/projects/$projectId/databases/$dbId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/inbox'
    | '/'
    | '/servers/$serverId'
    | '/settings/audit'
    | '/settings/backup-targets'
    | '/settings/deploy-keys'
    | '/settings/dns'
    | '/settings/mail'
    | '/settings/profile'
    | '/settings/registries'
    | '/settings/teams'
    | '/settings/users'
    | '/projects'
    | '/servers'
    | '/settings'
    | '/templates'
    | '/projects/$projectId'
    | '/projects/$projectId/settings/notifiers'
    | '/projects/$projectId/settings/protection'
    | '/projects/$projectId/settings/shared-variables'
    | '/projects/$projectId/settings/webhooks'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/applications/$appId/deployments'
    | '/projects/$projectId/applications/$appId/env'
    | '/projects/$projectId/applications/$appId/logs'
    | '/projects/$projectId/applications/$appId/previews'
    | '/projects/$projectId/applications/$appId/settings'
    | '/projects/$projectId/applications/$appId/storage'
    | '/projects/$projectId/applications/$appId/tasks'
    | '/projects/$projectId/compose/$stackId/env'
    | '/projects/$projectId/compose/$stackId/logs'
    | '/projects/$projectId/compose/$stackId/revisions'
    | '/projects/$projectId/compose/$stackId/settings'
    | '/projects/$projectId/databases/$dbId/backups'
    | '/projects/$projectId/databases/$dbId/connection'
    | '/projects/$projectId/databases/$dbId/settings'
    | '/projects/$projectId/applications/$appId'
    | '/projects/$projectId/compose/$stackId'
    | '/projects/$projectId/databases/$dbId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/inbox'
    | '/_app/settings'
    | '/_app/'
    | '/_app/servers/$serverId'
    | '/_app/settings/audit'
    | '/_app/settings/backup-targets'
    | '/_app/settings/deploy-keys'
    | '/_app/settings/dns'
    | '/_app/settings/mail'
    | '/_app/settings/profile'
    | '/_app/settings/registries'
    | '/_app/settings/teams'
    | '/_app/settings/users'
    | '/_app/projects/'
    | '/_app/servers/'
    | '/_app/settings/'
    | '/_app/templates/'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/applications/$appId'
    | '/_app/projects/$projectId/compose/$stackId'
    | '/_app/projects/$projectId/databases/$dbId'
    | '/_app/projects/$projectId/settings/notifiers'
    | '/_app/projects/$projectId/settings/protection'
    | '/_app/projects/$projectId/settings/shared-variables'
    | '/_app/projects/$projectId/settings/webhooks'
    | '/_app/projects/$projectId/settings/'
    | '/_app/projects/$projectId/applications/$appId/deployments'
    | '/_app/projects/$projectId/applications/$appId/env'
    | '/_app/projects/$projectId/applications/$appId/logs'
    | '/_app/projects/$projectId/applications/$appId/previews'
    | '/_app/projects/$projectId/applications/$appId/settings'
    | '/_app/projects/$projectId/applications/$appId/storage'
    | '/_app/projects/$projectId/applications/$appId/tasks'
    | '/_app/projects/$projectId/compose/$stackId/env'
    | '/_app/projects/$projectId/compose/$stackId/logs'
    | '/_app/projects/$projectId/compose/$stackId/revisions'
    | '/_app/projects/$projectId/compose/$stackId/settings'
    | '/_app/projects/$projectId/databases/$dbId/backups'
    | '/_app/projects/$projectId/databases/$dbId/connection'
    | '/_app/projects/$projectId/databases/$dbId/settings'
    | '/_app/projects/$projectId/applications/$appId/'
    | '/_app/projects/$projectId/compose/$stackId/'
    | '/_app/projects/$projectId/databases/$dbId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/': {
      id: '/_app/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AppServersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$serverId': {
      id: '/_app/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AppServersServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/backup-targets': {
      id: '/_app/settings/backup-targets'
      path: '/backup-targets'
      fullPath: '/settings/backup-targets'
      preLoaderRoute: typeof AppSettingsBackupTargetsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/deploy-keys': {
      id: '/_app/settings/deploy-keys'
      path: '/deploy-keys'
      fullPath: '/settings/deploy-keys'
      preLoaderRoute: typeof AppSettingsDeployKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/dns': {
      id: '/_app/settings/dns'
      path: '/dns'
      fullPath: '/settings/dns'
      preLoaderRoute: typeof AppSettingsDnsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/mail': {
      id: '/_app/settings/mail'
      path: '/mail'
      fullPath: '/settings/mail'
      preLoaderRoute: typeof AppSettingsMailRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/registries': {
      id: '/_app/settings/registries'
      path: '/registries'
      fullPath: '/settings/registries'
      preLoaderRoute: typeof AppSettingsRegistriesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/teams': {
      id: '/_app/settings/teams'
      path: '/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof AppSettingsTeamsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/applications/$appId': {
      id: '/_app/projects/$projectId/applications/$appId'
      path: '/projects/$projectId/applications/$appId'
      fullPath: '/projects/$projectId/applications/$appId'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/compose/$stackId': {
      id: '/_app/projects/$projectId/compose/$stackId'
      path: '/projects/$projectId/compose/$stackId'
      fullPath: '/projects/$projectId/compose/$stackId'
      preLoaderRoute: typeof AppProjectsProjectIdComposeStackIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/databases/$dbId': {
      id: '/_app/projects/$projectId/databases/$dbId'
      path: '/projects/$projectId/databases/$dbId'
      fullPath: '/projects/$projectId/databases/$dbId'
      preLoaderRoute: typeof AppProjectsProjectIdDatabasesDbIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/settings/': {
      id: '/_app/projects/$projectId/settings/'
      path: '/'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdSettingsRoute
    }
    '/_app/projects/$projectId/settings/notifiers': {
      id: '/_app/projects/$projectId/settings/notifiers'
      path: '/notifiers'
      fullPath: '/projects/$projectId/settings/notifiers'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsNotifiersRouteImport
      parentRoute: typeof AppProjectsProjectIdSettingsRoute
    }
    '/_app/projects/$projectId/settings/protection': {
      id: '/_app/projects/$projectId/settings/protection'
      path: '/protection'
      fullPath: '/projects/$projectId/settings/protection'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsProtectionRouteImport
      parentRoute: typeof AppProjectsProjectIdSettingsRoute
    }
    '/_app/projects/$projectId/settings/shared-variables': {
      id: '/_app/projects/$projectId/settings/shared-variables'
      path: '/shared-variables'
      fullPath: '/projects/$projectId/settings/shared-variables'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsSharedVariablesRouteImport
      parentRoute: typeof AppProjectsProjectIdSettingsRoute
    }
    '/_app/projects/$projectId/settings/webhooks': {
      id: '/_app/projects/$projectId/settings/webhooks'
      path: '/webhooks'
      fullPath: '/projects/$projectId/settings/webhooks'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsWebhooksRouteImport
      parentRoute: typeof AppProjectsProjectIdSettingsRoute
    }
    '/_app/projects/$projectId/applications/$appId/': {
      id: '/_app/projects/$projectId/applications/$appId/'
      path: '/'
      fullPath: '/projects/$projectId/applications/$appId/'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/deployments': {
      id: '/_app/projects/$projectId/applications/$appId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/applications/$appId/deployments'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/env': {
      id: '/_app/projects/$projectId/applications/$appId/env'
      path: '/env'
      fullPath: '/projects/$projectId/applications/$appId/env'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdEnvRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/logs': {
      id: '/_app/projects/$projectId/applications/$appId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/applications/$appId/logs'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/previews': {
      id: '/_app/projects/$projectId/applications/$appId/previews'
      path: '/previews'
      fullPath: '/projects/$projectId/applications/$appId/previews'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdPreviewsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/settings': {
      id: '/_app/projects/$projectId/applications/$appId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/applications/$appId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/storage': {
      id: '/_app/projects/$projectId/applications/$appId/storage'
      path: '/storage'
      fullPath: '/projects/$projectId/applications/$appId/storage'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdStorageRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/tasks': {
      id: '/_app/projects/$projectId/applications/$appId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/applications/$appId/tasks'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdTasksRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/compose/$stackId/': {
      id: '/_app/projects/$projectId/compose/$stackId/'
      path: '/'
      fullPath: '/projects/$projectId/compose/$stackId/'
      preLoaderRoute: typeof AppProjectsProjectIdComposeStackIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdComposeStackIdRoute
    }
    '/_app/projects/$projectId/compose/$stackId/env': {
      id: '/_app/projects/$projectId/compose/$stackId/env'
      path: '/env'
      fullPath: '/projects/$projectId/compose/$stackId/env'
      preLoaderRoute: typeof AppProjectsProjectIdComposeStackIdEnvRouteImport
      parentRoute: typeof AppProjectsProjectIdComposeStackIdRoute
    }
    '/_app/projects/$projectId/compose/$stackId/logs': {
      id: '/_app/projects/$projectId/compose/$stackId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/compose/$stackId/logs'
      preLoaderRoute: typeof AppProjectsProjectIdComposeStackIdLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdComposeStackIdRoute
    }
    '/_app/projects/$projectId/compose/$stackId/revisions': {
      id: '/_app/projects/$projectId/compose/$stackId/revisions'
      path: '/revisions'
      fullPath: '/projects/$projectId/compose/$stackId/revisions'
      preLoaderRoute: typeof AppProjectsProjectIdComposeStackIdRevisionsRouteImport
      parentRoute: typeof AppProjectsProjectIdComposeStackIdRoute
    }
    '/_app/projects/$projectId/compose/$stackId/settings': {
      id: '/_app/projects/$projectId/compose/$stackId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/compose/$stackId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdComposeStackIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdComposeStackIdRoute
    }
    '/_app/projects/$projectId/databases/$dbId/': {
      id: '/_app/projects/$projectId/databases/$dbId/'
      path: '/'
      fullPath: '/projects/$projectId/databases/$dbId/'
      preLoaderRoute: typeof AppProjectsProjectIdDatabasesDbIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdDatabasesDbIdRoute
    }
    '/_app/projects/$projectId/databases/$dbId/backups': {
      id: '/_app/projects/$projectId/databases/$dbId/backups'
      path: '/backups'
      fullPath: '/projects/$projectId/databases/$dbId/backups'
      preLoaderRoute: typeof AppProjectsProjectIdDatabasesDbIdBackupsRouteImport
      parentRoute: typeof AppProjectsProjectIdDatabasesDbIdRoute
    }
    '/_app/projects/$projectId/databases/$dbId/connection': {
      id: '/_app/projects/$projectId/databases/$dbId/connection'
      path: '/connection'
      fullPath: '/projects/$projectId/databases/$dbId/connection'
      preLoaderRoute: typeof AppProjectsProjectIdDatabasesDbIdConnectionRouteImport
      parentRoute: typeof AppProjectsProjectIdDatabasesDbIdRoute
    }
    '/_app/projects/$projectId/databases/$dbId/settings': {
      id: '/_app/projects/$projectId/databases/$dbId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/databases/$dbId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdDatabasesDbIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdDatabasesDbIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBackupTargetsRoute: typeof AppSettingsBackupTargetsRoute
  AppSettingsDeployKeysRoute: typeof AppSettingsDeployKeysRoute
  AppSettingsDnsRoute: typeof AppSettingsDnsRoute
  AppSettingsMailRoute: typeof AppSettingsMailRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsRegistriesRoute: typeof AppSettingsRegistriesRoute
  AppSettingsTeamsRoute: typeof AppSettingsTeamsRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBackupTargetsRoute: AppSettingsBackupTargetsRoute,
  AppSettingsDeployKeysRoute: AppSettingsDeployKeysRoute,
  AppSettingsDnsRoute: AppSettingsDnsRoute,
  AppSettingsMailRoute: AppSettingsMailRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsRegistriesRoute: AppSettingsRegistriesRoute,
  AppSettingsTeamsRoute: AppSettingsTeamsRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppProjectsProjectIdSettingsRouteChildren {
  AppProjectsProjectIdSettingsNotifiersRoute: typeof AppProjectsProjectIdSettingsNotifiersRoute
  AppProjectsProjectIdSettingsProtectionRoute: typeof AppProjectsProjectIdSettingsProtectionRoute
  AppProjectsProjectIdSettingsSharedVariablesRoute: typeof AppProjectsProjectIdSettingsSharedVariablesRoute
  AppProjectsProjectIdSettingsWebhooksRoute: typeof AppProjectsProjectIdSettingsWebhooksRoute
  AppProjectsProjectIdSettingsIndexRoute: typeof AppProjectsProjectIdSettingsIndexRoute
}

const AppProjectsProjectIdSettingsRouteChildren: AppProjectsProjectIdSettingsRouteChildren =
  {
    AppProjectsProjectIdSettingsNotifiersRoute:
      AppProjectsProjectIdSettingsNotifiersRoute,
    AppProjectsProjectIdSettingsProtectionRoute:
      AppProjectsProjectIdSettingsProtectionRoute,
    AppProjectsProjectIdSettingsSharedVariablesRoute:
      AppProjectsProjectIdSettingsSharedVariablesRoute,
    AppProjectsProjectIdSettingsWebhooksRoute:
      AppProjectsProjectIdSettingsWebhooksRoute,
    AppProjectsProjectIdSettingsIndexRoute:
      AppProjectsProjectIdSettingsIndexRoute,
  }

const AppProjectsProjectIdSettingsRouteWithChildren =
  AppProjectsProjectIdSettingsRoute._addFileChildren(
    AppProjectsProjectIdSettingsRouteChildren,
  )

interface AppProjectsProjectIdApplicationsAppIdRouteChildren {
  AppProjectsProjectIdApplicationsAppIdDeploymentsRoute: typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  AppProjectsProjectIdApplicationsAppIdEnvRoute: typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  AppProjectsProjectIdApplicationsAppIdLogsRoute: typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  AppProjectsProjectIdApplicationsAppIdPreviewsRoute: typeof AppProjectsProjectIdApplicationsAppIdPreviewsRoute
  AppProjectsProjectIdApplicationsAppIdSettingsRoute: typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  AppProjectsProjectIdApplicationsAppIdStorageRoute: typeof AppProjectsProjectIdApplicationsAppIdStorageRoute
  AppProjectsProjectIdApplicationsAppIdTasksRoute: typeof AppProjectsProjectIdApplicationsAppIdTasksRoute
  AppProjectsProjectIdApplicationsAppIdIndexRoute: typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
}

const AppProjectsProjectIdApplicationsAppIdRouteChildren: AppProjectsProjectIdApplicationsAppIdRouteChildren =
  {
    AppProjectsProjectIdApplicationsAppIdDeploymentsRoute:
      AppProjectsProjectIdApplicationsAppIdDeploymentsRoute,
    AppProjectsProjectIdApplicationsAppIdEnvRoute:
      AppProjectsProjectIdApplicationsAppIdEnvRoute,
    AppProjectsProjectIdApplicationsAppIdLogsRoute:
      AppProjectsProjectIdApplicationsAppIdLogsRoute,
    AppProjectsProjectIdApplicationsAppIdPreviewsRoute:
      AppProjectsProjectIdApplicationsAppIdPreviewsRoute,
    AppProjectsProjectIdApplicationsAppIdSettingsRoute:
      AppProjectsProjectIdApplicationsAppIdSettingsRoute,
    AppProjectsProjectIdApplicationsAppIdStorageRoute:
      AppProjectsProjectIdApplicationsAppIdStorageRoute,
    AppProjectsProjectIdApplicationsAppIdTasksRoute:
      AppProjectsProjectIdApplicationsAppIdTasksRoute,
    AppProjectsProjectIdApplicationsAppIdIndexRoute:
      AppProjectsProjectIdApplicationsAppIdIndexRoute,
  }

const AppProjectsProjectIdApplicationsAppIdRouteWithChildren =
  AppProjectsProjectIdApplicationsAppIdRoute._addFileChildren(
    AppProjectsProjectIdApplicationsAppIdRouteChildren,
  )

interface AppProjectsProjectIdComposeStackIdRouteChildren {
  AppProjectsProjectIdComposeStackIdEnvRoute: typeof AppProjectsProjectIdComposeStackIdEnvRoute
  AppProjectsProjectIdComposeStackIdLogsRoute: typeof AppProjectsProjectIdComposeStackIdLogsRoute
  AppProjectsProjectIdComposeStackIdRevisionsRoute: typeof AppProjectsProjectIdComposeStackIdRevisionsRoute
  AppProjectsProjectIdComposeStackIdSettingsRoute: typeof AppProjectsProjectIdComposeStackIdSettingsRoute
  AppProjectsProjectIdComposeStackIdIndexRoute: typeof AppProjectsProjectIdComposeStackIdIndexRoute
}

const AppProjectsProjectIdComposeStackIdRouteChildren: AppProjectsProjectIdComposeStackIdRouteChildren =
  {
    AppProjectsProjectIdComposeStackIdEnvRoute:
      AppProjectsProjectIdComposeStackIdEnvRoute,
    AppProjectsProjectIdComposeStackIdLogsRoute:
      AppProjectsProjectIdComposeStackIdLogsRoute,
    AppProjectsProjectIdComposeStackIdRevisionsRoute:
      AppProjectsProjectIdComposeStackIdRevisionsRoute,
    AppProjectsProjectIdComposeStackIdSettingsRoute:
      AppProjectsProjectIdComposeStackIdSettingsRoute,
    AppProjectsProjectIdComposeStackIdIndexRoute:
      AppProjectsProjectIdComposeStackIdIndexRoute,
  }

const AppProjectsProjectIdComposeStackIdRouteWithChildren =
  AppProjectsProjectIdComposeStackIdRoute._addFileChildren(
    AppProjectsProjectIdComposeStackIdRouteChildren,
  )

interface AppProjectsProjectIdDatabasesDbIdRouteChildren {
  AppProjectsProjectIdDatabasesDbIdBackupsRoute: typeof AppProjectsProjectIdDatabasesDbIdBackupsRoute
  AppProjectsProjectIdDatabasesDbIdConnectionRoute: typeof AppProjectsProjectIdDatabasesDbIdConnectionRoute
  AppProjectsProjectIdDatabasesDbIdSettingsRoute: typeof AppProjectsProjectIdDatabasesDbIdSettingsRoute
  AppProjectsProjectIdDatabasesDbIdIndexRoute: typeof AppProjectsProjectIdDatabasesDbIdIndexRoute
}

const AppProjectsProjectIdDatabasesDbIdRouteChildren: AppProjectsProjectIdDatabasesDbIdRouteChildren =
  {
    AppProjectsProjectIdDatabasesDbIdBackupsRoute:
      AppProjectsProjectIdDatabasesDbIdBackupsRoute,
    AppProjectsProjectIdDatabasesDbIdConnectionRoute:
      AppProjectsProjectIdDatabasesDbIdConnectionRoute,
    AppProjectsProjectIdDatabasesDbIdSettingsRoute:
      AppProjectsProjectIdDatabasesDbIdSettingsRoute,
    AppProjectsProjectIdDatabasesDbIdIndexRoute:
      AppProjectsProjectIdDatabasesDbIdIndexRoute,
  }

const AppProjectsProjectIdDatabasesDbIdRouteWithChildren =
  AppProjectsProjectIdDatabasesDbIdRoute._addFileChildren(
    AppProjectsProjectIdDatabasesDbIdRouteChildren,
  )

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppServersServerIdRoute: typeof AppServersServerIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppServersIndexRoute: typeof AppServersIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRouteWithChildren
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdApplicationsAppIdRoute: typeof AppProjectsProjectIdApplicationsAppIdRouteWithChildren
  AppProjectsProjectIdComposeStackIdRoute: typeof AppProjectsProjectIdComposeStackIdRouteWithChildren
  AppProjectsProjectIdDatabasesDbIdRoute: typeof AppProjectsProjectIdDatabasesDbIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppServersServerIdRoute: AppServersServerIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppServersIndexRoute: AppServersIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppProjectsProjectIdSettingsRoute:
    AppProjectsProjectIdSettingsRouteWithChildren,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdApplicationsAppIdRoute:
    AppProjectsProjectIdApplicationsAppIdRouteWithChildren,
  AppProjectsProjectIdComposeStackIdRoute:
    AppProjectsProjectIdComposeStackIdRouteWithChildren,
  AppProjectsProjectIdDatabasesDbIdRoute:
    AppProjectsProjectIdDatabasesDbIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
