/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppServersIndexRouteImport } from './routes/_app/servers/index'
import { Route as AppServersServerIdRouteImport } from './routes/_app/servers/$serverId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsBackupTargetsRouteImport } from './routes/_app/settings/backup-targets'
import { Route as AppSettingsDeployKeysRouteImport } from './routes/_app/settings/deploy-keys'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdApplicationsAppIdRouteImport } from './routes/_app/projects/$projectId/applications/$appId'
import { Route as AppProjectsProjectIdApplicationsAppIdIndexRouteImport } from './routes/_app/projects/$projectId/applications/$appId/index'
import { Route as AppProjectsProjectIdApplicationsAppIdDeploymentsRouteImport } from './routes/_app/projects/$projectId/applications/$appId/deployments'
import { Route as AppProjectsProjectIdApplicationsAppIdEnvRouteImport } from './routes/_app/projects/$projectId/applications/$appId/env'
import { Route as AppProjectsProjectIdApplicationsAppIdLogsRouteImport } from './routes/_app/projects/$projectId/applications/$appId/logs'
import { Route as AppProjectsProjectIdApplicationsAppIdSettingsRouteImport } from './routes/_app/projects/$projectId/applications/$appId/settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppServersIndexRoute = AppServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AppRoute,
} as any)
const AppServersServerIdRoute = AppServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBackupTargetsRoute =
  AppSettingsBackupTargetsRouteImport.update({
    id: '/backup-targets',
    path: '/backup-targets',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsDeployKeysRoute = AppSettingsDeployKeysRouteImport.update({
  id: '/deploy-keys',
  path: '/deploy-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdRoute =
  AppProjectsProjectIdApplicationsAppIdRouteImport.update({
    id: '/projects/$projectId/applications/$appId',
    path: '/projects/$projectId/applications/$appId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdIndexRoute =
  AppProjectsProjectIdApplicationsAppIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdDeploymentsRoute =
  AppProjectsProjectIdApplicationsAppIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdEnvRoute =
  AppProjectsProjectIdApplicationsAppIdEnvRouteImport.update({
    id: '/env',
    path: '/env',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdLogsRoute =
  AppProjectsProjectIdApplicationsAppIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)
const AppProjectsProjectIdApplicationsAppIdSettingsRoute =
  AppProjectsProjectIdApplicationsAppIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdApplicationsAppIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/settings/backup-targets': typeof AppSettingsBackupTargetsRoute
  '/settings/deploy-keys': typeof AppSettingsDeployKeysRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/servers/': typeof AppServersIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/applications/$appId': typeof AppProjectsProjectIdApplicationsAppIdRouteWithChildren
  '/projects/$projectId/applications/$appId/deployments': typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  '/projects/$projectId/applications/$appId/env': typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  '/projects/$projectId/applications/$appId/logs': typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  '/projects/$projectId/applications/$appId/settings': typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  '/projects/$projectId/applications/$appId/': typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/servers/$serverId': typeof AppServersServerIdRoute
  '/settings/backup-targets': typeof AppSettingsBackupTargetsRoute
  '/settings/deploy-keys': typeof AppSettingsDeployKeysRoute
  '/projects': typeof AppProjectsIndexRoute
  '/servers': typeof AppServersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/applications/$appId/deployments': typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  '/projects/$projectId/applications/$appId/env': typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  '/projects/$projectId/applications/$appId/logs': typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  '/projects/$projectId/applications/$appId/settings': typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  '/projects/$projectId/applications/$appId': typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/servers/$serverId': typeof AppServersServerIdRoute
  '/_app/settings/backup-targets': typeof AppSettingsBackupTargetsRoute
  '/_app/settings/deploy-keys': typeof AppSettingsDeployKeysRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/servers/': typeof AppServersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/applications/$appId': typeof AppProjectsProjectIdApplicationsAppIdRouteWithChildren
  '/_app/projects/$projectId/applications/$appId/deployments': typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  '/_app/projects/$projectId/applications/$appId/env': typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  '/_app/projects/$projectId/applications/$appId/logs': typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  '/_app/projects/$projectId/applications/$appId/settings': typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  '/_app/projects/$projectId/applications/$appId/': typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/servers/$serverId'
    | '/settings/backup-targets'
    | '/settings/deploy-keys'
    | '/projects/'
    | '/servers/'
    | '/settings/'
    | '/templates/'
    | '/projects/$projectId/'
    | '/projects/$projectId/applications/$appId'
    | '/projects/$projectId/applications/$appId/deployments'
    | '/projects/$projectId/applications/$appId/env'
    | '/projects/$projectId/applications/$appId/logs'
    | '/projects/$projectId/applications/$appId/settings'
    | '/projects/$projectId/applications/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/servers/$serverId'
    | '/settings/backup-targets'
    | '/settings/deploy-keys'
    | '/projects'
    | '/servers'
    | '/settings'
    | '/templates'
    | '/projects/$projectId'
    | '/projects/$projectId/applications/$appId/deployments'
    | '/projects/$projectId/applications/$appId/env'
    | '/projects/$projectId/applications/$appId/logs'
    | '/projects/$projectId/applications/$appId/settings'
    | '/projects/$projectId/applications/$appId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/settings'
    | '/_app/'
    | '/_app/servers/$serverId'
    | '/_app/settings/backup-targets'
    | '/_app/settings/deploy-keys'
    | '/_app/projects/'
    | '/_app/servers/'
    | '/_app/settings/'
    | '/_app/templates/'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/applications/$appId'
    | '/_app/projects/$projectId/applications/$appId/deployments'
    | '/_app/projects/$projectId/applications/$appId/env'
    | '/_app/projects/$projectId/applications/$appId/logs'
    | '/_app/projects/$projectId/applications/$appId/settings'
    | '/_app/projects/$projectId/applications/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/': {
      id: '/_app/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AppServersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$serverId': {
      id: '/_app/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AppServersServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/backup-targets': {
      id: '/_app/settings/backup-targets'
      path: '/backup-targets'
      fullPath: '/settings/backup-targets'
      preLoaderRoute: typeof AppSettingsBackupTargetsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/deploy-keys': {
      id: '/_app/settings/deploy-keys'
      path: '/deploy-keys'
      fullPath: '/settings/deploy-keys'
      preLoaderRoute: typeof AppSettingsDeployKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/applications/$appId': {
      id: '/_app/projects/$projectId/applications/$appId'
      path: '/projects/$projectId/applications/$appId'
      fullPath: '/projects/$projectId/applications/$appId'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/applications/$appId/': {
      id: '/_app/projects/$projectId/applications/$appId/'
      path: '/'
      fullPath: '/projects/$projectId/applications/$appId/'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/deployments': {
      id: '/_app/projects/$projectId/applications/$appId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/applications/$appId/deployments'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/env': {
      id: '/_app/projects/$projectId/applications/$appId/env'
      path: '/env'
      fullPath: '/projects/$projectId/applications/$appId/env'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdEnvRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/logs': {
      id: '/_app/projects/$projectId/applications/$appId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/applications/$appId/logs'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdLogsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
    '/_app/projects/$projectId/applications/$appId/settings': {
      id: '/_app/projects/$projectId/applications/$appId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/applications/$appId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdApplicationsAppIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdApplicationsAppIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsBackupTargetsRoute: typeof AppSettingsBackupTargetsRoute
  AppSettingsDeployKeysRoute: typeof AppSettingsDeployKeysRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBackupTargetsRoute: AppSettingsBackupTargetsRoute,
  AppSettingsDeployKeysRoute: AppSettingsDeployKeysRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppProjectsProjectIdApplicationsAppIdRouteChildren {
  AppProjectsProjectIdApplicationsAppIdDeploymentsRoute: typeof AppProjectsProjectIdApplicationsAppIdDeploymentsRoute
  AppProjectsProjectIdApplicationsAppIdEnvRoute: typeof AppProjectsProjectIdApplicationsAppIdEnvRoute
  AppProjectsProjectIdApplicationsAppIdLogsRoute: typeof AppProjectsProjectIdApplicationsAppIdLogsRoute
  AppProjectsProjectIdApplicationsAppIdSettingsRoute: typeof AppProjectsProjectIdApplicationsAppIdSettingsRoute
  AppProjectsProjectIdApplicationsAppIdIndexRoute: typeof AppProjectsProjectIdApplicationsAppIdIndexRoute
}

const AppProjectsProjectIdApplicationsAppIdRouteChildren: AppProjectsProjectIdApplicationsAppIdRouteChildren =
  {
    AppProjectsProjectIdApplicationsAppIdDeploymentsRoute:
      AppProjectsProjectIdApplicationsAppIdDeploymentsRoute,
    AppProjectsProjectIdApplicationsAppIdEnvRoute:
      AppProjectsProjectIdApplicationsAppIdEnvRoute,
    AppProjectsProjectIdApplicationsAppIdLogsRoute:
      AppProjectsProjectIdApplicationsAppIdLogsRoute,
    AppProjectsProjectIdApplicationsAppIdSettingsRoute:
      AppProjectsProjectIdApplicationsAppIdSettingsRoute,
    AppProjectsProjectIdApplicationsAppIdIndexRoute:
      AppProjectsProjectIdApplicationsAppIdIndexRoute,
  }

const AppProjectsProjectIdApplicationsAppIdRouteWithChildren =
  AppProjectsProjectIdApplicationsAppIdRoute._addFileChildren(
    AppProjectsProjectIdApplicationsAppIdRouteChildren,
  )

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppServersServerIdRoute: typeof AppServersServerIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppServersIndexRoute: typeof AppServersIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdApplicationsAppIdRoute: typeof AppProjectsProjectIdApplicationsAppIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppServersServerIdRoute: AppServersServerIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppServersIndexRoute: AppServersIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdApplicationsAppIdRoute:
    AppProjectsProjectIdApplicationsAppIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
